import type { ConversationSource } from '../types';

const T = 'Tú';

export const CONVERSATIONS_ADVANCED: ConversationSource[] = [
  /* ---------------- A2 ---------------- */
  {
    id: 'c-finde',
    level: 'A2',
    title: 'Montagmorgen: Wie war dein Wochenende?',
    emoji: '☕',
    setting: 'Montag im Büro – deine Kollegin fragt nach deinem Wochenende.',
    roles: { M: 'Marta', [T]: 'Du' },
    you: T,
    lines: [
      ['M', '¡Buenos días! ¿Qué tal el finde?', 'Guten Morgen! Wie war das Wochenende?'],
      [T, 'Genial. El sábado fui a la playa con unos amigos.', 'Super. Am Samstag war ich mit Freunden am Strand.'],
      ['M', '¡Qué envidia! ¿Y qué tal el agua?', 'Wie beneidenswert! Und wie war das Wasser?'],
      [T, 'Estaba fría, pero nos bañamos igual.', 'Es war kalt, aber wir sind trotzdem baden gegangen.'],
      ['M', 'Yo no hice nada especial. Estuve en casa limpiando.', 'Ich habe nichts Besonderes gemacht. Ich war zu Hause und habe geputzt.'],
      [T, 'Bueno, a veces también hace falta.', 'Na ja, manchmal muss das auch sein.'],
      ['M', 'Ya… ¡Venga, a trabajar!', 'Tja… Los, an die Arbeit!'],
    ],
    keyPhrases: [
      ['¡Qué envidia!', 'Wie beneidenswert!'],
      ['igual', 'trotzdem (umgangssprachlich)'],
      ['hace falta', 'es ist nötig'],
    ],
  },
  {
    id: 'c-hotel-problema',
    level: 'A2',
    title: 'Problem im Hotelzimmer',
    emoji: '🛎️',
    setting: 'Die Dusche in deinem Hotelzimmer funktioniert nicht. Du rufst die Rezeption an.',
    roles: { R: 'Recepción', [T]: 'Du' },
    you: T,
    lines: [
      ['R', 'Recepción, ¿dígame?', 'Rezeption, bitte?'],
      [T, 'Hola, llamo de la habitación 214. La ducha no funciona.', 'Hallo, ich rufe aus Zimmer 214 an. Die Dusche funktioniert nicht.'],
      ['R', '¿No sale agua?', 'Kommt kein Wasser?'],
      [T, 'Sale agua, pero está completamente fría.', 'Es kommt Wasser, aber es ist komplett kalt.'],
      ['R', 'Lo siento mucho. Ahora mismo subimos a mirarlo.', 'Das tut mir sehr leid. Wir kommen sofort hoch und sehen nach.'],
      [T, 'Gracias. ¿Y si no se puede arreglar?', 'Danke. Und wenn es sich nicht reparieren lässt?'],
      ['R', 'En ese caso le cambiamos de habitación.', 'In dem Fall geben wir Ihnen ein anderes Zimmer.'],
      [T, 'Perfecto, muchas gracias.', 'Perfekt, vielen Dank.'],
    ],
    keyPhrases: [
      ['ahora mismo', 'sofort / gerade jetzt'],
      ['arreglar', 'reparieren'],
    ],
  },
  {
    id: 'c-medico',
    level: 'A2',
    title: 'Beim Hausarzt',
    emoji: '🩺',
    setting: 'Du fühlst dich seit Tagen schlecht und bist beim Arzt.',
    roles: { D: 'Doctora', [T]: 'Du' },
    you: T,
    lines: [
      ['D', 'Pase, siéntese. ¿Qué le pasa?', 'Kommen Sie, setzen Sie sich. Was fehlt Ihnen?'],
      [T, 'Llevo tres días con fiebre y me duele todo el cuerpo.', 'Ich habe seit drei Tagen Fieber und mir tut alles weh.'],
      ['D', '¿Ha tomado algo?', 'Haben Sie etwas genommen?'],
      [T, 'Solo paracetamol.', 'Nur Paracetamol.'],
      ['D', 'A ver, abra la boca… Parece una gripe.', 'Mal sehen, öffnen Sie den Mund… Sieht nach Grippe aus.'],
      [T, '¿Es grave?', 'Ist es schlimm?'],
      ['D', 'No, pero tiene que descansar y beber mucha agua. Le doy la baja para tres días.', 'Nein, aber Sie müssen sich ausruhen und viel Wasser trinken. Ich schreibe Sie drei Tage krank.'],
      [T, 'De acuerdo. Muchas gracias, doctora.', 'Einverstanden. Vielen Dank, Frau Doktor.'],
    ],
    keyPhrases: [
      ['¿Qué le pasa?', 'Was fehlt Ihnen?'],
      ['dar la baja', 'krankschreiben'],
      ['A ver…', 'Mal sehen …'],
    ],
  },
  {
    id: 'c-quedar',
    level: 'A2',
    title: 'Verabredung per Sprachnachricht',
    emoji: '🎧',
    setting: 'Dein Freund Javi will am Wochenende etwas unternehmen.',
    roles: { J: 'Javi', [T]: 'Du' },
    you: T,
    lines: [
      ['J', 'Oye, ¿qué haces el sábado? ¿Te apetece ir a un concierto?', 'Hey, was machst du am Samstag? Hast du Lust auf ein Konzert?'],
      [T, '¡Claro! ¿De quién es el concierto?', 'Klar! Wer spielt denn?'],
      ['J', 'De un grupo indie de Barcelona. Las entradas cuestan veinte euros.', 'Eine Indie-Band aus Barcelona. Die Tickets kosten zwanzig Euro.'],
      [T, 'Vale, me parece bien. ¿A qué hora empieza?', 'Okay, klingt gut. Wann fängt es an?'],
      ['J', 'A las diez. ¿Quedamos antes para cenar?', 'Um zehn. Treffen wir uns vorher zum Abendessen?'],
      [T, 'Perfecto. ¿A las ocho en la plaza?', 'Perfekt. Um acht auf dem Platz?'],
      ['J', '¡Hecho! Compro las entradas ahora.', 'Abgemacht! Ich kaufe jetzt die Tickets.'],
    ],
    keyPhrases: [
      ['¡Hecho!', 'Abgemacht!'],
      ['me parece bien', 'finde ich gut'],
    ],
  },
  {
    id: 'c-piso',
    level: 'A2',
    title: 'Wohnungsbesichtigung',
    emoji: '🏢',
    setting: 'Du besichtigst ein Zimmer in einer WG.',
    roles: { C: 'Clara', [T]: 'Du' },
    you: T,
    lines: [
      ['C', '¡Hola! Pasa, pasa. Esta es la cocina y aquí está el salón.', 'Hallo! Komm rein. Das ist die Küche und hier ist das Wohnzimmer.'],
      [T, '¡Qué luminoso! ¿Y la habitación?', 'Wie hell! Und das Zimmer?'],
      ['C', 'Es esta, al fondo. Tiene armario y escritorio.', 'Es ist dieses hier, hinten. Es hat einen Schrank und einen Schreibtisch.'],
      [T, '¿Cuánto es el alquiler?', 'Wie hoch ist die Miete?'],
      ['C', 'Cuatrocientos al mes, con gastos incluidos.', 'Vierhundert im Monat, mit Nebenkosten.'],
      [T, '¿Y cuántos sois en el piso?', 'Und wie viele seid ihr in der Wohnung?'],
      ['C', 'Somos tres, todos trabajamos. Es un piso tranquilo.', 'Wir sind drei, alle berufstätig. Es ist eine ruhige Wohnung.'],
      [T, 'Me gusta mucho. ¿Cuándo me puedes decir algo?', 'Gefällt mir sehr. Wann kannst du mir Bescheid geben?'],
      ['C', 'Te escribo mañana, ¿vale?', 'Ich schreibe dir morgen, okay?'],
    ],
  },
  {
    id: 'c-cumple',
    level: 'A2',
    title: 'Geburtstagsparty',
    emoji: '🎂',
    setting: 'Du kommst zur Geburtstagsfeier einer Freundin.',
    roles: { S: 'Sara', [T]: 'Du' },
    you: T,
    lines: [
      [T, '¡Felicidades, Sara! Toma, esto es para ti.', 'Herzlichen Glückwunsch, Sara! Hier, das ist für dich.'],
      ['S', '¡Ay, gracias! No hacía falta. ¿Lo puedo abrir?', 'Oh, danke! Das wäre nicht nötig gewesen. Darf ich es aufmachen?'],
      [T, 'Claro, ábrelo.', 'Klar, mach es auf.'],
      ['S', '¡Un libro de cocina mexicana! ¡Me encanta!', 'Ein mexikanisches Kochbuch! Ich liebe es!'],
      [T, 'Me alegro. Así me invitas a cenar.', 'Das freut mich. Dann lädst du mich zum Essen ein.'],
      ['S', '¡Trato hecho! Sírvete algo de beber.', 'Abgemacht! Nimm dir was zu trinken.'],
    ],
    keyPhrases: [
      ['No hacía falta.', 'Das wäre nicht nötig gewesen.'],
      ['Sírvete.', 'Bedien dich.'],
    ],
    tip: 'In Spanien und Lateinamerika öffnet man Geschenke meist sofort vor allen.',
  },
  {
    id: 'c-aeropuerto',
    level: 'A2',
    title: 'Check-in am Flughafen',
    emoji: '🛄',
    setting: 'Du checkst für deinen Flug nach Buenos Aires ein.',
    roles: { A: 'Azafata', [T]: 'Du' },
    you: T,
    lines: [
      ['A', 'Buenos días. Su pasaporte, por favor.', 'Guten Morgen. Ihren Pass, bitte.'],
      [T, 'Aquí tiene.', 'Bitte sehr.'],
      ['A', '¿Va a facturar alguna maleta?', 'Möchten Sie einen Koffer aufgeben?'],
      [T, 'Sí, esta. Y llevo una mochila de equipaje de mano.', 'Ja, diesen. Und ich habe einen Rucksack als Handgepäck.'],
      ['A', '¿Prefiere ventanilla o pasillo?', 'Lieber Fenster oder Gang?'],
      [T, 'Ventanilla, si es posible.', 'Fenster, wenn möglich.'],
      ['A', 'Aquí tiene su tarjeta de embarque. Embarca por la puerta 23 a las once y media.', 'Hier ist Ihre Bordkarte. Boarding ist an Gate 23 um halb zwölf.'],
      [T, 'Gracias. ¿El vuelo va con retraso?', 'Danke. Hat der Flug Verspätung?'],
      ['A', 'De momento sale a su hora. ¡Buen viaje!', 'Im Moment ist er pünktlich. Gute Reise!'],
    ],
    keyPhrases: [
      ['ventanilla o pasillo', 'Fenster oder Gang'],
      ['a su hora', 'pünktlich'],
      ['¡Buen viaje!', 'Gute Reise!'],
    ],
  },
  {
    id: 'c-telefono',
    level: 'A2',
    title: 'Tisch telefonisch reservieren',
    emoji: '☎️',
    setting: 'Du rufst ein Restaurant an, um für Freitag zu reservieren.',
    roles: { R: 'Restaurante', [T]: 'Du' },
    you: T,
    lines: [
      ['R', 'Restaurante La Huerta, ¿dígame?', 'Restaurant La Huerta, bitte?'],
      [T, 'Hola, quería reservar una mesa para el viernes.', 'Hallo, ich wollte für Freitag einen Tisch reservieren.'],
      ['R', '¿Para cuántas personas?', 'Für wie viele Personen?'],
      [T, 'Para cuatro, a las nueve y media.', 'Für vier, um halb zehn.'],
      ['R', 'A las nueve y media lo tengo completo. ¿Le va bien a las diez?', 'Um halb zehn bin ich voll. Passt Ihnen zehn Uhr?'],
      [T, 'Sí, a las diez está bien.', 'Ja, zehn Uhr ist gut.'],
      ['R', '¿A nombre de quién?', 'Auf welchen Namen?'],
      [T, 'A nombre de Weber. W-E-B-E-R.', 'Auf den Namen Weber. W-E-B-E-R.'],
      ['R', 'Perfecto, apuntado. ¡Hasta el viernes!', 'Perfekt, notiert. Bis Freitag!'],
    ],
    keyPhrases: [
      ['Quería reservar…', 'Ich wollte reservieren …'],
      ['¿Le va bien…?', 'Passt es Ihnen …?'],
      ['apuntado', 'notiert'],
    ],
  },
  {
    id: 'c-recuerdos',
    level: 'A2',
    title: 'Kindheitserinnerungen',
    emoji: '🧒',
    setting: 'Du sprichst mit deiner Gastmutter über früher.',
    roles: { P: 'Pilar', [T]: 'Du' },
    you: T,
    lines: [
      ['P', '¿Y tú dónde vivías de pequeño?', 'Und wo hast du als Kind gewohnt?'],
      [T, 'Vivía en un pueblo cerca de Stuttgart.', 'Ich wohnte in einem Dorf in der Nähe von Stuttgart.'],
      ['P', '¿Y qué hacías en verano?', 'Und was hast du im Sommer gemacht?'],
      [T, 'Siempre iba al lago con mis primos. Nadábamos todo el día.', 'Ich ging immer mit meinen Cousins zum See. Wir schwammen den ganzen Tag.'],
      ['P', '¡Qué bonito! Yo, de niña, pasaba los veranos en el pueblo de mis abuelos.', 'Wie schön! Ich habe als Kind die Sommer im Dorf meiner Großeltern verbracht.'],
      [T, '¿Y lo echas de menos?', 'Und vermisst du das?'],
      ['P', 'Muchísimo. Eran otros tiempos.', 'Sehr. Das waren andere Zeiten.'],
    ],
  },
  /* ---------------- B1 ---------------- */
  {
    id: 'c-entrevista',
    level: 'B1',
    title: 'Vorstellungsgespräch',
    emoji: '👔',
    setting: 'Du hast ein Vorstellungsgespräch für eine Stelle in Barcelona.',
    roles: { E: 'Entrevistadora', [T]: 'Du' },
    you: T,
    lines: [
      ['E', 'Bueno, cuénteme un poco sobre usted.', 'Nun, erzählen Sie mir ein bisschen über sich.'],
      [T, 'Pues, soy ingeniero y llevo cinco años trabajando en el sector de la energía.', 'Also, ich bin Ingenieur und arbeite seit fünf Jahren im Energiesektor.'],
      ['E', '¿Por qué quiere trabajar con nosotros?', 'Warum möchten Sie bei uns arbeiten?'],
      [T, 'Me interesa mucho su proyecto de energías renovables y me gustaría vivir en España.', 'Ihr Projekt zu erneuerbaren Energien interessiert mich sehr und ich würde gern in Spanien leben.'],
      ['E', '¿Cuál diría que es su punto débil?', 'Was würden Sie als Ihre Schwäche bezeichnen?'],
      [T, 'A veces soy demasiado perfeccionista, pero estoy aprendiendo a delegar.', 'Manchmal bin ich zu perfektionistisch, aber ich lerne zu delegieren.'],
      ['E', 'Muy bien. ¿Tiene alguna pregunta para nosotros?', 'Sehr gut. Haben Sie Fragen an uns?'],
      [T, 'Sí, ¿cómo es un día normal en el equipo?', 'Ja, wie sieht ein normaler Tag im Team aus?'],
    ],
    keyPhrases: [
      ['Cuénteme…', 'Erzählen Sie mir …'],
      ['llevo cinco años trabajando', 'ich arbeite seit fünf Jahren'],
    ],
  },
  {
    id: 'c-reclamacion',
    level: 'B1',
    title: 'Reklamation im Elektroladen',
    emoji: '📦',
    setting: 'Die Kopfhörer, die du letzte Woche gekauft hast, sind kaputt.',
    roles: { D: 'Dependiente', [T]: 'Du' },
    you: T,
    lines: [
      [T, 'Buenas. Compré estos auriculares la semana pasada y ya no funcionan.', 'Guten Tag. Ich habe diese Kopfhörer letzte Woche gekauft und sie funktionieren schon nicht mehr.'],
      ['D', '¿Tiene el ticket de compra?', 'Haben Sie den Kassenbon?'],
      [T, 'Sí, aquí lo tiene.', 'Ja, hier ist er.'],
      ['D', 'Vale. Se los podemos mandar al servicio técnico. Tardan unas dos semanas.', 'Okay. Wir können sie zum Kundendienst schicken. Das dauert etwa zwei Wochen.'],
      [T, 'Preferiría que me los cambiaran por unos nuevos.', 'Mir wäre lieber, wenn Sie sie gegen neue umtauschen.'],
      ['D', 'Déjeme consultarlo con el encargado… De acuerdo, se los cambiamos.', 'Lassen Sie mich mit dem Filialleiter sprechen… In Ordnung, wir tauschen sie um.'],
      [T, 'Muchas gracias, es muy amable.', 'Vielen Dank, sehr freundlich.'],
    ],
    keyPhrases: [
      ['Preferiría que…', 'Mir wäre lieber, wenn …'],
      ['el servicio técnico', 'der Kundendienst'],
    ],
  },
  {
    id: 'c-consejo-amigo',
    level: 'B1',
    title: 'Ein Freund braucht Rat',
    emoji: '🫂',
    setting: 'Dein Freund Leo ist unglücklich in seinem Job.',
    roles: { L: 'Leo', [T]: 'Du' },
    you: T,
    lines: [
      ['L', 'Estoy harto de mi trabajo. Mi jefe no me valora nada.', 'Ich habe die Nase voll von meinem Job. Mein Chef schätzt mich überhaupt nicht.'],
      [T, 'Vaya, lo siento. ¿Has hablado con él?', 'Oh je, das tut mir leid. Hast du mit ihm geredet?'],
      ['L', 'No, me da miedo que se enfade.', 'Nein, ich habe Angst, dass er sauer wird.'],
      [T, 'Yo que tú, se lo diría. Es mejor que sepa cómo te sientes.', 'An deiner Stelle würde ich es ihm sagen. Es ist besser, dass er weiß, wie du dich fühlst.'],
      ['L', '¿Y si no cambia nada?', 'Und wenn sich nichts ändert?'],
      [T, 'Pues entonces deberías buscar otra cosa. Vales mucho.', 'Dann solltest du dir etwas anderes suchen. Du bist viel wert.'],
      ['L', 'Tienes razón. Gracias por escucharme.', 'Du hast recht. Danke, dass du mir zuhörst.'],
      [T, 'Para eso están los amigos.', 'Dafür sind Freunde da.'],
    ],
    keyPhrases: [
      ['Vaya…', 'Oh je … / Na so was …'],
      ['Para eso están los amigos.', 'Dafür sind Freunde da.'],
    ],
  },
  {
    id: 'c-opinion-ciudad',
    level: 'B1',
    title: 'Stadt oder Land?',
    emoji: '🏙️',
    setting: 'Beim Abendessen diskutiert ihr, wo man besser lebt.',
    roles: { I: 'Irene', [T]: 'Du' },
    you: T,
    lines: [
      ['I', 'Yo no podría vivir en el campo. Me aburriría muchísimo.', 'Ich könnte nicht auf dem Land leben. Ich würde mich zu Tode langweilen.'],
      [T, 'Pues yo creo que en el campo se vive mucho mejor.', 'Also ich glaube, auf dem Land lebt es sich viel besser.'],
      ['I', '¿En serio? ¿Por qué lo dices?', 'Echt? Warum sagst du das?'],
      [T, 'Hay menos estrés, menos ruido y la vivienda es más barata.', 'Es gibt weniger Stress, weniger Lärm und Wohnen ist billiger.'],
      ['I', 'Ya, pero no hay cines, ni conciertos, ni nada.', 'Ja, aber es gibt keine Kinos, keine Konzerte, gar nichts.'],
      [T, 'Bueno, depende del pueblo. Y siempre puedes ir a la ciudad el fin de semana.', 'Na ja, kommt aufs Dorf an. Und am Wochenende kann man immer in die Stadt fahren.'],
      ['I', 'En eso tienes razón.', 'Da hast du recht.'],
    ],
  },
  {
    id: 'c-planes-futuro',
    level: 'B1',
    title: 'Pläne nach dem Studium',
    emoji: '🎓',
    setting: 'Eine Freundin erzählt von ihren Zukunftsplänen.',
    roles: { N: 'Nuria', [T]: 'Du' },
    you: T,
    lines: [
      ['N', 'Cuando termine la carrera, me iré un año a Latinoamérica.', 'Wenn ich das Studium beendet habe, gehe ich für ein Jahr nach Lateinamerika.'],
      [T, '¡Qué pasada! ¿Adónde quieres ir?', 'Wie genial! Wohin willst du?'],
      ['N', 'Primero a México y luego bajaré hasta Patagonia.', 'Zuerst nach Mexiko und dann fahre ich runter bis Patagonien.'],
      [T, '¿Y vas a trabajar allí?', 'Und wirst du dort arbeiten?'],
      ['N', 'Ojalá encuentre algo de voluntariado. ¿Y tú, qué harás?', 'Hoffentlich finde ich eine Freiwilligenarbeit. Und du, was wirst du machen?'],
      [T, 'Todavía no lo sé. Me gustaría quedarme en España un tiempo.', 'Ich weiß es noch nicht. Ich würde gern eine Zeit in Spanien bleiben.'],
    ],
    keyPhrases: [
      ['¡Qué pasada!', 'Wie genial!'],
      ['la carrera', 'das Studium'],
    ],
  },
  {
    id: 'c-vecino-ruido',
    level: 'B1',
    title: 'Der laute Nachbar',
    emoji: '🔊',
    setting: 'Es ist ein Uhr nachts und dein Nachbar feiert eine laute Party.',
    roles: { V: 'Vecino', [T]: 'Du' },
    you: T,
    lines: [
      ['V', '¡Hola! ¿Qué pasa?', 'Hallo! Was gibt’s?'],
      [T, 'Perdona que te moleste, pero es la una y mañana trabajo temprano.', 'Entschuldige die Störung, aber es ist eins und ich muss morgen früh arbeiten.'],
      ['V', 'Uy, ¿se oye mucho?', 'Oh, hört man es so sehr?'],
      [T, 'Bastante, la verdad. ¿Podríais bajar un poco la música?', 'Ziemlich, ehrlich gesagt. Könntet ihr die Musik etwas leiser machen?'],
      ['V', 'Claro, perdona. No me había dado cuenta.', 'Klar, sorry. Das hatte ich nicht gemerkt.'],
      [T, 'No pasa nada. ¡Que lo paséis bien!', 'Kein Problem. Viel Spaß noch!'],
    ],
    keyPhrases: [
      ['Perdona que te moleste…', 'Entschuldige die Störung …'],
      ['darse cuenta', 'merken'],
    ],
  },
  {
    id: 'c-receta',
    level: 'B1',
    title: 'Tortilla-Kochkurs bei der Oma',
    emoji: '🍳',
    setting: 'Die Oma deiner spanischen Freundin bringt dir bei, wie man Tortilla macht.',
    roles: { A: 'Abuela', [T]: 'Du' },
    you: T,
    lines: [
      ['A', 'Primero pela las patatas y córtalas finitas.', 'Zuerst die Kartoffeln schälen und ganz dünn schneiden.'],
      [T, '¿Así está bien?', 'Ist das so gut?'],
      ['A', 'Perfecto. Ahora fríelas a fuego lento con la cebolla.', 'Perfekt. Jetzt brate sie bei schwacher Hitze mit der Zwiebel.'],
      [T, '¿La tortilla lleva cebolla?', 'Kommt in die Tortilla Zwiebel?'],
      ['A', '¡Claro! Aunque hay gente que dice que no… Ahora bate los huevos.', 'Natürlich! Auch wenn manche Leute sagen, nein… Jetzt die Eier verquirlen.'],
      [T, '¿Cuántos huevos echo?', 'Wie viele Eier tue ich rein?'],
      ['A', 'Seis. Mézclalo todo y échale sal. Lo más difícil es darle la vuelta.', 'Sechs. Misch alles und gib Salz dazu. Das Schwierigste ist das Umdrehen.'],
      [T, '¡Qué miedo! Ayúdame tú, por favor.', 'Oh je! Hilf du mir bitte.'],
    ],
    keyPhrases: [
      ['darle la vuelta', 'umdrehen / wenden'],
      ['finito / finita', 'ganz dünn (Verkleinerung)'],
    ],
    tip: 'Ob Tortilla mit oder ohne Zwiebel gehört, ist in Spanien eine ewige Debatte: „con cebolla o sin cebolla“?',
  },
  {
    id: 'c-noticias',
    level: 'B1',
    title: 'Hast du schon gehört?',
    emoji: '📢',
    setting: 'Eine Kollegin erzählt dir den neuesten Klatsch aus der Firma.',
    roles: { R: 'Rocío', [T]: 'Du' },
    you: T,
    lines: [
      ['R', '¿Te has enterado? ¡Pablo se va de la empresa!', 'Hast du es gehört? Pablo verlässt die Firma!'],
      [T, '¿En serio? ¡No me digas! ¿Por qué?', 'Echt? Sag bloß! Warum?'],
      ['R', 'Dicen que le han ofrecido un puesto en Londres.', 'Man sagt, man hat ihm eine Stelle in London angeboten.'],
      [T, 'Pues me alegro por él, aunque lo vamos a echar de menos.', 'Na, das freut mich für ihn, auch wenn wir ihn vermissen werden.'],
      ['R', 'Ya ves. Habrá que organizarle una despedida.', 'Tja. Wir müssen ihm eine Abschiedsfeier organisieren.'],
      [T, '¡Buena idea! Yo me encargo del regalo.', 'Gute Idee! Ich kümmere mich um das Geschenk.'],
    ],
    keyPhrases: [
      ['¡No me digas!', 'Sag bloß!'],
      ['encargarse de', 'sich kümmern um'],
      ['Ya ves.', 'Tja. / Siehst du.'],
    ],
  },
  /* ---------------- B2 ---------------- */
  {
    id: 'c-debate-teletrabajo',
    level: 'B2',
    title: 'Debatte: Homeoffice',
    emoji: '🏠',
    setting: 'In einem Meeting diskutiert ihr, ob die Firma das Homeoffice abschaffen soll.',
    roles: { J: 'Jefe', [T]: 'Du' },
    you: T,
    lines: [
      ['J', 'La dirección está pensando en volver al cien por cien presencial. ¿Qué opináis?', 'Die Geschäftsführung überlegt, zu 100 % Präsenz zurückzukehren. Was meint ihr?'],
      [T, 'Desde mi punto de vista, sería un error. La productividad no ha bajado.', 'Aus meiner Sicht wäre das ein Fehler. Die Produktivität ist nicht gesunken.'],
      ['J', 'Ya, pero se pierde el contacto entre compañeros.', 'Ja, aber der Kontakt zwischen Kollegen geht verloren.'],
      [T, 'Es cierto; no obstante, se podría encontrar un término medio, como dos días en la oficina.', 'Das stimmt; trotzdem könnte man einen Mittelweg finden, zum Beispiel zwei Tage im Büro.'],
      ['J', '¿Y crees que eso convencería a la dirección?', 'Und glaubst du, das würde die Geschäftsführung überzeugen?'],
      [T, 'Si presentáramos datos concretos, seguramente sí.', 'Wenn wir konkrete Daten präsentieren würden, sicher schon.'],
      ['J', 'De acuerdo. Prepárame un informe para el lunes.', 'Einverstanden. Bereite mir bis Montag einen Bericht vor.'],
    ],
    keyPhrases: [
      ['un término medio', 'ein Mittelweg'],
      ['presencial', 'in Präsenz'],
    ],
  },
  {
    id: 'c-meter-pata',
    level: 'B2',
    title: 'Fettnäpfchen',
    emoji: '🙈',
    setting: 'Du erzählst einer Freundin von einem peinlichen Moment.',
    roles: { B: 'Bea', [T]: 'Du' },
    you: T,
    lines: [
      [T, 'No te lo vas a creer. Ayer metí la pata hasta el fondo.', 'Du wirst es nicht glauben. Gestern bin ich voll ins Fettnäpfchen getreten.'],
      ['B', '¿Qué pasó?', 'Was ist passiert?'],
      [T, 'Resulta que estaba hablando mal del nuevo director… y estaba justo detrás de mí.', 'Also, ich habe über den neuen Direktor gelästert… und er stand genau hinter mir.'],
      ['B', '¡Anda ya! ¿Y qué hiciste?', 'Ach komm! Und was hast du gemacht?'],
      [T, 'Me quedé de piedra. No sabía dónde meterme.', 'Ich war wie versteinert. Ich wäre am liebsten im Boden versunken.'],
      ['B', '¿Y él dijo algo?', 'Und hat er was gesagt?'],
      [T, 'Solo sonrió y dijo: „Encantado, soy el nuevo director“. ¡Qué vergüenza!', 'Er hat nur gelächelt und gesagt: „Freut mich, ich bin der neue Direktor“. Wie peinlich!'],
      ['B', 'Bueno, por lo menos tiene sentido del humor.', 'Na ja, wenigstens hat er Humor.'],
    ],
    keyPhrases: [
      ['meter la pata', 'ins Fettnäpfchen treten'],
      ['no saber dónde meterse', 'am liebsten im Boden versinken'],
      ['¡Qué vergüenza!', 'Wie peinlich!'],
    ],
    tip: '„Vergüenza“ heißt Scham/Peinlichkeit. „Embarazada“ heißt NICHT „peinlich berührt“, sondern schwanger – ein klassischer falscher Freund!',
  },
  {
    id: 'c-negociar-mercado',
    level: 'B2',
    title: 'Feilschen auf dem Markt',
    emoji: '🧺',
    setting: 'Auf einem Kunsthandwerksmarkt in Mexiko willst du einen Teppich kaufen.',
    roles: { V: 'Vendedor', [T]: 'Du' },
    you: T,
    lines: [
      ['V', 'Pásele, joven. ¿Le gusta el tapete? Está hecho a mano.', 'Kommen Sie, junger Mensch. Gefällt Ihnen der Teppich? Er ist handgemacht.'],
      [T, 'Es precioso. ¿Cuánto cuesta?', 'Er ist wunderschön. Was kostet er?'],
      ['V', 'Para usted, mil doscientos pesos.', 'Für Sie zwölfhundert Pesos.'],
      [T, 'Uf, es un poco caro para mí. ¿Me lo dejaría en ochocientos?', 'Puh, das ist etwas teuer für mich. Würden Sie ihn mir für achthundert geben?'],
      ['V', 'No, no puedo. Lo mínimo es mil.', 'Nein, das geht nicht. Das Minimum ist tausend.'],
      [T, '¿Y si me llevo también este cojín? ¿Mil por los dos?', 'Und wenn ich auch dieses Kissen nehme? Tausend für beides?'],
      ['V', 'Ándele pues, mil cien y es suyo.', 'Na gut, elfhundert und es gehört Ihnen.'],
      [T, '¡Trato hecho!', 'Abgemacht!'],
    ],
    keyPhrases: [
      ['¿Me lo dejaría en…?', 'Würden Sie es mir für … lassen?'],
      ['¡Ándele!', 'Na los! / Na gut! (Mexiko)'],
      ['Pásele.', 'Kommen Sie herein / rein damit (Mexiko)'],
    ],
    tip: 'Mexikanisches Spanisch ist sehr höflich: „¿Mande?“ statt „¿Qué?“, viel „usted“ und Verkleinerungen wie „ahorita“ (gleich – kann aber auch „irgendwann“ bedeuten!).',
  },
  {
    id: 'c-hipotesis-loteria',
    level: 'B2',
    title: 'Was wäre, wenn …?',
    emoji: '🎰',
    setting: 'Mit Freunden in der Bar spinnt ihr herum, was ihr mit einem Lottogewinn machen würdet.',
    roles: { A: 'Álex', [T]: 'Du' },
    you: T,
    lines: [
      ['A', 'Si te tocaran diez millones, ¿seguirías trabajando?', 'Wenn du zehn Millionen gewinnen würdest, würdest du weiterarbeiten?'],
      [T, 'Ni de broma. Lo dejaría al día siguiente.', 'Auf keinen Fall. Ich würde am nächsten Tag kündigen.'],
      ['A', '¿Y qué harías con tanto tiempo libre?', 'Und was würdest du mit so viel Freizeit machen?'],
      [T, 'Viajaría, aprendería idiomas y montaría un pequeño hotel rural.', 'Ich würde reisen, Sprachen lernen und ein kleines Landhotel eröffnen.'],
      ['A', 'O sea, que acabarías trabajando igual.', 'Also würdest du am Ende genauso arbeiten.'],
      [T, 'Ya, pero sería mi propio jefe. ¡No es lo mismo!', 'Ja, aber ich wäre mein eigener Chef. Das ist nicht dasselbe!'],
      ['A', 'Bueno, primero habría que jugar a la lotería…', 'Na ja, erst müsste man mal Lotto spielen…'],
    ],
    keyPhrases: [
      ['Ni de broma.', 'Auf keinen Fall.'],
      ['montar', 'gründen / aufmachen'],
      ['No es lo mismo.', 'Das ist nicht dasselbe.'],
    ],
  },
  {
    id: 'c-politica',
    level: 'B2',
    title: 'Wohnungsnot – eine Diskussion',
    emoji: '🏘️',
    setting: 'Du diskutierst mit einem Bekannten über die steigenden Mieten.',
    roles: { G: 'Gonzalo', [T]: 'Du' },
    you: T,
    lines: [
      ['G', 'Es una locura. Los alquileres han subido un treinta por ciento en dos años.', 'Das ist verrückt. Die Mieten sind in zwei Jahren um dreißig Prozent gestiegen.'],
      [T, 'Sí, y en gran parte es por los pisos turísticos.', 'Ja, und das liegt größtenteils an den Ferienwohnungen.'],
      ['G', 'No creo que sea solo eso. También faltan viviendas nuevas.', 'Ich glaube nicht, dass es nur daran liegt. Es fehlen auch neue Wohnungen.'],
      [T, 'Puede que tengas razón. Aun así, habría que limitar los pisos turísticos.', 'Kann sein, dass du recht hast. Trotzdem müsste man die Ferienwohnungen begrenzen.'],
      ['G', 'Estoy de acuerdo, siempre que no se perjudique a los pequeños propietarios.', 'Einverstanden, solange die kleinen Eigentümer nicht benachteiligt werden.'],
      [T, 'En definitiva, es un problema complejo que necesita varias soluciones.', 'Letztendlich ist es ein komplexes Problem, das mehrere Lösungen braucht.'],
    ],
    keyPhrases: [
      ['en gran parte', 'größtenteils'],
      ['aun así', 'trotzdem'],
      ['perjudicar', 'benachteiligen / schaden'],
    ],
  },
  {
    id: 'c-argentina',
    level: 'B2',
    title: 'Asado in Buenos Aires',
    emoji: '🥩',
    setting: 'Du bist bei argentinischen Freunden zum Asado eingeladen. Achtung: Hier wird „vos“ benutzt!',
    roles: { M: 'Martín', [T]: 'Du' },
    you: T,
    lines: [
      ['M', '¡Che, qué bueno que viniste! ¿Querés un mate?', 'Hey, wie schön, dass du gekommen bist! Willst du einen Mate?'],
      [T, 'Dale, gracias. Nunca he probado el mate.', 'Klar, danke. Ich habe noch nie Mate probiert.'],
      ['M', '¿En serio? Tomá. Es un poco amargo, pero te va a encantar.', 'Echt? Hier. Er ist etwas bitter, aber du wirst ihn lieben.'],
      [T, 'Mmm… ¡está bueno! ¿Y cuándo comemos?', 'Mmm… der ist gut! Und wann essen wir?'],
      ['M', 'Tranqui, el asado lleva su tiempo. ¿Vos sabés hacer asado?', 'Ganz ruhig, ein Asado braucht seine Zeit. Kannst du Asado machen?'],
      [T, 'Para nada. ¿Me enseñás?', 'Überhaupt nicht. Bringst du es mir bei?'],
      ['M', '¡Obvio! Vení, te muestro.', 'Na klar! Komm, ich zeig’s dir.'],
    ],
    keyPhrases: [
      ['vos querés / sabés / venís', 'du willst / weißt / kommst (Argentinien)'],
      ['¡Dale!', 'Okay! / Los!'],
      ['Tranqui.', 'Ganz ruhig.'],
    ],
    tip: 'In Argentinien und Uruguay ersetzt „vos“ das „tú“: vos tenés, vos sos, vos querés. Das „ll“ und „y“ werden wie „sch“ ausgesprochen: „calle“ ≈ „casche“.',
  },
  {
    id: 'c-medico-especialista',
    level: 'B2',
    title: 'Beim Facharzt',
    emoji: '🏥',
    setting: 'Du hast seit Wochen Rückenschmerzen und sprichst mit einem Spezialisten.',
    roles: { D: 'Traumatólogo', [T]: 'Du' },
    you: T,
    lines: [
      ['D', 'Cuénteme, ¿desde cuándo tiene molestias?', 'Erzählen Sie, seit wann haben Sie Beschwerden?'],
      [T, 'Hace como un mes. Empezó después de una mudanza.', 'Seit ungefähr einem Monat. Es fing nach einem Umzug an.'],
      ['D', '¿El dolor se le extiende a las piernas?', 'Strahlt der Schmerz in die Beine aus?'],
      [T, 'A veces noto un hormigueo en la pierna derecha, sobre todo si estoy mucho tiempo sentado.', 'Manchmal spüre ich ein Kribbeln im rechten Bein, vor allem wenn ich lange sitze.'],
      ['D', 'Le voy a pedir una resonancia para descartar una hernia.', 'Ich werde ein MRT anordnen, um einen Bandscheibenvorfall auszuschließen.'],
      [T, '¿Mientras tanto qué puedo hacer?', 'Was kann ich in der Zwischenzeit tun?'],
      ['D', 'Evite cargar peso y haga los ejercicios que le dará el fisioterapeuta.', 'Vermeiden Sie es, schwer zu tragen, und machen Sie die Übungen, die Ihnen der Physiotherapeut gibt.'],
    ],
    keyPhrases: [
      ['las molestias', 'die Beschwerden'],
      ['el hormigueo', 'das Kribbeln'],
      ['descartar', 'ausschließen'],
    ],
  },
];
