import type { ConversationSource } from '../types';

const T = 'Tú';

export const CONVERSATIONS_BASIC: ConversationSource[] = [
  {
    id: 'c-saludo-vecino',
    level: 'A0',
    title: 'Der Nachbar im Treppenhaus',
    emoji: '🚪',
    setting: 'Du triffst morgens deinen Nachbarn im Treppenhaus.',
    roles: { V: 'Vecino', [T]: 'Du' },
    you: T,
    lines: [
      ['V', '¡Buenos días!', 'Guten Morgen!'],
      [T, '¡Buenos días! ¿Qué tal?', 'Guten Morgen! Wie geht’s?'],
      ['V', 'Bien, bien. ¿Y tú?', 'Gut, gut. Und dir?'],
      [T, 'Muy bien, gracias.', 'Sehr gut, danke.'],
      ['V', '¡Que tengas un buen día!', 'Hab einen schönen Tag!'],
      [T, 'Igualmente. ¡Hasta luego!', 'Gleichfalls. Bis später!'],
    ],
    keyPhrases: [
      ['¡Que tengas un buen día!', 'Hab einen schönen Tag!'],
      ['Igualmente.', 'Gleichfalls.'],
    ],
  },
  {
    id: 'c-presentarse',
    level: 'A0',
    title: 'Neue Leute kennenlernen',
    emoji: '🤝',
    setting: 'Auf einer Party stellt dich eine Freundin jemandem vor.',
    roles: { L: 'Lucía', [T]: 'Du' },
    you: T,
    lines: [
      ['L', 'Hola, soy Lucía. ¿Cómo te llamas?', 'Hallo, ich bin Lucía. Wie heißt du?'],
      [T, 'Me llamo Max. Encantado.', 'Ich heiße Max. Freut mich.'],
      ['L', 'Encantada. ¿De dónde eres?', 'Freut mich. Woher kommst du?'],
      [T, 'Soy de Alemania. ¿Y tú?', 'Ich komme aus Deutschland. Und du?'],
      ['L', 'Yo soy de aquí, de Valencia. ¡Hablas muy bien español!', 'Ich bin von hier, aus Valencia. Du sprichst sehr gut Spanisch!'],
      [T, 'Gracias, pero solo hablo un poco.', 'Danke, aber ich spreche nur ein bisschen.'],
    ],
    keyPhrases: [
      ['Solo hablo un poco.', 'Ich spreche nur ein bisschen.'],
      ['¿De dónde eres?', 'Woher kommst du?'],
    ],
    tip: 'Komplimente für dein Spanisch bekommst du oft – auch wenn du nur ein paar Wörter sprichst. ¡Aprovecha!',
  },
  {
    id: 'c-cafe',
    level: 'A0',
    title: 'Frühstück in der Bar',
    emoji: '🥐',
    setting: 'Du bestellst in einer spanischen Bar dein Frühstück.',
    roles: { C: 'Camarero', [T]: 'Du' },
    you: T,
    lines: [
      ['C', 'Buenos días. ¿Qué te pongo?', 'Guten Morgen. Was darf’s sein?'],
      [T, 'Un café con leche, por favor.', 'Einen Milchkaffee, bitte.'],
      ['C', '¿Algo para comer?', 'Etwas zu essen?'],
      [T, 'Sí, una tostada con tomate.', 'Ja, einen Toast mit Tomate.'],
      ['C', 'Muy bien. ¿Algo más?', 'Sehr gut. Noch etwas?'],
      [T, 'No, nada más. ¿Cuánto es?', 'Nein, nichts weiter. Wie viel macht das?'],
      ['C', 'Son tres euros.', 'Das macht drei Euro.'],
      [T, 'Aquí tienes. Gracias.', 'Bitte schön. Danke.'],
    ],
    keyPhrases: [
      ['¿Qué te pongo?', 'Was darf’s sein?'],
      ['Aquí tienes.', 'Bitte schön (beim Geben).'],
    ],
  },
  {
    id: 'c-no-entiendo',
    level: 'A0',
    title: 'Ich habe nicht verstanden',
    emoji: '😅',
    setting: 'Eine Frau fragt dich etwas auf der Straße, aber sie spricht sehr schnell.',
    roles: { S: 'Señora', [T]: 'Du' },
    you: T,
    lines: [
      ['S', 'Perdona, ¿sabes dónde está la calle Mayor?', 'Entschuldige, weißt du, wo die Calle Mayor ist?'],
      [T, 'Lo siento, no entiendo. ¿Puede hablar más despacio?', 'Tut mir leid, ich verstehe nicht. Können Sie langsamer sprechen?'],
      ['S', 'Claro. ¿Dónde… está… la calle Mayor?', 'Natürlich. Wo… ist… die Calle Mayor?'],
      [T, 'Ah, vale. No sé, no soy de aquí.', 'Ah, okay. Ich weiß nicht, ich bin nicht von hier.'],
      ['S', 'No pasa nada. ¡Gracias!', 'Kein Problem. Danke!'],
      [T, 'De nada. ¡Adiós!', 'Gern geschehen. Tschüss!'],
    ],
    keyPhrases: [
      ['No soy de aquí.', 'Ich bin nicht von hier.'],
      ['¿Puede hablar más despacio?', 'Können Sie langsamer sprechen?'],
    ],
  },
  {
    id: 'c-supermercado',
    level: 'A1',
    title: 'An der Supermarktkasse',
    emoji: '🧾',
    setting: 'Du bezahlst deinen Einkauf an der Kasse.',
    roles: { K: 'Cajera', [T]: 'Du' },
    you: T,
    lines: [
      ['K', 'Hola. ¿Necesitas bolsa?', 'Hallo. Brauchst du eine Tüte?'],
      [T, 'Sí, una, por favor.', 'Ja, eine, bitte.'],
      ['K', 'Son quince con treinta. ¿Tienes tarjeta de cliente?', 'Das macht fünfzehn dreißig. Hast du eine Kundenkarte?'],
      [T, 'No, no tengo. ¿Puedo pagar con tarjeta?', 'Nein, habe ich nicht. Kann ich mit Karte zahlen?'],
      ['K', 'Sí, claro. Acércala aquí.', 'Ja, klar. Halte sie hier dran.'],
      [T, 'Vale. ¿Me da el ticket, por favor?', 'Okay. Geben Sie mir bitte den Bon?'],
      ['K', 'Aquí tienes. ¡Que vaya bien!', 'Bitte schön. Mach’s gut!'],
      [T, '¡Gracias, igualmente!', 'Danke, gleichfalls!'],
    ],
    keyPhrases: [
      ['¿Puedo pagar con tarjeta?', 'Kann ich mit Karte zahlen?'],
      ['¡Que vaya bien!', 'Mach’s gut!'],
    ],
  },
  {
    id: 'c-restaurante',
    level: 'A1',
    title: 'Abendessen im Restaurant',
    emoji: '🍷',
    setting: 'Du gehst mit einer Freundin essen und bestellst.',
    roles: { C: 'Camarera', [T]: 'Du' },
    you: T,
    lines: [
      ['C', 'Buenas noches. ¿Cuántos son?', 'Guten Abend. Wie viele sind Sie?'],
      [T, 'Somos dos. ¿Hay mesa en la terraza?', 'Wir sind zwei. Gibt es einen Tisch auf der Terrasse?'],
      ['C', 'Sí, pasad por aquí. ¿Qué queréis beber?', 'Ja, kommt hier entlang. Was wollt ihr trinken?'],
      [T, 'Una botella de agua y dos copas de vino tinto.', 'Eine Flasche Wasser und zwei Gläser Rotwein.'],
      ['C', '¿Y para comer?', 'Und zum Essen?'],
      [T, 'De primero, unas croquetas para compartir, y de segundo, pescado a la plancha.', 'Als Vorspeise Kroketten zum Teilen und als Hauptgang gegrillten Fisch.'],
      ['C', 'Perfecto. ¿Algo más?', 'Perfekt. Sonst noch etwas?'],
      [T, 'De momento, nada más. Gracias.', 'Im Moment nichts weiter. Danke.'],
    ],
    keyPhrases: [
      ['para compartir', 'zum Teilen'],
      ['De momento, nada más.', 'Im Moment nichts weiter.'],
      ['a la plancha', 'gegrillt (von der Platte)'],
    ],
    tip: 'Tapas und Raciones werden in Spanien gern geteilt – bestell ein paar Sachen „para compartir“.',
  },
  {
    id: 'c-direcciones',
    level: 'A1',
    title: 'Den Weg zum Museum finden',
    emoji: '🧭',
    setting: 'Du suchst das Museum und fragst einen Passanten.',
    roles: { P: 'Peatón', [T]: 'Du' },
    you: T,
    lines: [
      [T, 'Perdone, ¿cómo llego al museo del Prado?', 'Entschuldigen Sie, wie komme ich zum Prado-Museum?'],
      ['P', 'Mira, sigue esta calle todo recto hasta la plaza.', 'Schau, geh diese Straße geradeaus bis zum Platz.'],
      [T, '¿Hasta la plaza? Vale.', 'Bis zum Platz? Okay.'],
      ['P', 'Allí giras a la izquierda y lo ves enseguida.', 'Dort biegst du links ab und siehst es sofort.'],
      [T, '¿Está lejos?', 'Ist es weit?'],
      ['P', 'No, a unos diez minutos andando.', 'Nein, ungefähr zehn Minuten zu Fuß.'],
      [T, 'Muchísimas gracias.', 'Tausend Dank.'],
      ['P', 'De nada, ¡que disfrutes!', 'Gern, viel Spaß!'],
    ],
    keyPhrases: [
      ['enseguida', 'sofort'],
      ['andando', 'zu Fuß'],
      ['¡Que disfrutes!', 'Viel Spaß! / Genieß es!'],
    ],
  },
  {
    id: 'c-ropa',
    level: 'A1',
    title: 'Jeans kaufen',
    emoji: '👖',
    setting: 'Du bist in einem Kleidungsgeschäft und suchst eine Hose.',
    roles: { D: 'Dependienta', [T]: 'Du' },
    you: T,
    lines: [
      ['D', 'Hola, ¿te puedo ayudar en algo?', 'Hallo, kann ich dir helfen?'],
      [T, 'Sí, busco unos vaqueros negros.', 'Ja, ich suche eine schwarze Jeans.'],
      ['D', '¿Qué talla usas?', 'Welche Größe trägst du?'],
      [T, 'La cuarenta, creo.', 'Die 40, glaube ich.'],
      ['D', 'Aquí tienes. Los probadores están al fondo.', 'Bitte schön. Die Umkleiden sind hinten.'],
      [T, 'Me quedan un poco pequeños. ¿Los tiene en la cuarenta y dos?', 'Die sind mir etwas zu klein. Haben Sie die in 42?'],
      ['D', 'Sí, toma. ¿Qué tal?', 'Ja, hier. Und?'],
      [T, 'Perfectos. Me los llevo.', 'Perfekt. Ich nehme sie.'],
    ],
    keyPhrases: [
      ['al fondo', 'hinten'],
      ['Me los llevo.', 'Ich nehme sie.'],
    ],
  },
  {
    id: 'c-taxi',
    level: 'A1',
    title: 'Mit dem Taxi zum Hotel',
    emoji: '🚕',
    setting: 'Du kommst am Flughafen an und nimmst ein Taxi.',
    roles: { X: 'Taxista', [T]: 'Du' },
    you: T,
    lines: [
      ['X', 'Buenas tardes. ¿Adónde vamos?', 'Guten Tag. Wohin geht’s?'],
      [T, 'Al hotel Sol, en la calle Alcalá, por favor.', 'Zum Hotel Sol, in der Calle Alcalá, bitte.'],
      ['X', 'Muy bien. ¿Es su primera vez en Madrid?', 'Sehr gut. Sind Sie zum ersten Mal in Madrid?'],
      [T, 'Sí, es mi primera vez. ¿Cuánto tiempo tardamos?', 'Ja, das erste Mal. Wie lange brauchen wir?'],
      ['X', 'Unos veinticinco minutos, si no hay tráfico.', 'Ungefähr fünfundzwanzig Minuten, wenn kein Verkehr ist.'],
      [T, 'Perfecto. ¿Puedo pagar con tarjeta?', 'Perfekt. Kann ich mit Karte zahlen?'],
      ['X', 'Sí, sin problema.', 'Ja, kein Problem.'],
    ],
    keyPhrases: [
      ['¿Cuánto tiempo tardamos?', 'Wie lange brauchen wir?'],
      ['si no hay tráfico', 'wenn kein Verkehr ist'],
    ],
  },
  {
    id: 'c-billete-tren',
    level: 'A1',
    title: 'Zugticket kaufen',
    emoji: '🚆',
    setting: 'Du kaufst am Schalter eine Fahrkarte nach Sevilla.',
    roles: { E: 'Empleado', [T]: 'Du' },
    you: T,
    lines: [
      [T, 'Hola, un billete para Sevilla, por favor.', 'Hallo, eine Fahrkarte nach Sevilla, bitte.'],
      ['E', '¿Solo ida o ida y vuelta?', 'Nur hin oder hin und zurück?'],
      [T, 'Ida y vuelta. Vuelvo el domingo.', 'Hin und zurück. Ich komme am Sonntag zurück.'],
      ['E', 'Hay un tren a las diez y otro a las doce y media.', 'Es gibt einen Zug um zehn und einen um halb eins.'],
      [T, 'El de las diez, por favor. ¿De qué andén sale?', 'Den um zehn, bitte. Von welchem Gleis fährt er?'],
      ['E', 'Del andén cuatro. Son ochenta euros.', 'Von Gleis vier. Das macht achtzig Euro.'],
      [T, 'Vale, aquí tiene.', 'Okay, bitte sehr.'],
    ],
  },
  {
    id: 'c-farmacia',
    level: 'A1',
    title: 'In der Apotheke',
    emoji: '💊',
    setting: 'Du hast Halsschmerzen und gehst in die Apotheke.',
    roles: { F: 'Farmacéutico', [T]: 'Du' },
    you: T,
    lines: [
      ['F', 'Hola, buenas. Dime.', 'Hallo. Was kann ich für dich tun?'],
      [T, 'Hola. Me duele mucho la garganta.', 'Hallo. Mein Hals tut sehr weh.'],
      ['F', '¿Tienes fiebre?', 'Hast du Fieber?'],
      [T, 'No, pero tengo un poco de tos.', 'Nein, aber ich habe etwas Husten.'],
      ['F', 'Te recomiendo estas pastillas. Una cada seis horas.', 'Ich empfehle dir diese Tabletten. Eine alle sechs Stunden.'],
      [T, 'Vale. ¿Y algo para la tos?', 'Okay. Und etwas gegen den Husten?'],
      ['F', 'Este jarabe va muy bien. ¡Que te mejores!', 'Dieser Sirup hilft sehr gut. Gute Besserung!'],
      [T, 'Muchas gracias.', 'Vielen Dank.'],
    ],
    keyPhrases: [
      ['Dime.', 'Sag mal / Was kann ich tun? (Verkäufer)'],
      ['¡Que te mejores!', 'Gute Besserung!'],
    ],
  },
  {
    id: 'c-hobbies',
    level: 'A1',
    title: 'Was machst du gern?',
    emoji: '🎸',
    setting: 'Du unterhältst dich mit einem neuen Kollegen in der Mittagspause.',
    roles: { D: 'Diego', [T]: 'Du' },
    you: T,
    lines: [
      ['D', '¿Y qué haces en tu tiempo libre?', 'Und was machst du in deiner Freizeit?'],
      [T, 'Me encanta cocinar y salir a correr.', 'Ich koche sehr gern und gehe joggen.'],
      ['D', '¡Qué bien! Yo juego al pádel los martes.', 'Wie schön! Ich spiele dienstags Padel.'],
      [T, '¿Pádel? Nunca he jugado.', 'Padel? Das habe ich noch nie gespielt.'],
      ['D', '¿En serio? ¡Tienes que probarlo! ¿Te vienes el martes?', 'Echt? Das musst du ausprobieren! Kommst du Dienstag mit?'],
      [T, '¡Vale, me apunto!', 'Okay, ich bin dabei!'],
    ],
    keyPhrases: [
      ['¿Te vienes?', 'Kommst du mit?'],
      ['¡Me apunto!', 'Ich bin dabei!'],
    ],
    tip: 'Pádel ist in Spanien und Argentinien extrem beliebt – eine Mischung aus Tennis und Squash.',
  },
  {
    id: 'c-familia',
    level: 'A1',
    title: 'Fotos von der Familie',
    emoji: '📸',
    setting: 'Eine Freundin zeigt dir Fotos auf ihrem Handy.',
    roles: { A: 'Ana', [T]: 'Du' },
    you: T,
    lines: [
      ['A', 'Mira, esta es mi familia.', 'Schau, das ist meine Familie.'],
      [T, '¡Qué foto tan bonita! ¿Quién es este?', 'Was für ein schönes Foto! Wer ist das?'],
      ['A', 'Es mi hermano mayor, Rubén. Vive en Chile.', 'Das ist mein älterer Bruder, Rubén. Er lebt in Chile.'],
      [T, '¿Y la niña?', 'Und das Mädchen?'],
      ['A', 'Es mi sobrina, la hija de Rubén. Tiene cuatro años.', 'Das ist meine Nichte, die Tochter von Rubén. Sie ist vier.'],
      [T, '¡Es muy guapa! Se parece a ti.', 'Sie ist sehr hübsch! Sie sieht dir ähnlich.'],
      ['A', '¿Tú crees? ¡Gracias!', 'Meinst du? Danke!'],
    ],
    keyPhrases: [
      ['Se parece a ti.', 'Sie/Er sieht dir ähnlich.'],
      ['el sobrino / la sobrina', 'der Neffe / die Nichte'],
    ],
  },
  {
    id: 'c-tiempo-charla',
    level: 'A1',
    title: 'Smalltalk übers Wetter',
    emoji: '🌦️',
    setting: 'Du wartest mit einer älteren Dame an der Bushaltestelle.',
    roles: { S: 'Señora', [T]: 'Du' },
    you: T,
    lines: [
      ['S', '¡Qué calor hace hoy!', 'Was für eine Hitze heute!'],
      [T, 'Sí, es horrible. ¿Siempre hace tanto calor en junio?', 'Ja, schrecklich. Ist es im Juni immer so heiß?'],
      ['S', 'Normalmente no tanto. Este año es especial.', 'Normalerweise nicht so sehr. Dieses Jahr ist besonders.'],
      [T, 'En Alemania ahora llueve mucho.', 'In Deutschland regnet es jetzt viel.'],
      ['S', '¡Pues aquí no llueve nunca! ¿Viene el autobús?', 'Na, hier regnet es nie! Kommt der Bus?'],
      [T, 'Sí, ya viene. ¡Por fin!', 'Ja, er kommt schon. Endlich!'],
    ],
  },
];
