import type { PhraseTuple } from './types';

/** "Frase del día": natural everyday sayings and expressions, one per day. */
export const DAILY_PHRASES: readonly (readonly [es: string, de: string, explain: string])[] = [
  ['¡Qué guay!', 'Wie cool!', 'Sehr typisch in Spanien. In Mexiko sagt man „¡Qué padre!“, in Kolumbien „¡Qué chévere!“.'],
  ['No pasa nada.', 'Macht nichts / kein Problem.', 'Die perfekte Antwort, wenn sich jemand entschuldigt.'],
  ['¡Vale!', 'Okay!', 'Das meistgehörte Wort in Spanien.'],
  ['¿Qué tal?', 'Wie geht’s?', 'Kurz und locker – passt fast immer.'],
  ['Poco a poco.', 'Schritt für Schritt.', 'Auch als Motto fürs Spanischlernen: Poco a poco se va lejos.'],
  ['¡Qué pena!', 'Wie schade!', 'Wenn etwas nicht klappt.'],
  ['Me da igual.', 'Ist mir egal.', 'Neutral, nicht unhöflich.'],
  ['¡Ni idea!', 'Keine Ahnung!', 'Kurz für „No tengo ni idea“.'],
  ['¡Qué fuerte!', 'Krass!', 'Für überraschende oder schockierende Nachrichten.'],
  ['Estoy hecho polvo.', 'Ich bin fix und fertig.', 'Wörtlich: Ich bin zu Staub gemacht.'],
  ['¡Ánimo!', 'Kopf hoch! / Du schaffst das!', 'Um jemanden zu motivieren.'],
  ['¿En serio?', 'Echt? / Im Ernst?', 'Klassische Reaktion auf Neuigkeiten.'],
  ['¡Qué rico!', 'Wie lecker!', 'Für Essen. In Lateinamerika auch für angenehme Dinge allgemein.'],
  ['Más vale tarde que nunca.', 'Besser spät als nie.', 'Ein Sprichwort, das du sofort benutzen kannst.'],
  ['¡Ojalá!', 'Hoffentlich!', 'Kommt aus dem Arabischen: „so Gott will“.'],
  ['Tengo un montón de trabajo.', 'Ich habe einen Haufen Arbeit.', '„Un montón de“ = viel / eine Menge.'],
  ['¡Venga, vamos!', 'Komm, los geht’s!', 'Zum Aufbruch oder zur Motivation.'],
  ['A lo mejor.', 'Vielleicht.', 'Sehr umgangssprachlich und häufig.'],
  ['¡Menos mal!', 'Zum Glück!', 'Erleichterung nach einem Schreck.'],
  ['¿Te apetece?', 'Hast du Lust?', 'Typische Einladung in Spanien.'],
  ['Estoy flipando.', 'Ich fass es nicht.', 'Von „flipar“ – ausflippen, staunen.'],
  ['¡Qué va!', 'Ach was! / Überhaupt nicht!', 'Starke Verneinung.'],
  ['Me encanta.', 'Ich liebe es.', 'Stärker als „me gusta“.'],
  ['No me suena.', 'Sagt mir nichts.', 'Wenn dir ein Name oder Wort unbekannt vorkommt.'],
  ['Da igual.', 'Egal / Ist nicht so wichtig.', 'Beschwichtigend.'],
  ['¡Buen provecho!', 'Guten Appetit!', 'In Spanien auch: „¡Que aproveche!“.'],
  ['Cada loco con su tema.', 'Jedem Tierchen sein Pläsierchen.', 'Wörtlich: Jeder Verrückte mit seinem Thema.'],
  ['Estar en las nubes.', 'Mit den Gedanken woanders sein.', 'Wörtlich: in den Wolken sein.'],
  ['Echar una mano.', 'Helfen.', '¿Me echas una mano? = Hilfst du mir?'],
  ['¡Por fin!', 'Endlich!', 'Für Freitag, Urlaub, Feierabend …'],
  ['Ya veremos.', 'Mal sehen.', 'Wenn man sich noch nicht festlegen will.'],
  ['¡Qué rollo!', 'Wie nervig / langweilig!', 'Für langweilige oder lästige Dinge.'],
  ['No te preocupes.', 'Mach dir keine Sorgen.', 'Sehr häufig und beruhigend.'],
  ['Tengo ganas de verte.', 'Ich freue mich darauf, dich zu sehen.', '„Tener ganas de“ = Lust haben auf.'],
  ['En boca cerrada no entran moscas.', 'Reden ist Silber, Schweigen ist Gold.', 'Wörtlich: In einen geschlossenen Mund kommen keine Fliegen.'],
  ['¡Salud!', 'Prost! / Gesundheit!', 'Beim Anstoßen und nach dem Niesen.'],
  ['Más o menos.', 'So lala.', 'Wenn es weder gut noch schlecht geht.'],
  ['¡Qué suerte!', 'Was für ein Glück!', 'Auch ironisch möglich.'],
  ['Lo que tú digas.', 'Wie du meinst.', 'Kann freundlich oder genervt klingen – je nach Ton!'],
  ['Sin prisa, pero sin pausa.', 'Ohne Eile, aber ohne Pause.', 'Ein gutes Lernmotto.'],
];

/** Phrasebook categories with essential phrases for travel and emergencies. */
export const PHRASEBOOK: { id: string; title: string; emoji: string; phrases: readonly PhraseTuple[] }[] = [
  {
    id: 'basics',
    title: 'Das Wichtigste',
    emoji: '⭐',
    phrases: [
      ['Hola / Adiós', 'Hallo / Tschüss'],
      ['Por favor / Gracias', 'Bitte / Danke'],
      ['Perdón / Lo siento', 'Entschuldigung / Es tut mir leid'],
      ['No entiendo.', 'Ich verstehe nicht.'],
      ['¿Hablas inglés?', 'Sprichst du Englisch?'],
      ['¿Puedes repetirlo, por favor?', 'Kannst du das bitte wiederholen?'],
      ['¿Cómo se dice … en español?', 'Wie sagt man … auf Spanisch?'],
      ['Sí / No / Vale', 'Ja / Nein / Okay'],
    ],
  },
  {
    id: 'emergency',
    title: 'Notfall',
    emoji: '🆘',
    phrases: [
      ['¡Ayuda!', 'Hilfe!'],
      ['Llame a una ambulancia, por favor.', 'Rufen Sie bitte einen Krankenwagen.'],
      ['Necesito un médico.', 'Ich brauche einen Arzt.'],
      ['Me han robado la cartera.', 'Mir wurde der Geldbeutel gestohlen.'],
      ['¿Dónde está la comisaría?', 'Wo ist die Polizeiwache?'],
      ['Soy alérgico a …', 'Ich bin allergisch gegen …'],
      ['He perdido mi pasaporte.', 'Ich habe meinen Pass verloren.'],
      ['¡Fuego!', 'Feuer!'],
      ['Es una emergencia.', 'Es ist ein Notfall.'],
    ],
  },
  {
    id: 'restaurant',
    title: 'Essen & Trinken',
    emoji: '🍴',
    phrases: [
      ['Una mesa para dos, por favor.', 'Einen Tisch für zwei, bitte.'],
      ['¿Me trae la carta?', 'Bringen Sie mir die Karte?'],
      ['¿Qué me recomienda?', 'Was empfehlen Sie mir?'],
      ['Soy vegetariano/a.', 'Ich bin Vegetarier/in.'],
      ['Sin gluten, por favor.', 'Glutenfrei, bitte.'],
      ['¡Está buenísimo!', 'Es ist superlecker!'],
      ['La cuenta, por favor.', 'Die Rechnung, bitte.'],
      ['¿Se puede pagar con tarjeta?', 'Kann man mit Karte zahlen?'],
    ],
  },
  {
    id: 'transport',
    title: 'Unterwegs',
    emoji: '🚉',
    phrases: [
      ['¿Dónde está la parada de autobús?', 'Wo ist die Bushaltestelle?'],
      ['Un billete para …, por favor.', 'Eine Fahrkarte nach …, bitte.'],
      ['¿A qué hora sale el próximo tren?', 'Wann fährt der nächste Zug?'],
      ['¿Este autobús va al centro?', 'Fährt dieser Bus ins Zentrum?'],
      ['Lléveme a esta dirección, por favor.', 'Bringen Sie mich bitte zu dieser Adresse.'],
      ['¿Cuánto cuesta ir al aeropuerto?', 'Was kostet es zum Flughafen?'],
      ['Me he perdido.', 'Ich habe mich verlaufen.'],
    ],
  },
  {
    id: 'hotel',
    title: 'Unterkunft',
    emoji: '🛏️',
    phrases: [
      ['Tengo una reserva.', 'Ich habe eine Reservierung.'],
      ['¿Tienen habitaciones libres?', 'Haben Sie freie Zimmer?'],
      ['¿A qué hora es el desayuno?', 'Wann gibt es Frühstück?'],
      ['¿Cuál es la contraseña del wifi?', 'Wie ist das WLAN-Passwort?'],
      ['… no funciona.', '… funktioniert nicht.'],
      ['¿Puedo dejar aquí la maleta?', 'Kann ich hier den Koffer lassen?'],
    ],
  },
  {
    id: 'shopping',
    title: 'Einkaufen',
    emoji: '🛍️',
    phrases: [
      ['¿Cuánto cuesta?', 'Wie viel kostet das?'],
      ['Solo estoy mirando, gracias.', 'Ich schaue nur, danke.'],
      ['¿Lo tiene en otra talla / otro color?', 'Haben Sie es in einer anderen Größe / Farbe?'],
      ['¿Puedo probármelo?', 'Kann ich es anprobieren?'],
      ['Me lo llevo.', 'Ich nehme es.'],
      ['¿Me hace un descuento?', 'Geben Sie mir einen Rabatt?'],
    ],
  },
  {
    id: 'smalltalk',
    title: 'Smalltalk',
    emoji: '💬',
    phrases: [
      ['¿De dónde eres?', 'Woher kommst du?'],
      ['¿A qué te dedicas?', 'Was machst du beruflich?'],
      ['¿Cuánto tiempo llevas aquí?', 'Wie lange bist du schon hier?'],
      ['¡Qué bonito es esto!', 'Wie schön es hier ist!'],
      ['Estoy aprendiendo español.', 'Ich lerne Spanisch.'],
      ['¿Me das tu número?', 'Gibst du mir deine Nummer?'],
      ['¡Ha sido un placer!', 'Es war mir ein Vergnügen!'],
    ],
  },
];

/** False friends between German and Spanish. */
export const FALSE_FRIENDS: readonly (readonly [es: string, means: string, notMeans: string, insteadEs: string])[] = [
  ['embarazada', 'schwanger', 'peinlich berührt', 'avergonzado/a'],
  ['el éxito', 'der Erfolg', 'der Ausgang (Exit)', 'la salida'],
  ['constipado', 'erkältet', 'verstopft', 'estreñido'],
  ['la carta', 'der Brief / die Speisekarte', 'die (Spiel-/Bank-)Karte', 'la tarjeta'],
  ['el gimnasio', 'das Fitnessstudio', 'das Gymnasium (Schule)', 'el instituto'],
  ['la tasa', 'die Gebühr / Rate', 'die Tasse', 'la taza'],
  ['el bravo', 'wild / mutig', 'brav', 'bueno / obediente'],
  ['largo', 'lang', 'breit', 'ancho'],
  ['la fábrica', 'die Fabrik', 'das Fabrikat', 'la marca / el producto'],
  ['el mantel', 'die Tischdecke', 'der Mantel', 'el abrigo'],
  ['realizar', 'durchführen / verwirklichen', 'realisieren (begreifen)', 'darse cuenta'],
  ['el profesor', 'der Lehrer (auch Schule)', 'nur Uni-Professor', 'el catedrático (Uni)'],
  ['el ambiente', 'die Stimmung / Umwelt', 'das Ambiente (nur Deko)', 'la decoración'],
  ['la nota', 'die Note (Schule) / Notiz', 'die Banknote', 'el billete'],
  ['actual', 'aktuell / gegenwärtig', 'tatsächlich', 'real / verdadero'],
  ['el chef', 'der Küchenchef', 'der Chef (Boss)', 'el jefe'],
  ['la boda', 'die Hochzeit', 'der Boden', 'el suelo'],
  ['el rato', 'die Weile / der Moment', 'der Rat', 'el consejo'],
];

/** Short culture & language facts shown on the home screen and in the "Mehr" section. */
export const CULTURE: readonly (readonly [title: string, text: string])[] = [
  ['Zwei Küsschen', 'In Spanien begrüßt man Freunde und neue Bekannte mit zwei Küsschen (dos besos), in den meisten Ländern Lateinamerikas mit einem. Männer untereinander geben sich meist die Hand oder umarmen sich.'],
  ['Späte Essenszeiten', 'Mittagessen in Spanien: 14–15 Uhr. Abendessen: 21–22 Uhr. Restaurants öffnen abends oft erst um 20:30 Uhr.'],
  ['Tú oder usted?', 'In Spanien duzt man sich sehr schnell, sogar Fremde im Geschäft. In Lateinamerika ist „usted“ verbreiteter – in Kolumbien sagen manche sogar zu Freunden und Familie „usted“.'],
  ['Vosotros vs. ustedes', '„Vosotros“ (ihr) gibt es nur in Spanien. In ganz Lateinamerika sagt man „ustedes“ – für Freunde und Fremde.'],
  ['El voseo', 'In Argentinien, Uruguay, Paraguay und Teilen Mittelamerikas sagt man „vos“ statt „tú“: vos tenés, vos sos, vos podés.'],
  ['Die Siesta', 'Nicht jeder schläft mittags! Aber viele kleine Geschäfte schließen von ca. 14 bis 17 Uhr, besonders in kleineren Städten.'],
  ['Tapas', 'In manchen Städten (z. B. Granada, León) bekommt man zu jedem Getränk eine Tapa gratis dazu.'],
  ['Aussprache: c/z', 'In den meisten Teilen Spaniens spricht man „z“ und „ce/ci“ wie das englische „th“. In Lateinamerika, den Kanaren und Teilen Andalusiens wie „s“ (seseo).'],
  ['21 Länder', 'Spanisch ist in 21 Ländern Amtssprache und wird von über 500 Millionen Menschen als Muttersprache gesprochen – nach Chinesisch die zweitgrößte Muttersprache der Welt.'],
  ['Día de Muertos', 'In Mexiko feiert man am 1. und 2. November den Tag der Toten – ein buntes Fest mit Altären, Ringelblumen und Zuckerschädeln, um die Verstorbenen zu ehren.'],
  ['Las Fallas', 'In Valencia werden jedes Jahr im März riesige Figuren aus Pappmaché aufgestellt und in der Nacht des 19. März verbrannt.'],
  ['Pünktlichkeit', 'Bei privaten Verabredungen ist man oft 10–20 Minuten „zu spät“ – das ist normal. Bei beruflichen Terminen wird Pünktlichkeit aber erwartet.'],
  ['Spanische Nachnamen', 'Spanier haben zwei Nachnamen: den ersten des Vaters und den ersten der Mutter. Frauen behalten ihre Namen bei der Heirat.'],
  ['Ahorita', 'In Mexiko bedeutet „ahorita“ wörtlich „gleich“ – kann aber auch „in ein paar Stunden“ oder „nie“ heißen. 😉'],
  ['Mate', 'In Argentinien, Uruguay und Paraguay trinkt man Mate-Tee aus einem Gefäß mit Metallstrohhalm (bombilla) – und er wird in der Gruppe geteilt.'],
  ['Los Reyes Magos', 'In Spanien bringen die Heiligen Drei Könige am 6. Januar die Geschenke. Am Vorabend gibt es große Umzüge (cabalgatas).'],
];
