import type { VerbDef } from '../lib/conjugate';

/** The most useful Spanish verbs, roughly ordered by frequency. */
export const VERBS: VerbDef[] = [
  {
    inf: 'ser',
    de: 'sein (Wesen, Herkunft)',
    level: 'A1',
    part: 'sido',
    ger: 'siendo',
    impTu: 'sé',
    over: {
      presente: ['soy', 'eres', 'es', 'somos', 'sois', 'son'],
      indefinido: ['fui', 'fuiste', 'fue', 'fuimos', 'fuisteis', 'fueron'],
      imperfecto: ['era', 'eras', 'era', 'éramos', 'erais', 'eran'],
      subjuntivo: ['sea', 'seas', 'sea', 'seamos', 'seáis', 'sean'],
      imperativo: ['—', 'sé', 'sea', 'seamos', 'sed', 'sean'],
    },
  },
  {
    inf: 'estar',
    de: 'sein (Zustand, Ort)',
    level: 'A1',
    pret: 'estuv',
    over: {
      presente: ['estoy', 'estás', 'está', 'estamos', 'estáis', 'están'],
      subjuntivo: ['esté', 'estés', 'esté', 'estemos', 'estéis', 'estén'],
      imperativo: ['—', 'está', 'esté', 'estemos', 'estad', 'estén'],
    },
  },
  {
    inf: 'tener',
    de: 'haben',
    level: 'A1',
    stem: 'ie',
    yo: 'tengo',
    pret: 'tuv',
    fut: 'tendr',
    impTu: 'ten',
  },
  {
    inf: 'hacer',
    de: 'machen, tun',
    level: 'A1',
    yo: 'hago',
    pret: 'hic',
    fut: 'har',
    part: 'hecho',
    impTu: 'haz',
  },
  {
    inf: 'ir',
    de: 'gehen, fahren',
    level: 'A1',
    ger: 'yendo',
    impTu: 've',
    over: {
      presente: ['voy', 'vas', 'va', 'vamos', 'vais', 'van'],
      indefinido: ['fui', 'fuiste', 'fue', 'fuimos', 'fuisteis', 'fueron'],
      imperfecto: ['iba', 'ibas', 'iba', 'íbamos', 'ibais', 'iban'],
      subjuntivo: ['vaya', 'vayas', 'vaya', 'vayamos', 'vayáis', 'vayan'],
      imperativo: ['—', 've', 'vaya', 'vamos', 'id', 'vayan'],
    },
  },
  {
    inf: 'poder',
    de: 'können',
    level: 'A1',
    stem: 'ue',
    pret: 'pud',
    fut: 'podr',
    ger: 'pudiendo',
  },
  {
    inf: 'querer',
    de: 'wollen, lieben',
    level: 'A1',
    stem: 'ie',
    pret: 'quis',
    fut: 'querr',
  },
  {
    inf: 'decir',
    de: 'sagen',
    level: 'A1',
    stem: 'i',
    yo: 'digo',
    pret: 'dij',
    fut: 'dir',
    part: 'dicho',
    ger: 'diciendo',
    impTu: 'di',
  },
  {
    inf: 'haber',
    de: 'haben (Hilfsverb), es gibt (hay)',
    level: 'A2',
    pret: 'hub',
    fut: 'habr',
    over: {
      presente: ['he', 'has', 'ha / hay', 'hemos', 'habéis', 'han'],
      subjuntivo: ['haya', 'hayas', 'haya', 'hayamos', 'hayáis', 'hayan'],
      imperativo: ['—', '—', '—', '—', '—', '—'],
    },
  },
  {
    inf: 'saber',
    de: 'wissen, können (gelernt)',
    level: 'A1',
    yo: 'sé',
    pret: 'sup',
    fut: 'sabr',
    over: {
      subjuntivo: ['sepa', 'sepas', 'sepa', 'sepamos', 'sepáis', 'sepan'],
    },
  },
  { inf: 'hablar', de: 'sprechen', level: 'A1' },
  { inf: 'comer', de: 'essen', level: 'A1' },
  { inf: 'vivir', de: 'leben, wohnen', level: 'A1' },
  {
    inf: 'ver',
    de: 'sehen',
    level: 'A1',
    yo: 'veo',
    part: 'visto',
    over: {
      presente: ['veo', 'ves', 've', 'vemos', 'veis', 'ven'],
      indefinido: ['vi', 'viste', 'vio', 'vimos', 'visteis', 'vieron'],
      imperfecto: ['veía', 'veías', 'veía', 'veíamos', 'veíais', 'veían'],
    },
  },
  {
    inf: 'dar',
    de: 'geben',
    level: 'A1',
    over: {
      presente: ['doy', 'das', 'da', 'damos', 'dais', 'dan'],
      indefinido: ['di', 'diste', 'dio', 'dimos', 'disteis', 'dieron'],
      subjuntivo: ['dé', 'des', 'dé', 'demos', 'deis', 'den'],
      imperativo: ['—', 'da', 'dé', 'demos', 'dad', 'den'],
    },
  },
  {
    inf: 'venir',
    de: 'kommen',
    level: 'A1',
    stem: 'ie',
    yo: 'vengo',
    pret: 'vin',
    fut: 'vendr',
    ger: 'viniendo',
    impTu: 'ven',
  },
  {
    inf: 'poner',
    de: 'legen, stellen, setzen',
    level: 'A2',
    yo: 'pongo',
    pret: 'pus',
    fut: 'pondr',
    part: 'puesto',
    impTu: 'pon',
  },
  {
    inf: 'salir',
    de: 'ausgehen, hinausgehen',
    level: 'A1',
    yo: 'salgo',
    fut: 'saldr',
    impTu: 'sal',
  },
  { inf: 'llegar', de: 'ankommen', level: 'A1' },
  { inf: 'pasar', de: 'passieren, verbringen', level: 'A1' },
  { inf: 'deber', de: 'müssen, sollen', level: 'A2' },
  {
    inf: 'conocer',
    de: 'kennen, kennenlernen',
    level: 'A1',
    yo: 'conozco',
  },
  { inf: 'llevar', de: 'tragen, mitnehmen', level: 'A1' },
  { inf: 'dejar', de: 'lassen, verlassen', level: 'A2' },
  { inf: 'seguir', de: 'weitermachen, folgen', level: 'A2', stem: 'i' },
  { inf: 'encontrar', de: 'finden', level: 'A1', stem: 'ue' },
  { inf: 'llamar', de: 'rufen, anrufen', level: 'A1' },
  { inf: 'llamarse', de: 'heißen', level: 'A1' },
  { inf: 'pensar', de: 'denken', level: 'A1', stem: 'ie' },
  { inf: 'tomar', de: 'nehmen, trinken', level: 'A1' },
  { inf: 'trabajar', de: 'arbeiten', level: 'A1' },
  { inf: 'necesitar', de: 'brauchen', level: 'A1' },
  { inf: 'creer', de: 'glauben', level: 'A2' },
  { inf: 'leer', de: 'lesen', level: 'A1' },
  { inf: 'escribir', de: 'schreiben', level: 'A1', part: 'escrito' },
  { inf: 'abrir', de: 'öffnen', level: 'A2', part: 'abierto' },
  { inf: 'volver', de: 'zurückkommen', level: 'A1', stem: 'ue', part: 'vuelto' },
  { inf: 'dormir', de: 'schlafen', level: 'A1', stem: 'ue' },
  { inf: 'pedir', de: 'bestellen, bitten um', level: 'A1', stem: 'i' },
  { inf: 'empezar', de: 'anfangen', level: 'A2', stem: 'ie' },
  { inf: 'jugar', de: 'spielen', level: 'A1', stem: 'u-ue' },
  { inf: 'preferir', de: 'bevorzugen', level: 'A2', stem: 'ie' },
  { inf: 'sentir', de: 'fühlen, bedauern', level: 'A2', stem: 'ie' },
  { inf: 'sentirse', de: 'sich fühlen', level: 'A2', stem: 'ie' },
  { inf: 'entender', de: 'verstehen', level: 'A1', stem: 'ie' },
  { inf: 'buscar', de: 'suchen', level: 'A1' },
  { inf: 'comprar', de: 'kaufen', level: 'A1' },
  { inf: 'pagar', de: 'bezahlen', level: 'A1' },
  { inf: 'estudiar', de: 'lernen, studieren', level: 'A1' },
  { inf: 'aprender', de: 'lernen', level: 'A1' },
  { inf: 'beber', de: 'trinken', level: 'A1' },
  { inf: 'gustar', de: 'gefallen', level: 'A1' },
  { inf: 'levantarse', de: 'aufstehen', level: 'A1' },
  { inf: 'acostarse', de: 'ins Bett gehen', level: 'A2', stem: 'ue' },
  { inf: 'ducharse', de: 'duschen', level: 'A1' },
  { inf: 'vestirse', de: 'sich anziehen', level: 'A2', stem: 'i' },
  {
    inf: 'traer',
    de: 'bringen, mitbringen',
    level: 'A2',
    yo: 'traigo',
    pret: 'traj',
    ger: 'trayendo',
  },
  {
    inf: 'oír',
    de: 'hören',
    level: 'A2',
    yo: 'oigo',
    over: {
      presente: ['oigo', 'oyes', 'oye', 'oímos', 'oís', 'oyen'],
      imperativo: ['—', 'oye', 'oiga', 'oigamos', 'oíd', 'oigan'],
    },
  },
  { inf: 'esperar', de: 'warten, hoffen', level: 'A1' },
  { inf: 'ayudar', de: 'helfen', level: 'A1' },
  { inf: 'cerrar', de: 'schließen', level: 'A2', stem: 'ie' },
  { inf: 'perder', de: 'verlieren, verpassen', level: 'A2', stem: 'ie' },
  { inf: 'recordar', de: 'sich erinnern', level: 'A2', stem: 'ue' },
  { inf: 'conducir', de: 'fahren (Auto)', level: 'A2', yo: 'conduzco', pret: 'conduj' },
  { inf: 'construir', de: 'bauen', level: 'B1' },
  { inf: 'elegir', de: 'wählen', level: 'B1', stem: 'i' },
  { inf: 'morir', de: 'sterben', level: 'B1', stem: 'ue', part: 'muerto' },
  { inf: 'romper', de: 'kaputt machen, brechen', level: 'B1', part: 'roto' },
  { inf: 'devolver', de: 'zurückgeben', level: 'B1', stem: 'ue', part: 'devuelto' },
  { inf: 'olvidar', de: 'vergessen', level: 'A2' },
  { inf: 'viajar', de: 'reisen', level: 'A1' },
  { inf: 'cocinar', de: 'kochen', level: 'A1' },
  { inf: 'cambiar', de: 'ändern, wechseln', level: 'A2' },
  { inf: 'quedar', de: 'sich verabreden, übrig bleiben', level: 'A2' },
  { inf: 'quedarse', de: 'bleiben', level: 'A2' },
  { inf: 'mantener', de: 'beibehalten, unterhalten', level: 'B1', stem: 'ie', yo: 'mantengo', pret: 'mantuv', fut: 'mantendr', impTu: 'mantén' },
  { inf: 'caer', de: 'fallen', level: 'B1', yo: 'caigo' },
  { inf: 'divertirse', de: 'sich amüsieren', level: 'A2', stem: 'ie' },
];
