import type { LevelSource } from '../types';

export const A0: LevelSource = {
  id: 'A0',
  title: 'Primeros pasos',
  subtitle: 'Start bei null – deine ersten Wörter und Sätze',
  units: [
    {
      id: 'a0-u1',
      title: 'Hallo!',
      lessons: [
        {
          id: 'a0-hola',
          title: 'Hola y adiós',
          goal: 'Menschen begrüßen und dich verabschieden',
          emoji: '👋',
          words: [
            ['hola', 'hallo'],
            ['adiós', 'tschüss / auf Wiedersehen'],
            ['buenos días', 'guten Morgen / guten Tag'],
            ['buenas tardes', 'guten Tag / guten Nachmittag'],
            ['buenas noches', 'guten Abend / gute Nacht'],
            ['hasta luego', 'bis später'],
            ['hasta mañana', 'bis morgen'],
            ['chao', 'tschau'],
            ['nos vemos', 'wir sehen uns'],
            ['buenas', 'hallo (locker)'],
            ['sí', 'ja'],
            ['no', 'nein'],
          ],
          phrases: [
            ['¡Hola! ¿Qué tal?', 'Hallo! Wie geht’s?'],
            ['Buenos días, señora.', 'Guten Morgen, (meine Dame).'],
            ['Hasta luego, Ana.', 'Bis später, Ana.'],
            ['Buenas noches, hasta mañana.', 'Gute Nacht, bis morgen.'],
            ['Adiós, nos vemos.', 'Tschüss, wir sehen uns.'],
          ],
          dialogue: [
            ['Ana', '¡Hola, Pablo!', 'Hallo, Pablo!'],
            ['Pablo', '¡Hola, Ana! ¿Qué tal?', 'Hallo, Ana! Wie geht’s?'],
            ['Ana', 'Bien. ¿Y tú?', 'Gut. Und dir?'],
            ['Pablo', 'Muy bien. ¡Hasta luego!', 'Sehr gut. Bis später!'],
            ['Ana', '¡Chao!', 'Tschau!'],
          ],
          tip: '„Buenos días“ sagt man bis zum Mittagessen (ca. 14 Uhr), danach „buenas tardes“. Ganz locker grüßt man einfach mit „¡Buenas!“. Das „h“ in „hola“ ist immer stumm: [ola].',
        },
        {
          id: 'a0-que-tal',
          title: '¿Qué tal?',
          goal: 'Fragen und sagen, wie es dir geht',
          emoji: '🙂',
          words: [
            ['¿qué tal?', 'wie geht’s?'],
            ['¿cómo estás?', 'wie geht es dir?'],
            ['bien', 'gut'],
            ['muy bien', 'sehr gut'],
            ['mal', 'schlecht'],
            ['regular', 'so lala'],
            ['más o menos', 'mehr oder weniger'],
            ['genial', 'super / genial'],
            ['cansado', 'müde (m)'],
            ['cansada', 'müde (f)'],
            ['¿y tú?', 'und du?'],
            ['también', 'auch'],
            ['gracias', 'danke'],
          ],
          phrases: [
            ['¿Cómo estás?', 'Wie geht es dir?'],
            ['Estoy bien, gracias.', 'Mir geht es gut, danke.'],
            ['Estoy muy cansado.', 'Ich bin sehr müde.'],
            ['Más o menos. ¿Y tú?', 'Mehr oder weniger. Und du?'],
            ['Yo también estoy bien.', 'Mir geht es auch gut.'],
            ['¡Genial, gracias!', 'Super, danke!'],
          ],
          dialogue: [
            ['Lucía', 'Hola, Marco. ¿Cómo estás?', 'Hallo, Marco. Wie geht es dir?'],
            ['Marco', 'Regular… estoy cansado. ¿Y tú?', 'So lala… ich bin müde. Und du?'],
            ['Lucía', 'Yo estoy genial.', 'Mir geht es super.'],
            ['Marco', '¡Qué bien!', 'Wie schön!'],
          ],
          tip: 'Im Spanischen ändern viele Adjektive ihre Endung: ein Mann ist „cansado“, eine Frau „cansada“. -o = männlich, -a = weiblich.',
        },
        {
          id: 'a0-me-llamo',
          title: 'Me llamo…',
          goal: 'Dich vorstellen und nach dem Namen fragen',
          emoji: '🪪',
          words: [
            ['me llamo', 'ich heiße'],
            ['¿cómo te llamas?', 'wie heißt du?'],
            ['yo', 'ich'],
            ['tú', 'du'],
            ['soy', 'ich bin'],
            ['eres', 'du bist'],
            ['mucho gusto', 'freut mich'],
            ['encantado', 'sehr erfreut (m)'],
            ['encantada', 'sehr erfreut (f)'],
            ['igualmente', 'gleichfalls'],
            ['el nombre', 'der Name'],
            ['y', 'und'],
          ],
          phrases: [
            ['Me llamo Laura.', 'Ich heiße Laura.'],
            ['¿Cómo te llamas?', 'Wie heißt du?'],
            ['Soy Tom. Mucho gusto.', 'Ich bin Tom. Freut mich.'],
            ['Encantada. Igualmente.', 'Sehr erfreut. Gleichfalls.'],
            ['¿Y tú? ¿Cómo te llamas?', 'Und du? Wie heißt du?'],
          ],
          dialogue: [
            ['Tom', 'Hola, me llamo Tom. ¿Cómo te llamas?', 'Hallo, ich heiße Tom. Wie heißt du?'],
            ['Laura', 'Soy Laura. Mucho gusto.', 'Ich bin Laura. Freut mich.'],
            ['Tom', 'Igualmente.', 'Gleichfalls.'],
          ],
          tip: 'In Spanien gibt man sich zur Begrüßung oft zwei Küsschen (dos besos) – erst rechte, dann linke Wange. In Lateinamerika meist nur eins.',
        },
        {
          id: 'a0-cortesia',
          title: 'Por favor y gracias',
          goal: 'Höflich bitten, danken und dich entschuldigen',
          emoji: '🙏',
          words: [
            ['por favor', 'bitte'],
            ['gracias', 'danke'],
            ['muchas gracias', 'vielen Dank'],
            ['de nada', 'gern geschehen'],
            ['perdón', 'Entschuldigung'],
            ['lo siento', 'es tut mir leid'],
            ['disculpe', 'entschuldigen Sie'],
            ['vale', 'okay', 'LatAm: está bien / dale / órale (MX)'],
            ['claro', 'klar'],
            ['no pasa nada', 'kein Problem / macht nichts'],
            ['con permiso', 'mit Verlaub / darf ich mal vorbei'],
          ],
          phrases: [
            ['Un café, por favor.', 'Einen Kaffee, bitte.'],
            ['Muchas gracias. – De nada.', 'Vielen Dank. – Gern geschehen.'],
            ['Perdón, lo siento.', 'Entschuldigung, es tut mir leid.'],
            ['No pasa nada.', 'Macht nichts.'],
            ['Disculpe, ¿el baño?', 'Entschuldigen Sie, die Toilette?'],
            ['Vale, claro.', 'Okay, klar.'],
          ],
          tip: '„Vale“ ist das typischste Wort in Spanien – du hörst es ständig. In Lateinamerika sagt man eher „está bien“, „dale“ (Argentinien, Kolumbien) oder „órale“ (Mexiko).',
        },
      ],
    },
    {
      id: 'a0-u2',
      title: 'Zahlen & Farben',
      lessons: [
        {
          id: 'a0-numeros-1',
          title: 'Números 0–10',
          goal: 'Von null bis zehn zählen',
          emoji: '🔢',
          words: [
            ['cero', 'null'],
            ['uno', 'eins'],
            ['dos', 'zwei'],
            ['tres', 'drei'],
            ['cuatro', 'vier'],
            ['cinco', 'fünf'],
            ['seis', 'sechs'],
            ['siete', 'sieben'],
            ['ocho', 'acht'],
            ['nueve', 'neun'],
            ['diez', 'zehn'],
            ['el número', 'die Zahl / die Nummer'],
          ],
          phrases: [
            ['Uno, dos, tres.', 'Eins, zwei, drei.'],
            ['Dos cafés, por favor.', 'Zwei Kaffee, bitte.'],
            ['Tengo cinco euros.', 'Ich habe fünf Euro.'],
            ['Mi número es el siete.', 'Meine Nummer ist die Sieben.'],
          ],
          tip: 'Aussprache: „z“ und „c“ vor e/i spricht man in Spanien wie das englische „th“ (diez ≈ „dieth“), in Lateinamerika wie ein „s“ (dies).',
        },
        {
          id: 'a0-numeros-2',
          title: 'Números 11–100',
          goal: 'Größere Zahlen, Preise und Alter verstehen',
          emoji: '💯',
          words: [
            ['once', 'elf'],
            ['doce', 'zwölf'],
            ['trece', 'dreizehn'],
            ['quince', 'fünfzehn'],
            ['dieciséis', 'sechzehn'],
            ['veinte', 'zwanzig'],
            ['veintiuno', 'einundzwanzig'],
            ['treinta', 'dreißig'],
            ['treinta y cinco', 'fünfunddreißig'],
            ['cuarenta', 'vierzig'],
            ['cincuenta', 'fünfzig'],
            ['sesenta', 'sechzig'],
            ['setenta', 'siebzig'],
            ['ochenta', 'achtzig'],
            ['noventa', 'neunzig'],
            ['cien', 'hundert'],
            ['¿cuánto cuesta?', 'wie viel kostet es?'],
            ['¿cuántos años tienes?', 'wie alt bist du?'],
          ],
          phrases: [
            ['Tengo treinta años.', 'Ich bin dreißig Jahre alt.'],
            ['¿Cuánto cuesta? – Quince euros.', 'Wie viel kostet es? – Fünfzehn Euro.'],
            ['Son cuarenta y dos euros.', 'Das macht zweiundvierzig Euro.'],
            ['¿Cuántos años tienes?', 'Wie alt bist du?'],
          ],
          tip: 'Ab 31 wird mit „y“ verbunden: treinta y uno, cuarenta y dos … Von 16 bis 29 schreibt man es als ein Wort: dieciséis, veintidós. Achtung: Alter „hat“ man auf Spanisch: tengo 30 años.',
        },
        {
          id: 'a0-colores',
          title: 'Los colores',
          goal: 'Farben benennen und Dinge beschreiben',
          emoji: '🎨',
          words: [
            ['rojo', 'rot'],
            ['azul', 'blau'],
            ['verde', 'grün'],
            ['amarillo', 'gelb'],
            ['negro', 'schwarz'],
            ['blanco', 'weiß'],
            ['gris', 'grau'],
            ['rosa', 'rosa'],
            ['naranja', 'orange'],
            ['marrón', 'braun', 'LatAm oft: café'],
            ['morado', 'lila'],
            ['el color', 'die Farbe'],
            ['¿de qué color es?', 'welche Farbe hat es?'],
            ['favorito', 'Lieblings-'],
          ],
          phrases: [
            ['Mi color favorito es el azul.', 'Meine Lieblingsfarbe ist Blau.'],
            ['El coche es rojo.', 'Das Auto ist rot.'],
            ['La casa es blanca.', 'Das Haus ist weiß.'],
            ['¿De qué color es?', 'Welche Farbe hat es?'],
          ],
          tip: 'Farben stehen meistens nach dem Nomen und passen sich an: el coche rojo, la casa roja. Farben auf -e (verde) oder Konsonant (azul) ändern sich nicht.',
        },
      ],
    },
    {
      id: 'a0-u3',
      title: 'Erste Sätze',
      lessons: [
        {
          id: 'a0-no-entiendo',
          title: 'No entiendo',
          goal: 'Sagen, dass du etwas nicht verstehst, und nachfragen',
          emoji: '🤔',
          words: [
            ['no entiendo', 'ich verstehe nicht'],
            ['no sé', 'ich weiß nicht'],
            ['¿puedes repetir?', 'kannst du das wiederholen?'],
            ['más despacio', 'langsamer'],
            ['¿qué significa…?', 'was bedeutet …?'],
            ['¿cómo se dice…?', 'wie sagt man …?'],
            ['hablo un poco de español', 'ich spreche ein bisschen Spanisch'],
            ['¿hablas inglés?', 'sprichst du Englisch?'],
            ['alemán', 'Deutsch (Sprache)'],
            ['español', 'Spanisch'],
            ['un poco', 'ein bisschen'],
            ['otra vez', 'noch einmal'],
          ],
          phrases: [
            ['Perdón, no entiendo.', 'Entschuldigung, ich verstehe nicht.'],
            ['¿Puedes hablar más despacio, por favor?', 'Kannst du bitte langsamer sprechen?'],
            ['¿Cómo se dice „Danke“ en español?', 'Wie sagt man „Danke“ auf Spanisch?'],
            ['Hablo un poco de español.', 'Ich spreche ein bisschen Spanisch.'],
            ['¿Qué significa „vale“?', 'Was bedeutet „vale“?'],
            ['Otra vez, por favor.', 'Noch einmal, bitte.'],
          ],
          dialogue: [
            ['Camarero', '¿Qué te pongo?', 'Was darf’s sein?'],
            ['Tú', 'Perdón, no entiendo. ¿Puedes repetir, por favor?', 'Entschuldigung, ich verstehe nicht. Kannst du das bitte wiederholen?'],
            ['Camarero', '¿Qué quieres tomar?', 'Was möchtest du trinken?'],
            ['Tú', '¡Ah, vale! Un agua, por favor.', 'Ah, okay! Ein Wasser, bitte.'],
          ],
          tip: 'Diese Sätze sind deine Rettungsanker! Spanischsprachige sind meist sehr geduldig, wenn du zeigst, dass du es versuchst.',
        },
        {
          id: 'a0-preguntas',
          title: 'Preguntas básicas',
          goal: 'Die wichtigsten Fragewörter benutzen',
          emoji: '❓',
          words: [
            ['¿qué?', 'was?'],
            ['¿quién?', 'wer?'],
            ['¿dónde?', 'wo?'],
            ['¿cuándo?', 'wann?'],
            ['¿cómo?', 'wie?'],
            ['¿por qué?', 'warum?'],
            ['porque', 'weil'],
            ['¿cuánto?', 'wie viel?'],
            ['¿cuál?', 'welche(r/s)?'],
            ['¿adónde?', 'wohin?'],
            ['¿de dónde?', 'woher?'],
          ],
          phrases: [
            ['¿Dónde está el baño?', 'Wo ist die Toilette?'],
            ['¿Quién es?', 'Wer ist das?'],
            ['¿Qué es esto?', 'Was ist das?'],
            ['¿Por qué no?', 'Warum nicht?'],
            ['¿De dónde eres?', 'Woher kommst du?'],
            ['¿Cuándo es la fiesta?', 'Wann ist die Party?'],
          ],
          tip: 'Fragen beginnen mit einem umgedrehten Fragezeichen: ¿…? Fragewörter tragen immer einen Akzent (¿qué?, ¿dónde?). Ohne Akzent heißt „que“ einfach „dass“ und „porque“ „weil“.',
        },
        {
          id: 'a0-cafe',
          title: 'En el café',
          goal: 'Im Café etwas bestellen und bezahlen',
          emoji: '☕',
          words: [
            ['un café', 'ein Kaffee'],
            ['un café con leche', 'ein Milchkaffee'],
            ['un cortado', 'ein Espresso mit etwas Milch'],
            ['un té', 'ein Tee'],
            ['un agua', 'ein Wasser'],
            ['un zumo de naranja', 'ein Orangensaft', 'LatAm: un jugo de naranja'],
            ['una cerveza', 'ein Bier'],
            ['un vaso de vino', 'ein Glas Wein'],
            ['un cruasán', 'ein Croissant'],
            ['una tostada', 'ein Toast'],
            ['quiero', 'ich möchte / ich will'],
            ['¿me pones…?', 'gibst du mir …? (Bestellung)'],
            ['la cuenta', 'die Rechnung'],
            ['para tomar aquí', 'zum hier Trinken'],
            ['para llevar', 'zum Mitnehmen'],
          ],
          phrases: [
            ['Un café con leche, por favor.', 'Einen Milchkaffee, bitte.'],
            ['¿Me pones un agua, por favor?', 'Bringst du mir ein Wasser, bitte?'],
            ['Quiero una tostada con tomate.', 'Ich möchte einen Toast mit Tomate.'],
            ['La cuenta, por favor.', 'Die Rechnung, bitte.'],
            ['¿Para tomar aquí o para llevar?', 'Zum hier Trinken oder zum Mitnehmen?'],
            ['¿Cuánto es?', 'Wie viel macht das?'],
          ],
          dialogue: [
            ['Camarera', '¡Buenos días! ¿Qué te pongo?', 'Guten Morgen! Was darf’s sein?'],
            ['Tú', 'Un café con leche y una tostada, por favor.', 'Einen Milchkaffee und einen Toast, bitte.'],
            ['Camarera', '¿Para tomar aquí o para llevar?', 'Zum hier Trinken oder zum Mitnehmen?'],
            ['Tú', 'Para tomar aquí.', 'Zum hier Trinken.'],
            ['Camarera', 'Muy bien. Son tres cincuenta.', 'Sehr gut. Das macht drei fünfzig.'],
            ['Tú', 'Aquí tienes. ¡Gracias!', 'Bitte schön. Danke!'],
          ],
          tip: 'In Spanien bestellt man ganz direkt: „¿Me pones un café?“ klingt nicht unhöflich, sondern natürlich. Ein „por favor“ macht es freundlich.',
        },
        {
          id: 'a0-cosas',
          title: 'Cosas a mi alrededor',
          goal: 'Alltägliche Dinge benennen und „el/la“ verwenden',
          emoji: '🎒',
          words: [
            ['el móvil', 'das Handy', 'LatAm: el celular'],
            ['la llave', 'der Schlüssel'],
            ['el libro', 'das Buch'],
            ['la mesa', 'der Tisch'],
            ['la silla', 'der Stuhl'],
            ['la puerta', 'die Tür'],
            ['la ventana', 'das Fenster'],
            ['el bolso', 'die Tasche', 'LatAm: la cartera / la bolsa'],
            ['la cartera', 'der Geldbeutel', 'LatAm: la billetera'],
            ['las gafas', 'die Brille', 'LatAm: los lentes / los anteojos'],
            ['el coche', 'das Auto', 'LatAm: el carro / el auto'],
            ['la casa', 'das Haus'],
            ['esto', 'das (hier)'],
            ['aquí', 'hier'],
            ['allí', 'dort'],
          ],
          phrases: [
            ['¿Dónde está mi móvil?', 'Wo ist mein Handy?'],
            ['Las llaves están en la mesa.', 'Die Schlüssel sind auf dem Tisch.'],
            ['¿Qué es esto? – Es un libro.', 'Was ist das? – Das ist ein Buch.'],
            ['Mi coche está allí.', 'Mein Auto ist dort.'],
            ['Abre la ventana, por favor.', 'Mach bitte das Fenster auf.'],
          ],
          grammar: 'articulos',
          tip: 'Jedes Nomen ist männlich (el) oder weiblich (la). Faustregel: -o ist meist männlich (el libro), -a meist weiblich (la mesa). Lerne Wörter immer mit Artikel!',
        },
      ],
    },
  ],
};
