import type { LevelSource } from '../types';

export const A1: LevelSource = {
  id: 'A1',
  title: 'Mi mundo',
  subtitle: 'Über dich sprechen und den Alltag meistern',
  units: [
    {
      id: 'a1-u1',
      title: 'Über mich',
      lessons: [
        {
          id: 'a1-origen',
          title: '¿De dónde eres?',
          goal: 'Sagen, woher du kommst und wo du wohnst',
          emoji: '🌍',
          words: [
            ['soy de…', 'ich komme aus …'],
            ['vivo en…', 'ich wohne in …'],
            ['Alemania', 'Deutschland'],
            ['alemán', 'deutsch / Deutscher'],
            ['alemana', 'deutsch / Deutsche'],
            ['Austria', 'Österreich'],
            ['Suiza', 'Schweiz'],
            ['España', 'Spanien'],
            ['español', 'spanisch / Spanier'],
            ['México', 'Mexiko'],
            ['mexicano', 'mexikanisch / Mexikaner'],
            ['Argentina', 'Argentinien'],
            ['Colombia', 'Kolumbien'],
            ['el país', 'das Land'],
            ['la ciudad', 'die Stadt'],
            ['el pueblo', 'das Dorf'],
            ['hablar', 'sprechen'],
            ['vivir', 'leben / wohnen'],
            ['el idioma', 'die Sprache'],
          ],
          phrases: [
            ['Soy de Alemania, de Múnich.', 'Ich komme aus Deutschland, aus München.'],
            ['Vivo en Berlín.', 'Ich wohne in Berlin.'],
            ['¿Dónde vives?', 'Wo wohnst du?'],
            ['Ella es española, de Sevilla.', 'Sie ist Spanierin, aus Sevilla.'],
            ['Hablo alemán e inglés.', 'Ich spreche Deutsch und Englisch.'],
            ['Vivo en un pueblo pequeño.', 'Ich wohne in einem kleinen Dorf.'],
          ],
          dialogue: [
            ['Sofía', '¿De dónde eres?', 'Woher kommst du?'],
            ['Tú', 'Soy de Alemania, de Hamburgo. ¿Y tú?', 'Ich komme aus Deutschland, aus Hamburg. Und du?'],
            ['Sofía', 'Yo soy mexicana, pero vivo en Madrid.', 'Ich bin Mexikanerin, aber ich wohne in Madrid.'],
            ['Tú', '¡Qué guay! ¿Te gusta Madrid?', 'Wie cool! Gefällt dir Madrid?'],
            ['Sofía', 'Sí, me encanta.', 'Ja, ich liebe es.'],
          ],
          grammar: 'presente-regular',
          tip: 'Länder schreibt man groß, Nationalitäten und Sprachen klein: Alemania, aber alemán. „Y“ wird vor einem i-Laut zu „e“: alemán e inglés.',
        },
        {
          id: 'a1-familia',
          title: 'La familia',
          goal: 'Deine Familie vorstellen',
          emoji: '👨‍👩‍👧',
          words: [
            ['la familia', 'die Familie'],
            ['la madre', 'die Mutter'],
            ['el padre', 'der Vater'],
            ['los padres', 'die Eltern'],
            ['el hermano', 'der Bruder'],
            ['la hermana', 'die Schwester'],
            ['los hermanos', 'die Geschwister'],
            ['el hijo', 'der Sohn'],
            ['la hija', 'die Tochter'],
            ['el abuelo', 'der Großvater'],
            ['la abuela', 'die Großmutter'],
            ['el tío', 'der Onkel'],
            ['la tía', 'die Tante'],
            ['el primo', 'der Cousin'],
            ['la prima', 'die Cousine'],
            ['el marido', 'der Ehemann', 'LatAm oft: el esposo'],
            ['la mujer', 'die Frau / Ehefrau', 'LatAm oft: la esposa'],
            ['el novio', 'der Freund (Partner)'],
            ['la novia', 'die Freundin (Partnerin)'],
            ['mamá', 'Mama'],
            ['papá', 'Papa'],
            ['tener', 'haben'],
          ],
          phrases: [
            ['Tengo dos hermanos.', 'Ich habe zwei Geschwister.'],
            ['Mi madre se llama Elena.', 'Meine Mutter heißt Elena.'],
            ['¿Tienes hijos?', 'Hast du Kinder?'],
            ['No tengo hermanos, soy hijo único.', 'Ich habe keine Geschwister, ich bin Einzelkind.'],
            ['Mis abuelos viven en el campo.', 'Meine Großeltern leben auf dem Land.'],
            ['Mi novia es colombiana.', 'Meine Freundin ist Kolumbianerin.'],
          ],
          dialogue: [
            ['Carlos', '¿Tienes hermanos?', 'Hast du Geschwister?'],
            ['Tú', 'Sí, tengo una hermana. Se llama Mia.', 'Ja, ich habe eine Schwester. Sie heißt Mia.'],
            ['Carlos', '¿Y es mayor o menor?', 'Und ist sie älter oder jünger?'],
            ['Tú', 'Es menor. Tiene veinte años.', 'Sie ist jünger. Sie ist zwanzig.'],
          ],
          grammar: 'posesivos',
          tip: '„Los padres“ = die Eltern, „los hermanos“ = Geschwister (oder Brüder). Die männliche Mehrzahl steht für gemischte Gruppen.',
        },
        {
          id: 'a1-trabajo',
          title: '¿A qué te dedicas?',
          goal: 'Über deinen Beruf sprechen',
          emoji: '💼',
          words: [
            ['trabajar', 'arbeiten'],
            ['el trabajo', 'die Arbeit / der Job'],
            ['¿a qué te dedicas?', 'was machst du beruflich?'],
            ['el profesor', 'der Lehrer'],
            ['la profesora', 'die Lehrerin'],
            ['el médico', 'der Arzt'],
            ['la médica', 'die Ärztin'],
            ['el enfermero', 'der Krankenpfleger'],
            ['el ingeniero', 'der Ingenieur'],
            ['el camarero', 'der Kellner', 'LatAm: el mesero'],
            ['el abogado', 'der Anwalt'],
            ['el estudiante', 'der Student'],
            ['la estudiante', 'die Studentin'],
            ['el jefe', 'der Chef'],
            ['la oficina', 'das Büro'],
            ['la empresa', 'die Firma'],
            ['estudiar', 'studieren / lernen'],
            ['jubilado', 'in Rente'],
            ['en paro', 'arbeitslos', 'LatAm: desempleado'],
          ],
          phrases: [
            ['¿A qué te dedicas?', 'Was machst du beruflich?'],
            ['Soy profesora de matemáticas.', 'Ich bin Mathelehrerin.'],
            ['Trabajo en una empresa de software.', 'Ich arbeite in einer Softwarefirma.'],
            ['Estudio medicina en la universidad.', 'Ich studiere Medizin an der Uni.'],
            ['Mi padre está jubilado.', 'Mein Vater ist in Rente.'],
            ['Trabajo desde casa.', 'Ich arbeite von zu Hause.'],
          ],
          tip: 'Beim Beruf fällt der Artikel weg: „Soy médico“ (nicht „soy un médico“). Viele Berufe haben eine weibliche Form auf -a.',
        },
        {
          id: 'a1-describir',
          title: '¿Cómo es?',
          goal: 'Menschen beschreiben – Aussehen und Charakter',
          emoji: '🧑',
          words: [
            ['alto', 'groß'],
            ['bajo', 'klein'],
            ['delgado', 'schlank'],
            ['guapo', 'hübsch / gutaussehend', 'LatAm auch: lindo'],
            ['feo', 'hässlich'],
            ['joven', 'jung'],
            ['mayor', 'älter / alt'],
            ['simpático', 'sympathisch / nett'],
            ['antipático', 'unsympathisch'],
            ['divertido', 'lustig'],
            ['aburrido', 'langweilig'],
            ['inteligente', 'intelligent'],
            ['tímido', 'schüchtern'],
            ['amable', 'freundlich'],
            ['el pelo', 'die Haare'],
            ['los ojos', 'die Augen'],
            ['moreno', 'dunkelhaarig / braungebrannt'],
            ['rubio', 'blond'],
            ['ser', 'sein'],
          ],
          phrases: [
            ['Mi hermano es alto y moreno.', 'Mein Bruder ist groß und dunkelhaarig.'],
            ['Ella es muy simpática.', 'Sie ist sehr nett.'],
            ['Tiene los ojos azules.', 'Er/Sie hat blaue Augen.'],
            ['¿Cómo es tu novio?', 'Wie ist dein Freund so?'],
            ['Es un poco tímido, pero muy divertido.', 'Er ist ein bisschen schüchtern, aber sehr lustig.'],
          ],
          grammar: 'ser-estar',
          tip: 'Für Eigenschaften (wie jemand IST) benutzt man „ser“: Es simpático. Für Zustände (wie es jemandem GEHT) „estar“: Está cansado.',
        },
      ],
    },
    {
      id: 'a1-u2',
      title: 'Essen & Einkaufen',
      lessons: [
        {
          id: 'a1-comida',
          title: 'La comida',
          goal: 'Lebensmittel benennen und sagen, was du magst',
          emoji: '🥘',
          words: [
            ['el pan', 'das Brot'],
            ['el queso', 'der Käse'],
            ['el jamón', 'der Schinken'],
            ['el huevo', 'das Ei'],
            ['la carne', 'das Fleisch'],
            ['el pollo', 'das Hähnchen'],
            ['el pescado', 'der Fisch (als Essen)'],
            ['el arroz', 'der Reis'],
            ['la pasta', 'die Nudeln'],
            ['la verdura', 'das Gemüse'],
            ['la fruta', 'das Obst'],
            ['la manzana', 'der Apfel'],
            ['el plátano', 'die Banane', 'LatAm: la banana / el guineo'],
            ['la patata', 'die Kartoffel', 'LatAm: la papa'],
            ['el tomate', 'die Tomate'],
            ['la leche', 'die Milch'],
            ['el aceite de oliva', 'das Olivenöl'],
            ['me gusta', 'ich mag / mir gefällt'],
            ['me encanta', 'ich liebe (es)'],
            ['no me gusta nada', 'ich mag überhaupt nicht'],
            ['vegetariano', 'vegetarisch'],
          ],
          phrases: [
            ['Me gusta mucho el queso.', 'Ich mag Käse sehr.'],
            ['Me encantan las patatas fritas.', 'Ich liebe Pommes.'],
            ['No me gusta nada el pescado.', 'Ich mag Fisch überhaupt nicht.'],
            ['Soy vegetariana, no como carne.', 'Ich bin Vegetarierin, ich esse kein Fleisch.'],
            ['¿Te gusta la comida picante?', 'Magst du scharfes Essen?'],
            ['Desayuno pan con tomate.', 'Ich frühstücke Brot mit Tomate.'],
          ],
          grammar: 'gustar',
          tip: '„Gustar“ funktioniert umgekehrt: „Me gusta el queso“ heißt wörtlich „Mir gefällt der Käse“. Bei Mehrzahl: „Me gustan las fresas“.',
        },
        {
          id: 'a1-restaurante',
          title: 'En el restaurante',
          goal: 'Im Restaurant reservieren, bestellen und bezahlen',
          emoji: '🍽️',
          words: [
            ['la mesa para dos', 'ein Tisch für zwei'],
            ['la carta', 'die Speisekarte'],
            ['el menú del día', 'das Tagesmenü'],
            ['de primero', 'als Vorspeise'],
            ['de segundo', 'als Hauptgang'],
            ['de postre', 'als Nachtisch'],
            ['la bebida', 'das Getränk'],
            ['el plato', 'der Teller / das Gericht'],
            ['la ración', 'die Portion'],
            ['las tapas', 'die Tapas'],
            ['rico', 'lecker'],
            ['la propina', 'das Trinkgeld'],
            ['pedir', 'bestellen'],
            ['¿qué me recomienda?', 'was empfehlen Sie mir?'],
            ['para mí…', 'für mich …'],
            ['¿nos trae la cuenta?', 'bringen Sie uns die Rechnung?'],
            ['con tarjeta', 'mit Karte'],
            ['en efectivo', 'bar'],
          ],
          phrases: [
            ['Una mesa para dos, por favor.', 'Einen Tisch für zwei, bitte.'],
            ['¿Qué me recomienda?', 'Was empfehlen Sie mir?'],
            ['Para mí, de primero una ensalada.', 'Für mich als Vorspeise einen Salat.'],
            ['¡Está riquísimo!', 'Das ist superlecker!'],
            ['¿Nos trae la cuenta, por favor?', 'Bringen Sie uns bitte die Rechnung?'],
            ['¿Puedo pagar con tarjeta?', 'Kann ich mit Karte zahlen?'],
          ],
          dialogue: [
            ['Camarero', 'Buenas noches. ¿Tienen reserva?', 'Guten Abend. Haben Sie reserviert?'],
            ['Tú', 'No. ¿Tiene una mesa para dos?', 'Nein. Haben Sie einen Tisch für zwei?'],
            ['Camarero', 'Sí, claro. Aquí tienen la carta.', 'Ja, natürlich. Hier ist die Karte.'],
            ['Tú', '¿Qué nos recomienda?', 'Was empfehlen Sie uns?'],
            ['Camarero', 'La paella está muy rica hoy.', 'Die Paella ist heute sehr lecker.'],
            ['Tú', 'Perfecto, una paella para dos.', 'Perfekt, eine Paella für zwei.'],
          ],
          tip: 'Das „menú del día“ (Mittagsmenü mit Vorspeise, Hauptgang, Nachtisch und Getränk) ist in Spanien günstig und typisch. Trinkgeld ist freiwillig – 5–10 % oder Aufrunden reicht.',
        },
        {
          id: 'a1-supermercado',
          title: 'En el supermercado',
          goal: 'Einkaufen, Mengen und Preise',
          emoji: '🛒',
          words: [
            ['comprar', 'kaufen'],
            ['el supermercado', 'der Supermarkt'],
            ['el mercado', 'der Markt'],
            ['un kilo de', 'ein Kilo'],
            ['medio kilo', 'ein halbes Kilo'],
            ['una botella de', 'eine Flasche'],
            ['una barra de pan', 'ein Baguette / Stangenbrot'],
            ['un paquete de', 'eine Packung'],
            ['una lata de', 'eine Dose'],
            ['la bolsa', 'die Tüte'],
            ['barato', 'billig'],
            ['caro', 'teuer'],
            ['la oferta', 'das Angebot'],
            ['la caja', 'die Kasse'],
            ['el euro', 'der Euro'],
            ['el céntimo', 'der Cent', 'LatAm: el centavo'],
            ['¿algo más?', 'noch etwas?'],
            ['nada más', 'nichts weiter'],
            ['¿me da…?', 'geben Sie mir …?'],
          ],
          phrases: [
            ['¿Me da un kilo de tomates, por favor?', 'Geben Sie mir ein Kilo Tomaten, bitte?'],
            ['¿Algo más? – No, nada más, gracias.', 'Noch etwas? – Nein, nichts weiter, danke.'],
            ['¿Cuánto cuesta el kilo?', 'Wie viel kostet das Kilo?'],
            ['¡Qué caro!', 'Wie teuer!'],
            ['¿Necesita bolsa?', 'Brauchen Sie eine Tüte?'],
            ['Busco la leche sin lactosa.', 'Ich suche laktosefreie Milch.'],
          ],
          dialogue: [
            ['Frutero', '¡Buenos días! ¿Qué le pongo?', 'Guten Morgen! Was darf’s sein?'],
            ['Tú', 'Medio kilo de fresas y tres plátanos, por favor.', 'Ein halbes Kilo Erdbeeren und drei Bananen, bitte.'],
            ['Frutero', 'Aquí tiene. ¿Algo más?', 'Bitte sehr. Noch etwas?'],
            ['Tú', 'Nada más. ¿Cuánto es?', 'Nichts weiter. Wie viel macht das?'],
            ['Frutero', 'Cuatro euros con veinte.', 'Vier Euro zwanzig.'],
          ],
          tip: 'Auf dem Markt ist man per „usted“ oder locker per „tú“ – beides ist ok. „¿Qué le pongo?“ ist die klassische Verkäuferfrage.',
        },
        {
          id: 'a1-ropa',
          title: 'La ropa',
          goal: 'Kleidung kaufen und anprobieren',
          emoji: '👕',
          words: [
            ['la ropa', 'die Kleidung'],
            ['la camiseta', 'das T-Shirt', 'LatAm: la playera (MX) / la remera (AR)'],
            ['la camisa', 'das Hemd'],
            ['los pantalones', 'die Hose'],
            ['los vaqueros', 'die Jeans', 'LatAm: los jeans'],
            ['la falda', 'der Rock', 'LatAm: la pollera (AR)'],
            ['el vestido', 'das Kleid'],
            ['la chaqueta', 'die Jacke', 'LatAm: la chamarra (MX) / la campera (AR)'],
            ['el abrigo', 'der Mantel'],
            ['los zapatos', 'die Schuhe'],
            ['las zapatillas', 'die Turnschuhe', 'LatAm: los tenis'],
            ['la talla', 'die Größe'],
            ['probarse', 'anprobieren'],
            ['el probador', 'die Umkleidekabine'],
            ['me queda bien', 'es steht mir / passt mir'],
            ['grande', 'groß'],
            ['pequeño', 'klein'],
            ['llevar', 'tragen'],
          ],
          phrases: [
            ['¿Puedo probármelo?', 'Kann ich es anprobieren?'],
            ['¿Lo tiene en otra talla?', 'Haben Sie es in einer anderen Größe?'],
            ['Me queda un poco grande.', 'Es ist mir ein bisschen zu groß.'],
            ['¿Dónde están los probadores?', 'Wo sind die Umkleiden?'],
            ['Hoy llevo vaqueros y una camiseta.', 'Heute trage ich Jeans und ein T-Shirt.'],
            ['Me lo llevo.', 'Ich nehme es.'],
          ],
          tip: 'Bei Kleidung sagt man nicht „es passt“, sondern „me queda bien/mal“. „Me lo llevo“ ist der Satz, wenn du dich entschieden hast.',
        },
      ],
    },
    {
      id: 'a1-u3',
      title: 'Mein Alltag',
      lessons: [
        {
          id: 'a1-hora',
          title: '¿Qué hora es?',
          goal: 'Uhrzeit sagen und verstehen',
          emoji: '⏰',
          words: [
            ['¿qué hora es?', 'wie spät ist es?'],
            ['es la una', 'es ist ein Uhr'],
            ['son las dos', 'es ist zwei Uhr'],
            ['y cuarto', 'Viertel nach'],
            ['y media', 'halb (… und dreißig)'],
            ['menos cuarto', 'Viertel vor'],
            ['en punto', 'Punkt / genau'],
            ['¿a qué hora?', 'um wie viel Uhr?'],
            ['a las ocho', 'um acht Uhr'],
            ['de la mañana', 'morgens'],
            ['de la tarde', 'nachmittags'],
            ['de la noche', 'abends / nachts'],
            ['el mediodía', 'der Mittag'],
            ['la medianoche', 'die Mitternacht'],
            ['temprano', 'früh'],
            ['tarde', 'spät'],
          ],
          phrases: [
            ['Son las tres y media.', 'Es ist halb vier (3:30).'],
            ['Es la una menos cuarto.', 'Es ist Viertel vor eins.'],
            ['¿A qué hora empieza la película?', 'Um wie viel Uhr fängt der Film an?'],
            ['Quedamos a las ocho en punto.', 'Wir treffen uns um Punkt acht.'],
            ['Llego tarde, lo siento.', 'Ich komme zu spät, sorry.'],
          ],
          tip: 'Achtung: „y media“ zählt von der vollen Stunde aus: „las tres y media“ = 3:30 (nicht halb drei!). Für ein Uhr sagt man „es la una“, sonst „son las …“.',
        },
        {
          id: 'a1-dias',
          title: 'Días y meses',
          goal: 'Wochentage, Monate und Datum',
          emoji: '📅',
          words: [
            ['lunes', 'Montag'],
            ['martes', 'Dienstag'],
            ['miércoles', 'Mittwoch'],
            ['jueves', 'Donnerstag'],
            ['viernes', 'Freitag'],
            ['sábado', 'Samstag'],
            ['domingo', 'Sonntag'],
            ['el fin de semana', 'das Wochenende'],
            ['hoy', 'heute'],
            ['mañana', 'morgen'],
            ['ayer', 'gestern'],
            ['la semana', 'die Woche'],
            ['el mes', 'der Monat'],
            ['el año', 'das Jahr'],
            ['enero', 'Januar'],
            ['abril', 'April'],
            ['julio', 'Juli'],
            ['diciembre', 'Dezember'],
            ['el cumpleaños', 'der Geburtstag'],
          ],
          phrases: [
            ['Hoy es viernes. ¡Por fin!', 'Heute ist Freitag. Endlich!'],
            ['El lunes trabajo, el domingo no.', 'Am Montag arbeite ich, am Sonntag nicht.'],
            ['Mi cumpleaños es el doce de mayo.', 'Mein Geburtstag ist am zwölften Mai.'],
            ['¿Qué haces el fin de semana?', 'Was machst du am Wochenende?'],
            ['Hasta el martes.', 'Bis Dienstag.'],
          ],
          tip: 'Wochentage und Monate schreibt man klein. „Am Montag“ = „el lunes“ (ohne „en“). „Los lunes“ = montags (jeden Montag).',
        },
        {
          id: 'a1-rutina',
          title: 'Mi día',
          goal: 'Deinen Tagesablauf beschreiben',
          emoji: '🌅',
          words: [
            ['despertarse', 'aufwachen'],
            ['levantarse', 'aufstehen'],
            ['ducharse', 'duschen'],
            ['vestirse', 'sich anziehen'],
            ['desayunar', 'frühstücken'],
            ['comer', 'essen / zu Mittag essen'],
            ['cenar', 'zu Abend essen'],
            ['ir al trabajo', 'zur Arbeit gehen'],
            ['volver a casa', 'nach Hause zurückkommen'],
            ['acostarse', 'ins Bett gehen'],
            ['dormir', 'schlafen'],
            ['la siesta', 'der Mittagsschlaf'],
            ['siempre', 'immer'],
            ['normalmente', 'normalerweise'],
            ['a veces', 'manchmal'],
            ['nunca', 'nie'],
            ['luego', 'dann / später'],
            ['después', 'danach'],
          ],
          phrases: [
            ['Me levanto a las siete.', 'Ich stehe um sieben auf.'],
            ['Normalmente desayuno un café y una tostada.', 'Normalerweise frühstücke ich einen Kaffee und einen Toast.'],
            ['Después me ducho y me visto.', 'Danach dusche ich und ziehe mich an.'],
            ['Como a las dos y ceno a las nueve.', 'Ich esse um zwei zu Mittag und um neun zu Abend.'],
            ['Los domingos duermo la siesta.', 'Sonntags mache ich Mittagsschlaf.'],
            ['Me acuesto muy tarde.', 'Ich gehe sehr spät ins Bett.'],
          ],
          grammar: 'reflexivos',
          tip: 'In Spanien isst man spät: Mittagessen ca. 14–15 Uhr, Abendessen 21–22 Uhr. Reflexive Verben erkennst du am „-se“: levantarse → me levanto.',
        },
        {
          id: 'a1-casa',
          title: 'Mi casa',
          goal: 'Deine Wohnung beschreiben',
          emoji: '🏠',
          words: [
            ['el piso', 'die Wohnung', 'LatAm: el departamento / el apartamento'],
            ['la habitación', 'das Zimmer', 'LatAm auch: el cuarto / la recámara (MX)'],
            ['el dormitorio', 'das Schlafzimmer'],
            ['el salón', 'das Wohnzimmer', 'LatAm: la sala'],
            ['la cocina', 'die Küche'],
            ['el baño', 'das Bad'],
            ['el balcón', 'der Balkon'],
            ['la terraza', 'die Terrasse'],
            ['la cama', 'das Bett'],
            ['el sofá', 'das Sofa'],
            ['la nevera', 'der Kühlschrank', 'LatAm: el refrigerador / la heladera (AR)'],
            ['la lavadora', 'die Waschmaschine'],
            ['el compañero de piso', 'der Mitbewohner'],
            ['grande', 'groß'],
            ['luminoso', 'hell'],
            ['hay', 'es gibt'],
            ['al lado de', 'neben'],
            ['encima de', 'auf / über'],
          ],
          phrases: [
            ['Vivo en un piso con dos compañeros.', 'Ich wohne in einer WG mit zwei Mitbewohnern.'],
            ['Mi piso tiene tres habitaciones.', 'Meine Wohnung hat drei Zimmer.'],
            ['En el salón hay un sofá y una tele.', 'Im Wohnzimmer gibt es ein Sofa und einen Fernseher.'],
            ['La cocina es pequeña pero luminosa.', 'Die Küche ist klein, aber hell.'],
            ['El baño está al lado del dormitorio.', 'Das Bad ist neben dem Schlafzimmer.'],
          ],
          grammar: 'hay-estar',
          tip: '„Hay“ (es gibt) ist unveränderlich: hay un sofá, hay dos camas. „Piso“ heißt in Spanien Wohnung und Stockwerk.',
        },
        {
          id: 'a1-tiempo',
          title: '¿Qué tiempo hace?',
          goal: 'Über das Wetter und Jahreszeiten reden',
          emoji: '☀️',
          words: [
            ['el tiempo', 'das Wetter / die Zeit'],
            ['hace sol', 'die Sonne scheint'],
            ['hace calor', 'es ist heiß'],
            ['hace frío', 'es ist kalt'],
            ['hace viento', 'es ist windig'],
            ['hace buen tiempo', 'es ist schönes Wetter'],
            ['llueve', 'es regnet'],
            ['nieva', 'es schneit'],
            ['está nublado', 'es ist bewölkt'],
            ['la lluvia', 'der Regen'],
            ['el grado', 'das Grad'],
            ['la primavera', 'der Frühling'],
            ['el verano', 'der Sommer'],
            ['el otoño', 'der Herbst'],
            ['el invierno', 'der Winter'],
            ['el paraguas', 'der Regenschirm'],
          ],
          phrases: [
            ['¿Qué tiempo hace hoy?', 'Wie ist das Wetter heute?'],
            ['Hace mucho calor, ¡treinta y cinco grados!', 'Es ist sehr heiß, 35 Grad!'],
            ['Está lloviendo, coge el paraguas.', 'Es regnet, nimm den Regenschirm mit.', ],
            ['En invierno hace frío y nieva.', 'Im Winter ist es kalt und es schneit.'],
            ['¡Qué buen tiempo hace!', 'Was für schönes Wetter!'],
          ],
          tip: 'Wetter mit „hacer“: hace sol, hace frío. Achtung: „coger“ (nehmen) ist in Spanien normal, in vielen Ländern Lateinamerikas aber ein vulgäres Wort – dort sagt man „tomar“ oder „agarrar“.',
        },
      ],
    },
    {
      id: 'a1-u4',
      title: 'Unterwegs & Freizeit',
      lessons: [
        {
          id: 'a1-ciudad',
          title: 'En la ciudad',
          goal: 'Nach dem Weg fragen und Wegbeschreibungen verstehen',
          emoji: '🗺️',
          words: [
            ['la calle', 'die Straße'],
            ['la plaza', 'der Platz'],
            ['la estación', 'der Bahnhof'],
            ['el banco', 'die Bank'],
            ['la farmacia', 'die Apotheke'],
            ['el museo', 'das Museum'],
            ['la parada de autobús', 'die Bushaltestelle'],
            ['todo recto', 'geradeaus'],
            ['a la derecha', 'rechts'],
            ['a la izquierda', 'links'],
            ['girar', 'abbiegen'],
            ['la esquina', 'die Ecke'],
            ['cerca', 'nah'],
            ['lejos', 'weit'],
            ['enfrente de', 'gegenüber von'],
            ['¿cómo llego a…?', 'wie komme ich zu …?'],
            ['está a cinco minutos', 'es ist fünf Minuten entfernt'],
          ],
          phrases: [
            ['Perdona, ¿cómo llego a la estación?', 'Entschuldige, wie komme ich zum Bahnhof?'],
            ['Sigue todo recto y gira a la derecha.', 'Geh geradeaus und bieg rechts ab.'],
            ['¿Hay una farmacia por aquí?', 'Gibt es hier in der Nähe eine Apotheke?'],
            ['Está en la esquina, enfrente del banco.', 'Sie ist an der Ecke, gegenüber der Bank.'],
            ['¿Está lejos? – No, está a cinco minutos andando.', 'Ist es weit? – Nein, fünf Minuten zu Fuß.'],
          ],
          dialogue: [
            ['Tú', 'Perdona, ¿hay un supermercado por aquí?', 'Entschuldige, gibt es hier einen Supermarkt?'],
            ['Señor', 'Sí, sigue todo recto y la segunda a la izquierda.', 'Ja, geh geradeaus und die zweite links.'],
            ['Tú', '¿Está lejos?', 'Ist es weit?'],
            ['Señor', 'Qué va, está a dos minutos.', 'Ach was, das sind zwei Minuten.'],
            ['Tú', '¡Muchas gracias!', 'Vielen Dank!'],
          ],
          tip: '„Qué va“ ist typisch spanisch und heißt „ach was / keineswegs“. Für „Entschuldigung“ beim Ansprechen sagt man locker „perdona“ (du) oder „perdone“ (Sie).',
        },
        {
          id: 'a1-transporte',
          title: 'El transporte',
          goal: 'Verkehrsmittel nutzen und Tickets kaufen',
          emoji: '🚌',
          words: [
            ['el autobús', 'der Bus', 'LatAm: el camión (MX) / el colectivo (AR) / la guagua (Karibik)'],
            ['el metro', 'die U-Bahn'],
            ['el tren', 'der Zug'],
            ['el avión', 'das Flugzeug'],
            ['el taxi', 'das Taxi'],
            ['la bici', 'das Fahrrad'],
            ['a pie', 'zu Fuß'],
            ['el billete', 'die Fahrkarte', 'LatAm: el boleto'],
            ['de ida y vuelta', 'hin und zurück'],
            ['el andén', 'der Bahnsteig'],
            ['la salida', 'die Abfahrt / der Ausgang'],
            ['la llegada', 'die Ankunft'],
            ['el retraso', 'die Verspätung'],
            ['coger el autobús', 'den Bus nehmen', 'LatAm: tomar el autobús'],
            ['bajarse', 'aussteigen'],
            ['subir', 'einsteigen / hochgehen'],
            ['ir en…', 'mit … fahren'],
          ],
          phrases: [
            ['Un billete de ida y vuelta a Toledo, por favor.', 'Eine Hin- und Rückfahrkarte nach Toledo, bitte.'],
            ['¿De qué andén sale el tren?', 'Von welchem Bahnsteig fährt der Zug ab?'],
            ['Voy al trabajo en metro.', 'Ich fahre mit der U-Bahn zur Arbeit.'],
            ['¿Dónde me tengo que bajar?', 'Wo muss ich aussteigen?'],
            ['El tren tiene veinte minutos de retraso.', 'Der Zug hat zwanzig Minuten Verspätung.'],
          ],
          tip: 'Verkehrsmittel mit „en“: en tren, en coche – aber „a pie“ (zu Fuß). Bei Bussen gibt es extrem viele regionale Wörter!',
        },
        {
          id: 'a1-tiempo-libre',
          title: 'Tiempo libre',
          goal: 'Über Hobbys und Freizeit sprechen',
          emoji: '⚽',
          words: [
            ['el tiempo libre', 'die Freizeit'],
            ['jugar al fútbol', 'Fußball spielen'],
            ['nadar', 'schwimmen'],
            ['correr', 'laufen / joggen'],
            ['bailar', 'tanzen'],
            ['leer', 'lesen'],
            ['escuchar música', 'Musik hören'],
            ['tocar la guitarra', 'Gitarre spielen'],
            ['ver series', 'Serien schauen'],
            ['salir con amigos', 'mit Freunden ausgehen'],
            ['ir al gimnasio', 'ins Fitnessstudio gehen'],
            ['cocinar', 'kochen'],
            ['viajar', 'reisen'],
            ['hacer senderismo', 'wandern'],
            ['los videojuegos', 'die Videospiele'],
            ['el deporte', 'der Sport'],
            ['¿qué te gusta hacer?', 'was machst du gern?'],
          ],
          phrases: [
            ['¿Qué te gusta hacer en tu tiempo libre?', 'Was machst du gern in deiner Freizeit?'],
            ['Me gusta mucho bailar salsa.', 'Ich tanze sehr gern Salsa.'],
            ['Los sábados juego al fútbol con amigos.', 'Samstags spiele ich mit Freunden Fußball.'],
            ['No me gusta nada correr.', 'Ich jogge überhaupt nicht gern.'],
            ['Toco la guitarra desde hace diez años.', 'Ich spiele seit zehn Jahren Gitarre.'],
          ],
          grammar: 'gustar',
          tip: 'Achtung: „spielen“ heißt bei Sport/Spielen „jugar“, bei Instrumenten aber „tocar“: tocar el piano.',
        },
        {
          id: 'a1-cuerpo',
          title: 'El cuerpo y la salud',
          goal: 'Sagen, was dir wehtut',
          emoji: '🤒',
          words: [
            ['la cabeza', 'der Kopf'],
            ['el estómago', 'der Magen'],
            ['la garganta', 'der Hals (innen)'],
            ['la espalda', 'der Rücken'],
            ['el brazo', 'der Arm'],
            ['la pierna', 'das Bein'],
            ['la mano', 'die Hand'],
            ['el pie', 'der Fuß'],
            ['los dientes', 'die Zähne'],
            ['me duele', 'mir tut … weh'],
            ['la fiebre', 'das Fieber'],
            ['el resfriado', 'die Erkältung'],
            ['enfermo', 'krank'],
            ['la pastilla', 'die Tablette'],
            ['el médico', 'der Arzt'],
            ['estar mareado', 'schwindelig sein'],
          ],
          phrases: [
            ['Me duele la cabeza.', 'Ich habe Kopfschmerzen.'],
            ['Me duelen los pies.', 'Mir tun die Füße weh.'],
            ['Estoy enfermo, tengo fiebre.', 'Ich bin krank, ich habe Fieber.'],
            ['Necesito algo para el resfriado.', 'Ich brauche etwas gegen Erkältung.'],
            ['¿Te encuentras bien?', 'Geht es dir gut?'],
          ],
          tip: '„Doler“ funktioniert wie „gustar“: me duele la cabeza (Einzahl), me duelen los pies (Mehrzahl). Notruf in Spanien und EU: 112.',
        },
      ],
    },
  ],
};
