import type { LevelSource } from '../types';

export const A2: LevelSource = {
  id: 'A2',
  title: 'Mi vida',
  subtitle: 'Erzählen, planen, reisen – über Vergangenheit und Zukunft',
  units: [
    {
      id: 'a2-u1',
      title: 'Was hast du gemacht?',
      lessons: [
        {
          id: 'a2-hoy-he',
          title: '¿Qué has hecho hoy?',
          goal: 'Erzählen, was du heute / diese Woche gemacht hast',
          emoji: '✅',
          words: [
            ['he comido', 'ich habe gegessen'],
            ['he trabajado', 'ich habe gearbeitet'],
            ['has visto', 'du hast gesehen'],
            ['ha llamado', 'er/sie hat angerufen'],
            ['hemos hecho', 'wir haben gemacht'],
            ['ya', 'schon'],
            ['todavía no', 'noch nicht'],
            ['esta mañana', 'heute Morgen'],
            ['esta semana', 'diese Woche'],
            ['este año', 'dieses Jahr'],
            ['alguna vez', 'jemals / schon mal'],
            ['nunca', 'noch nie'],
            ['acabar de', 'gerade (etwas) getan haben'],
            ['hecho', 'gemacht'],
            ['dicho', 'gesagt'],
            ['visto', 'gesehen'],
            ['escrito', 'geschrieben'],
            ['vuelto', 'zurückgekommen'],
          ],
          phrases: [
            ['¿Qué has hecho hoy?', 'Was hast du heute gemacht?'],
            ['Esta mañana he ido al gimnasio.', 'Heute Morgen bin ich ins Fitnessstudio gegangen.'],
            ['¿Has estado alguna vez en México?', 'Warst du schon mal in Mexiko?'],
            ['Todavía no he visto la película.', 'Ich habe den Film noch nicht gesehen.'],
            ['Ya he terminado, ¡por fin!', 'Ich bin schon fertig, endlich!'],
            ['Acabo de llegar a casa.', 'Ich bin gerade nach Hause gekommen.'],
          ],
          grammar: 'perfecto',
          tip: 'In Spanien benutzt man das Perfekt (he comido) für alles, was „heute“ oder „diese Woche“ passiert ist. In Lateinamerika sagt man stattdessen meist das Indefinido: „Hoy comí paella.“',
        },
        {
          id: 'a2-ayer',
          title: 'Ayer y el fin de semana pasado',
          goal: 'Über abgeschlossene Ereignisse in der Vergangenheit erzählen',
          emoji: '⏪',
          words: [
            ['ayer', 'gestern'],
            ['anoche', 'gestern Abend / letzte Nacht'],
            ['anteayer', 'vorgestern'],
            ['el fin de semana pasado', 'letztes Wochenende'],
            ['la semana pasada', 'letzte Woche'],
            ['hace dos días', 'vor zwei Tagen'],
            ['fui', 'ich ging / war'],
            ['comí', 'ich aß'],
            ['vi', 'ich sah'],
            ['hice', 'ich machte'],
            ['estuve', 'ich war (Ort/Zustand)'],
            ['tuve', 'ich hatte'],
            ['salimos', 'wir gingen aus'],
            ['primero', 'zuerst'],
            ['luego', 'dann'],
            ['al final', 'am Ende'],
            ['¿qué tal el finde?', 'wie war das Wochenende?'],
          ],
          phrases: [
            ['¿Qué hiciste ayer?', 'Was hast du gestern gemacht?'],
            ['El sábado fuimos a la playa.', 'Am Samstag sind wir an den Strand gefahren.'],
            ['Anoche salí con unos amigos y llegué tardísimo.', 'Gestern Abend bin ich mit Freunden ausgegangen und sehr spät heimgekommen.'],
            ['Primero cenamos y luego fuimos a bailar.', 'Zuerst haben wir zu Abend gegessen und dann sind wir tanzen gegangen.'],
            ['Estuve en Barcelona hace dos años.', 'Ich war vor zwei Jahren in Barcelona.'],
            ['¿Qué tal el finde? – ¡Genial!', 'Wie war das Wochenende? – Super!'],
          ],
          dialogue: [
            ['Marta', '¿Qué tal el finde?', 'Wie war dein Wochenende?'],
            ['Tú', 'Muy bien. El sábado fui a la sierra con mi hermano.', 'Sehr gut. Am Samstag war ich mit meinem Bruder in den Bergen.'],
            ['Marta', '¡Qué bien! ¿Y el domingo?', 'Schön! Und am Sonntag?'],
            ['Tú', 'El domingo no hice nada. Vi una serie y dormí mucho.', 'Am Sonntag habe ich nichts gemacht. Ich habe eine Serie geschaut und viel geschlafen.'],
            ['Marta', 'Pues yo igual, ¡qué vagos!', 'Ich auch, wie faul wir sind!'],
          ],
          grammar: 'indefinido',
          tip: '„Ir“ und „ser“ haben im Indefinido dieselben Formen: „fui“ = ich ging ODER ich war. Der Kontext entscheidet. „Finde“ ist die lockere Kurzform von „fin de semana“.',
        },
        {
          id: 'a2-infancia',
          title: 'Cuando era pequeño',
          goal: 'Von deiner Kindheit und Gewohnheiten früher erzählen',
          emoji: '🧸',
          words: [
            ['cuando era pequeño', 'als ich klein war'],
            ['de niño', 'als Kind'],
            ['antes', 'früher'],
            ['era', 'ich war / es war'],
            ['tenía', 'ich hatte'],
            ['vivía', 'ich wohnte'],
            ['jugaba', 'ich spielte'],
            ['iba', 'ich ging (regelmäßig)'],
            ['todos los veranos', 'jeden Sommer'],
            ['siempre', 'immer'],
            ['a menudo', 'oft'],
            ['el colegio', 'die Schule'],
            ['el juguete', 'das Spielzeug'],
            ['travieso', 'frech / ungezogen'],
            ['echar de menos', 'vermissen', 'LatAm: extrañar'],
            ['acordarse de', 'sich erinnern an'],
          ],
          phrases: [
            ['Cuando era pequeña, vivía en el campo.', 'Als ich klein war, lebte ich auf dem Land.'],
            ['Todos los veranos íbamos a casa de mis abuelos.', 'Jeden Sommer fuhren wir zu meinen Großeltern.'],
            ['De niño era muy travieso.', 'Als Kind war ich sehr frech.'],
            ['Antes no me gustaba la verdura.', 'Früher mochte ich kein Gemüse.'],
            ['Echo de menos esos tiempos.', 'Ich vermisse diese Zeiten.'],
            ['¿Te acuerdas de nuestro profesor?', 'Erinnerst du dich an unseren Lehrer?'],
          ],
          grammar: 'imperfecto',
          tip: 'Das Imperfecto beschreibt Gewohnheiten und Hintergründe („wie es früher war“). Das Indefinido erzählt einzelne abgeschlossene Ereignisse.',
        },
      ],
    },
    {
      id: 'a2-u2',
      title: 'Reisen',
      lessons: [
        {
          id: 'a2-viaje',
          title: 'De viaje',
          goal: 'Eine Reise planen und am Flughafen zurechtkommen',
          emoji: '✈️',
          words: [
            ['el viaje', 'die Reise'],
            ['las vacaciones', 'der Urlaub'],
            ['el aeropuerto', 'der Flughafen'],
            ['el vuelo', 'der Flug'],
            ['la maleta', 'der Koffer', 'LatAm auch: la valija (AR)'],
            ['el equipaje de mano', 'das Handgepäck'],
            ['el pasaporte', 'der Reisepass'],
            ['la tarjeta de embarque', 'die Bordkarte'],
            ['la puerta de embarque', 'das Gate'],
            ['facturar', 'Gepäck aufgeben'],
            ['despegar', 'abheben'],
            ['aterrizar', 'landen'],
            ['reservar', 'buchen / reservieren'],
            ['el destino', 'das Reiseziel'],
            ['hacer la maleta', 'Koffer packen'],
            ['perder el vuelo', 'den Flug verpassen'],
            ['la playa', 'der Strand'],
            ['la montaña', 'die Berge'],
          ],
          phrases: [
            ['¿Dónde puedo facturar la maleta?', 'Wo kann ich den Koffer aufgeben?'],
            ['Mi vuelo sale a las diez de la puerta B12.', 'Mein Flug geht um zehn vom Gate B12.'],
            ['Este verano vamos a ir a Perú.', 'Diesen Sommer fahren wir nach Peru.'],
            ['Todavía no he hecho la maleta.', 'Ich habe den Koffer noch nicht gepackt.'],
            ['¡Casi pierdo el vuelo!', 'Fast hätte ich den Flug verpasst!'],
            ['¿Prefieres playa o montaña?', 'Lieber Strand oder Berge?'],
          ],
          grammar: 'ir-a',
          tip: '„Ir a + Infinitiv“ ist die einfachste Zukunft: Voy a viajar = Ich werde reisen. Wird im Alltag viel öfter benutzt als das Futur.',
        },
        {
          id: 'a2-hotel',
          title: 'En el hotel',
          goal: 'Einchecken, Fragen stellen und Probleme melden',
          emoji: '🏨',
          words: [
            ['la habitación doble', 'das Doppelzimmer'],
            ['la habitación individual', 'das Einzelzimmer'],
            ['la reserva', 'die Reservierung'],
            ['la recepción', 'die Rezeption'],
            ['el desayuno incluido', 'Frühstück inklusive'],
            ['la llave', 'der Schlüssel'],
            ['el ascensor', 'der Aufzug', 'LatAm auch: el elevador'],
            ['la planta', 'das Stockwerk'],
            ['la toalla', 'das Handtuch'],
            ['el aire acondicionado', 'die Klimaanlage'],
            ['la contraseña del wifi', 'das WLAN-Passwort'],
            ['no funciona', 'funktioniert nicht'],
            ['hacer el check-in', 'einchecken'],
            ['dejar la habitación', 'auschecken'],
            ['la noche', 'die Nacht'],
            ['tranquilo', 'ruhig'],
          ],
          phrases: [
            ['Tengo una reserva a nombre de Müller.', 'Ich habe eine Reservierung auf den Namen Müller.'],
            ['¿El desayuno está incluido?', 'Ist das Frühstück inklusive?'],
            ['¿Cuál es la contraseña del wifi?', 'Wie ist das WLAN-Passwort?'],
            ['El aire acondicionado no funciona.', 'Die Klimaanlage funktioniert nicht.'],
            ['¿A qué hora hay que dejar la habitación?', 'Bis wann muss man das Zimmer räumen?'],
            ['¿Me puede dar otra toalla?', 'Können Sie mir noch ein Handtuch geben?'],
          ],
          dialogue: [
            ['Recepcionista', 'Buenas tardes, ¿en qué puedo ayudarle?', 'Guten Tag, wie kann ich Ihnen helfen?'],
            ['Tú', 'Hola, tengo una reserva para tres noches.', 'Hallo, ich habe eine Reservierung für drei Nächte.'],
            ['Recepcionista', '¿A nombre de quién?', 'Auf welchen Namen?'],
            ['Tú', 'De Schneider.', 'Schneider.'],
            ['Recepcionista', 'Perfecto. Habitación 305, tercera planta. El ascensor está a la derecha.', 'Perfekt. Zimmer 305, dritter Stock. Der Aufzug ist rechts.'],
          ],
          tip: 'Im Hotel ist „usted“ üblich (Sie-Form). Die Verbform ist dieselbe wie für er/sie: ¿Me puede ayudar?',
        },
        {
          id: 'a2-medico',
          title: 'En el médico',
          goal: 'Beim Arzt Symptome beschreiben',
          emoji: '🩺',
          words: [
            ['la cita', 'der Termin'],
            ['el síntoma', 'das Symptom'],
            ['la tos', 'der Husten'],
            ['la gripe', 'die Grippe'],
            ['estar resfriado', 'erkältet sein'],
            ['la alergia', 'die Allergie'],
            ['la receta', 'das Rezept'],
            ['el jarabe', 'der Hustensaft'],
            ['la herida', 'die Wunde'],
            ['vomitar', 'sich übergeben'],
            ['tener náuseas', 'Übelkeit haben'],
            ['desde hace', 'seit'],
            ['grave', 'schlimm / ernst'],
            ['el seguro médico', 'die Krankenversicherung'],
            ['las urgencias', 'die Notaufnahme'],
            ['tomar', 'einnehmen'],
          ],
          phrases: [
            ['Quería pedir cita con el médico.', 'Ich wollte einen Arzttermin vereinbaren.'],
            ['Tengo tos y me duele la garganta desde hace tres días.', 'Ich habe seit drei Tagen Husten und Halsschmerzen.'],
            ['Soy alérgico a la penicilina.', 'Ich bin allergisch gegen Penicillin.'],
            ['Tome una pastilla cada ocho horas.', 'Nehmen Sie alle acht Stunden eine Tablette.'],
            ['¿Es grave, doctora?', 'Ist es schlimm, Frau Doktor?'],
            ['Tengo la tarjeta sanitaria europea.', 'Ich habe die Europäische Krankenversicherungskarte.'],
          ],
          tip: '„Quería“ (ich wollte) ist eine sehr höfliche Art, um etwas zu bitten – wie im Deutschen „ich hätte gern“.',
        },
      ],
    },
    {
      id: 'a2-u3',
      title: 'Leute & Pläne',
      lessons: [
        {
          id: 'a2-quedar',
          title: '¿Quedamos?',
          goal: 'Sich verabreden, zusagen und absagen',
          emoji: '📲',
          words: [
            ['quedar', 'sich verabreden'],
            ['¿quedamos?', 'treffen wir uns?'],
            ['¿te apetece…?', 'hast du Lust auf …?', 'LatAm: ¿tienes ganas de…? / ¿te provoca…? (CO)'],
            ['tener ganas de', 'Lust haben auf'],
            ['estar libre', 'Zeit haben / frei sein'],
            ['estar ocupado', 'beschäftigt sein'],
            ['me viene bien', 'passt mir gut'],
            ['no puedo', 'ich kann nicht'],
            ['otro día', 'ein andermal'],
            ['¿a qué hora quedamos?', 'um wie viel Uhr treffen wir uns?'],
            ['¿dónde quedamos?', 'wo treffen wir uns?'],
            ['vale, perfecto', 'okay, perfekt'],
            ['cancelar', 'absagen'],
            ['el plan', 'der Plan'],
            ['¡me apunto!', 'ich bin dabei!'],
            ['¡qué pena!', 'wie schade!'],
          ],
          phrases: [
            ['¿Te apetece tomar algo esta tarde?', 'Hast du Lust, heute Nachmittag etwas trinken zu gehen?'],
            ['¿Quedamos el viernes a las ocho?', 'Treffen wir uns Freitag um acht?'],
            ['Lo siento, el viernes no puedo. ¿Qué tal el sábado?', 'Tut mir leid, Freitag kann ich nicht. Wie wäre Samstag?'],
            ['¡Me apunto! ¿Dónde quedamos?', 'Ich bin dabei! Wo treffen wir uns?'],
            ['Me viene fatal, ¿lo dejamos para otro día?', 'Passt mir gar nicht, verschieben wir es auf ein andermal?'],
            ['Te escribo cuando salga del trabajo.', 'Ich schreibe dir, wenn ich von der Arbeit komme.'],
          ],
          dialogue: [
            ['Javi', 'Oye, ¿te apetece ir al cine esta noche?', 'Hey, hast du Lust heute Abend ins Kino zu gehen?'],
            ['Tú', 'Hoy no puedo, estoy hasta arriba de trabajo.', 'Heute kann ich nicht, ich ertrinke in Arbeit.'],
            ['Javi', '¡Qué pena! ¿Y mañana?', 'Wie schade! Und morgen?'],
            ['Tú', 'Mañana me viene genial. ¿A qué hora quedamos?', 'Morgen passt mir super. Um wie viel Uhr treffen wir uns?'],
            ['Javi', 'A las nueve en la puerta del cine.', 'Um neun vor dem Kino.'],
            ['Tú', 'Vale, ¡hasta mañana!', 'Okay, bis morgen!'],
          ],
          tip: '„Quedar“ ist DAS Verb für Verabredungen in Spanien. „Estar hasta arriba“ = total ausgelastet sein.',
        },
        {
          id: 'a2-sentimientos',
          title: 'Emociones',
          goal: 'Gefühle ausdrücken und darauf reagieren',
          emoji: '😊',
          words: [
            ['contento', 'froh / zufrieden'],
            ['feliz', 'glücklich'],
            ['triste', 'traurig'],
            ['enfadado', 'wütend / sauer', 'LatAm: enojado'],
            ['nervioso', 'nervös'],
            ['preocupado', 'besorgt'],
            ['agobiado', 'gestresst / überfordert'],
            ['aburrido', 'gelangweilt'],
            ['emocionado', 'aufgeregt / gerührt'],
            ['sorprendido', 'überrascht'],
            ['tener miedo', 'Angst haben'],
            ['tener vergüenza', 'sich schämen'],
            ['estar harto de', 'die Nase voll haben von'],
            ['¡qué bien!', 'wie schön!'],
            ['¡qué rabia!', 'wie ärgerlich!'],
            ['¡qué fuerte!', 'krass! / heftig!'],
            ['¡ánimo!', 'Kopf hoch!'],
          ],
          phrases: [
            ['Estoy muy contenta con mi nuevo trabajo.', 'Ich bin sehr froh über meinen neuen Job.'],
            ['¿Por qué estás enfadado?', 'Warum bist du sauer?'],
            ['Estoy un poco agobiada con los exámenes.', 'Ich bin ein bisschen gestresst wegen der Prüfungen.'],
            ['Estoy harto de la lluvia.', 'Ich habe die Nase voll vom Regen.'],
            ['¡Qué fuerte! No me lo puedo creer.', 'Krass! Ich kann es nicht glauben.'],
            ['¡Ánimo! Todo va a salir bien.', 'Kopf hoch! Alles wird gut.'],
          ],
          grammar: 'ser-estar',
          tip: 'Gefühle sind Zustände, darum „estar“: estoy triste. Achtung: „estar aburrido“ = gelangweilt sein, „ser aburrido“ = langweilig sein!',
        },
        {
          id: 'a2-fiestas',
          title: 'Fiestas y celebraciones',
          goal: 'Gratulieren, feiern und Traditionen kennenlernen',
          emoji: '🎉',
          words: [
            ['la fiesta', 'die Party / das Fest'],
            ['¡feliz cumpleaños!', 'alles Gute zum Geburtstag!'],
            ['¡felicidades!', 'herzlichen Glückwunsch!'],
            ['¡enhorabuena!', 'Glückwunsch! (zu einem Erfolg)'],
            ['¡salud!', 'Prost! / Gesundheit!'],
            ['el regalo', 'das Geschenk'],
            ['la tarta', 'die Torte', 'LatAm: el pastel / la torta'],
            ['las velas', 'die Kerzen'],
            ['la Navidad', 'Weihnachten'],
            ['la Nochevieja', 'Silvester'],
            ['las uvas', 'die Trauben'],
            ['la boda', 'die Hochzeit'],
            ['invitar', 'einladen'],
            ['celebrar', 'feiern'],
            ['brindar', 'anstoßen'],
            ['los Reyes Magos', 'die Heiligen Drei Könige'],
          ],
          phrases: [
            ['¡Feliz cumpleaños! ¡Que cumplas muchos más!', 'Alles Gute zum Geburtstag! Auf viele weitere!'],
            ['Te invito a mi fiesta el sábado.', 'Ich lade dich am Samstag zu meiner Party ein.'],
            ['¡Enhorabuena por el nuevo trabajo!', 'Glückwunsch zum neuen Job!'],
            ['¡Feliz Navidad y próspero Año Nuevo!', 'Frohe Weihnachten und ein gutes neues Jahr!'],
            ['Brindemos por los novios. ¡Salud!', 'Lasst uns auf das Brautpaar anstoßen. Prost!'],
          ],
          tip: 'In Spanien isst man an Silvester zu jedem der 12 Glockenschläge eine Traube (las doce uvas). Geschenke bringen dort traditionell die Heiligen Drei Könige am 6. Januar.',
        },
        {
          id: 'a2-telefono',
          title: 'Al teléfono y por mensaje',
          goal: 'Telefonieren und Nachrichten schreiben',
          emoji: '📞',
          words: [
            ['¿dígame?', 'Hallo? (am Telefon)', 'LatAm: ¿aló? / ¿bueno? (MX)'],
            ['¿de parte de quién?', 'wer spricht da?'],
            ['un momento', 'einen Moment'],
            ['no se oye bien', 'man hört schlecht'],
            ['se ha cortado', 'die Verbindung ist abgebrochen'],
            ['llamar', 'anrufen'],
            ['devolver la llamada', 'zurückrufen'],
            ['el mensaje', 'die Nachricht'],
            ['mandar un audio', 'eine Sprachnachricht schicken'],
            ['el contestador', 'der Anrufbeantworter'],
            ['la batería', 'der Akku'],
            ['cargar el móvil', 'das Handy aufladen'],
            ['la cobertura', 'der Empfang (Netz)'],
            ['te paso a…', 'ich gebe dich weiter an …'],
            ['equivocarse de número', 'sich verwählen'],
          ],
          phrases: [
            ['¿Dígame? – Hola, ¿está Carmen?', 'Hallo? – Hallo, ist Carmen da?'],
            ['Ahora no puede ponerse. ¿Quieres dejarle un mensaje?', 'Sie kann gerade nicht. Willst du ihr eine Nachricht hinterlassen?'],
            ['Perdona, no te oigo bien, no tengo cobertura.', 'Sorry, ich höre dich schlecht, ich habe keinen Empfang.'],
            ['Te llamo luego, me queda poca batería.', 'Ich ruf dich später an, mein Akku ist fast leer.'],
            ['Te mando un audio, que estoy conduciendo.', 'Ich schick dir eine Sprachnachricht, ich fahre gerade.'],
            ['Perdone, me he equivocado de número.', 'Entschuldigung, ich habe mich verwählt.'],
          ],
          tip: 'In Chats schreibt man oft Abkürzungen: „q“ (que), „xq“ (porque), „tb“ (también), „bss“ (besos), „jajaja“ (Lachen). Spanier lieben Sprachnachrichten!',
        },
      ],
    },
    {
      id: 'a2-u4',
      title: 'Welt um mich',
      lessons: [
        {
          id: 'a2-naturaleza',
          title: 'Naturaleza y animales',
          goal: 'Über Natur, Tiere und Ausflüge sprechen',
          emoji: '🌳',
          words: [
            ['la naturaleza', 'die Natur'],
            ['el campo', 'das Land / das Feld'],
            ['el bosque', 'der Wald'],
            ['el río', 'der Fluss'],
            ['el lago', 'der See'],
            ['el mar', 'das Meer'],
            ['la isla', 'die Insel'],
            ['el cielo', 'der Himmel'],
            ['la flor', 'die Blume'],
            ['el árbol', 'der Baum'],
            ['el perro', 'der Hund'],
            ['el gato', 'die Katze'],
            ['el pájaro', 'der Vogel'],
            ['el caballo', 'das Pferd'],
            ['la vaca', 'die Kuh'],
            ['la mascota', 'das Haustier'],
            ['el paisaje', 'die Landschaft'],
            ['la excursión', 'der Ausflug'],
          ],
          phrases: [
            ['¿Tienes mascota? – Sí, tengo un perro que se llama Toby.', 'Hast du ein Haustier? – Ja, einen Hund namens Toby.'],
            ['El domingo hicimos una excursión al lago.', 'Am Sonntag haben wir einen Ausflug zum See gemacht.'],
            ['¡Qué paisaje tan bonito!', 'Was für eine schöne Landschaft!'],
            ['Me encanta pasear por el bosque.', 'Ich liebe es, im Wald spazieren zu gehen.'],
            ['Prefiero el mar a la montaña.', 'Ich ziehe das Meer den Bergen vor.'],
          ],
          tip: '„¡Qué + Nomen + tan + Adjektiv!“ ist eine sehr natürliche Ausrufform: ¡Qué día tan bonito!',
        },
        {
          id: 'a2-piso',
          title: 'Buscando piso',
          goal: 'Eine Wohnung suchen und mieten',
          emoji: '🔑',
          words: [
            ['alquilar', 'mieten'],
            ['el alquiler', 'die Miete'],
            ['el casero', 'der Vermieter', 'LatAm: el dueño / el arrendador'],
            ['la fianza', 'die Kaution', 'LatAm: el depósito'],
            ['el contrato', 'der Vertrag'],
            ['amueblado', 'möbliert'],
            ['los gastos incluidos', 'Nebenkosten inklusive'],
            ['el barrio', 'das Viertel'],
            ['el anuncio', 'die Anzeige'],
            ['metros cuadrados', 'Quadratmeter'],
            ['exterior', 'nach außen gelegen'],
            ['interior', 'zum Innenhof gelegen'],
            ['la mudanza', 'der Umzug'],
            ['mudarse', 'umziehen'],
            ['visitar el piso', 'die Wohnung besichtigen'],
            ['el vecino', 'der Nachbar'],
          ],
          phrases: [
            ['Llamo por el anuncio del piso.', 'Ich rufe wegen der Wohnungsanzeige an.'],
            ['¿Los gastos están incluidos en el alquiler?', 'Sind die Nebenkosten in der Miete inbegriffen?'],
            ['¿Cuándo puedo ver el piso?', 'Wann kann ich die Wohnung besichtigen?'],
            ['Hay que pagar dos meses de fianza.', 'Man muss zwei Monatsmieten Kaution zahlen.'],
            ['Me mudo el mes que viene.', 'Ich ziehe nächsten Monat um.'],
            ['El barrio es tranquilo y está bien comunicado.', 'Das Viertel ist ruhig und gut angebunden.'],
          ],
          tip: '„Exterior“ heißt, die Wohnung hat Fenster zur Straße – in Spanien ein wichtiges Kriterium, weil „interior“-Wohnungen oft dunkel sind.',
        },
        {
          id: 'a2-tecnologia',
          title: 'Tecnología',
          goal: 'Über Handy, Internet und Technikprobleme sprechen',
          emoji: '💻',
          words: [
            ['el ordenador', 'der Computer', 'LatAm: la computadora'],
            ['el portátil', 'der Laptop', 'LatAm: la laptop'],
            ['la pantalla', 'der Bildschirm'],
            ['la contraseña', 'das Passwort'],
            ['descargar', 'herunterladen'],
            ['subir una foto', 'ein Foto hochladen'],
            ['las redes sociales', 'die sozialen Netzwerke'],
            ['el correo electrónico', 'die E-Mail'],
            ['la aplicación', 'die App'],
            ['actualizar', 'aktualisieren'],
            ['se ha colgado', 'hat sich aufgehängt'],
            ['reiniciar', 'neu starten'],
            ['el cargador', 'das Ladegerät'],
            ['enchufar', 'einstecken'],
            ['guardar', 'speichern'],
            ['borrar', 'löschen'],
          ],
          phrases: [
            ['Se me ha colgado el ordenador.', 'Mein Computer hat sich aufgehängt.'],
            ['¿Has probado a reiniciarlo?', 'Hast du versucht, ihn neu zu starten?'],
            ['He olvidado mi contraseña.', 'Ich habe mein Passwort vergessen.'],
            ['¿Me pasas el cargador?', 'Gibst du mir mal das Ladegerät?'],
            ['Te mando el archivo por correo.', 'Ich schicke dir die Datei per Mail.'],
            ['Paso demasiado tiempo en las redes sociales.', 'Ich verbringe zu viel Zeit in sozialen Netzwerken.'],
          ],
          tip: '„Se me ha…“ ist typisch für ungewollte Missgeschicke: Se me ha caído el móvil (Mir ist das Handy runtergefallen) – es klingt, als wäre es „einfach passiert“.',
        },
      ],
    },
  ],
};
