import type { LevelSource } from '../types';

export const B1: LevelSource = {
  id: 'B1',
  title: 'Me defiendo',
  subtitle: 'Meinungen, Wünsche, Ratschläge – sich frei unterhalten',
  units: [
    {
      id: 'b1-u1',
      title: 'Meinung & Wünsche',
      lessons: [
        {
          id: 'b1-opinion',
          title: 'En mi opinión…',
          goal: 'Deine Meinung sagen, zustimmen und widersprechen',
          emoji: '💭',
          words: [
            ['creo que', 'ich glaube, dass'],
            ['pienso que', 'ich denke, dass'],
            ['en mi opinión', 'meiner Meinung nach'],
            ['para mí', 'für mich'],
            ['estoy de acuerdo', 'ich bin einverstanden'],
            ['no estoy de acuerdo', 'ich bin nicht einverstanden'],
            ['tienes razón', 'du hast recht'],
            ['depende', 'kommt drauf an'],
            ['no creo que', 'ich glaube nicht, dass'],
            ['me parece que', 'mir scheint, dass'],
            ['¿qué te parece?', 'was hältst du davon?'],
            ['la verdad es que', 'ehrlich gesagt'],
            ['por un lado', 'einerseits'],
            ['por otro lado', 'andererseits'],
            ['sin embargo', 'jedoch'],
            ['¡ni de broma!', 'auf keinen Fall!'],
            ['¡exacto!', 'genau!'],
          ],
          phrases: [
            ['¿Qué te parece la nueva ley?', 'Was hältst du von dem neuen Gesetz?'],
            ['Creo que tienes razón.', 'Ich glaube, du hast recht.'],
            ['No creo que sea buena idea.', 'Ich glaube nicht, dass das eine gute Idee ist.'],
            ['La verdad es que no lo sé, depende.', 'Ehrlich gesagt weiß ich es nicht, es kommt drauf an.'],
            ['Por un lado es barato, pero por otro lado está lejos.', 'Einerseits ist es billig, andererseits ist es weit weg.'],
            ['No estoy de acuerdo contigo para nada.', 'Ich bin überhaupt nicht deiner Meinung.'],
          ],
          dialogue: [
            ['Elena', '¿Qué te parece trabajar desde casa?', 'Was hältst du davon, von zu Hause zu arbeiten?'],
            ['Tú', 'Para mí es genial. Ahorro mucho tiempo.', 'Für mich ist es super. Ich spare viel Zeit.'],
            ['Elena', 'Ya, pero ¿no crees que te sientes un poco solo?', 'Ja, aber glaubst du nicht, dass man sich etwas einsam fühlt?'],
            ['Tú', 'Bueno, depende. Por eso voy a la oficina dos días a la semana.', 'Na ja, kommt drauf an. Deshalb gehe ich zwei Tage die Woche ins Büro.'],
            ['Elena', 'Tienes razón, eso es lo mejor.', 'Du hast recht, das ist das Beste.'],
          ],
          grammar: 'subjuntivo',
          tip: 'Nach „creo que“ steht der Indikativ, nach „no creo que“ der Subjuntivo: Creo que es verdad. / No creo que sea verdad.',
        },
        {
          id: 'b1-consejos',
          title: 'Dar consejos',
          goal: 'Ratschläge geben und um Rat fragen',
          emoji: '🧭',
          words: [
            ['el consejo', 'der Rat(schlag)'],
            ['aconsejar', 'raten'],
            ['deberías', 'du solltest'],
            ['yo que tú', 'an deiner Stelle'],
            ['yo en tu lugar', 'ich an deiner Stelle'],
            ['¿por qué no…?', 'warum … nicht?'],
            ['te recomiendo que', 'ich empfehle dir, dass'],
            ['es mejor que', 'es ist besser, dass'],
            ['hace falta', 'es ist nötig'],
            ['tener en cuenta', 'berücksichtigen'],
            ['¿qué harías tú?', 'was würdest du machen?'],
            ['no te preocupes', 'mach dir keine Sorgen'],
            ['tranquilo', 'ruhig / keine Panik'],
            ['merecer la pena', 'sich lohnen', 'LatAm: valer la pena'],
            ['intentar', 'versuchen'],
          ],
          phrases: [
            ['Yo que tú, hablaría con ella.', 'An deiner Stelle würde ich mit ihr reden.'],
            ['Deberías descansar más.', 'Du solltest dich mehr ausruhen.'],
            ['¿Por qué no lo intentas otra vez?', 'Warum versuchst du es nicht noch mal?'],
            ['Te recomiendo que vayas al médico.', 'Ich empfehle dir, zum Arzt zu gehen.'],
            ['No te preocupes, tiene solución.', 'Mach dir keine Sorgen, das lässt sich lösen.'],
            ['¿Merece la pena ir a Sevilla en agosto?', 'Lohnt es sich, im August nach Sevilla zu fahren?'],
          ],
          grammar: 'condicional',
          tip: '„Yo que tú“ + Konditional ist die natürlichste Art, Rat zu geben: Yo que tú, no iría.',
        },
        {
          id: 'b1-futuro',
          title: 'Planes de futuro',
          goal: 'Über Zukunftspläne, Träume und Vermutungen sprechen',
          emoji: '🔮',
          words: [
            ['el futuro', 'die Zukunft'],
            ['el sueño', 'der Traum'],
            ['el objetivo', 'das Ziel'],
            ['algún día', 'eines Tages'],
            ['dentro de cinco años', 'in fünf Jahren'],
            ['el año que viene', 'nächstes Jahr'],
            ['tener pensado', 'vorhaben'],
            ['me gustaría', 'ich würde gern'],
            ['ojalá', 'hoffentlich'],
            ['seguramente', 'sicherlich'],
            ['quizás', 'vielleicht'],
            ['estará', 'er/sie wird sein / ist wohl'],
            ['tendré', 'ich werde haben'],
            ['haré', 'ich werde machen'],
            ['podré', 'ich werde können'],
            ['cuando tenga tiempo', 'wenn ich Zeit habe'],
          ],
          phrases: [
            ['Algún día viviré en la playa.', 'Eines Tages werde ich am Strand wohnen.'],
            ['Me gustaría aprender a surfear.', 'Ich würde gern surfen lernen.'],
            ['¡Ojalá haga buen tiempo mañana!', 'Hoffentlich ist morgen schönes Wetter!'],
            ['Cuando tenga dinero, viajaré por Sudamérica.', 'Wenn ich Geld habe, reise ich durch Südamerika.'],
            ['¿Dónde estará Pedro? – Estará en el atasco.', 'Wo Pedro wohl ist? – Er steckt bestimmt im Stau.'],
            ['Tengo pensado cambiar de trabajo.', 'Ich habe vor, den Job zu wechseln.'],
          ],
          grammar: 'futuro',
          tip: 'Das Futur drückt auch Vermutungen aus: „Serán las tres“ = Es ist wohl drei Uhr. Nach „cuando“ (Zukunft) steht der Subjuntivo: cuando llegues.',
        },
        {
          id: 'b1-deseos',
          title: 'Deseos y sentimientos',
          goal: 'Wünsche ausdrücken und auf Nachrichten reagieren',
          emoji: '🌠',
          words: [
            ['espero que', 'ich hoffe, dass'],
            ['quiero que', 'ich will, dass'],
            ['me alegro de que', 'ich freue mich, dass'],
            ['siento que', 'es tut mir leid, dass'],
            ['me molesta que', 'es stört mich, dass'],
            ['me da miedo que', 'ich habe Angst, dass'],
            ['¡que te mejores!', 'gute Besserung!'],
            ['¡que lo pases bien!', 'viel Spaß!'],
            ['¡que tengas suerte!', 'viel Glück!'],
            ['¡que aproveche!', 'guten Appetit!'],
            ['¡que descanses!', 'schlaf gut / ruh dich aus!'],
            ['¡qué pena que…!', 'wie schade, dass …!'],
            ['echar de menos', 'vermissen'],
            ['sorprender', 'überraschen'],
          ],
          phrases: [
            ['Espero que te guste el regalo.', 'Ich hoffe, dir gefällt das Geschenk.'],
            ['Me alegro mucho de que estés aquí.', 'Ich freue mich sehr, dass du hier bist.'],
            ['¡Que te mejores pronto!', 'Gute Besserung!'],
            ['Quiero que me digas la verdad.', 'Ich will, dass du mir die Wahrheit sagst.'],
            ['¡Qué pena que no puedas venir!', 'Wie schade, dass du nicht kommen kannst!'],
            ['Me molesta que llegue siempre tarde.', 'Es stört mich, dass er immer zu spät kommt.'],
          ],
          grammar: 'subjuntivo',
          tip: 'Viele feste Wünsche beginnen mit „¡Que…!“ + Subjuntivo. Die wirst du ständig hören – lerne sie als Ganzes!',
        },
      ],
    },
    {
      id: 'b1-u2',
      title: 'Beziehungen & Arbeit',
      lessons: [
        {
          id: 'b1-relaciones',
          title: 'Relaciones',
          goal: 'Über Freundschaft, Liebe und Konflikte sprechen',
          emoji: '❤️',
          words: [
            ['la pareja', 'der/die Partner(in) / das Paar'],
            ['enamorarse de', 'sich verlieben in'],
            ['salir con alguien', 'mit jemandem zusammen sein'],
            ['ligar', 'flirten / jemanden aufreißen'],
            ['cortar con', 'Schluss machen mit', 'LatAm: terminar con'],
            ['la amistad', 'die Freundschaft'],
            ['el mejor amigo', 'der beste Freund'],
            ['llevarse bien', 'sich gut verstehen'],
            ['llevarse mal', 'sich schlecht verstehen'],
            ['discutir', 'streiten / diskutieren'],
            ['la pelea', 'der Streit'],
            ['hacer las paces', 'sich versöhnen'],
            ['confiar en', 'vertrauen'],
            ['los celos', 'die Eifersucht'],
            ['echar de menos', 'vermissen'],
            ['el compromiso', 'die Verpflichtung / Verlobung'],
            ['casarse', 'heiraten'],
          ],
          phrases: [
            ['Me llevo muy bien con mi suegra.', 'Ich verstehe mich sehr gut mit meiner Schwiegermutter.'],
            ['Llevan cinco años saliendo juntos.', 'Sie sind seit fünf Jahren zusammen.'],
            ['Ayer discutimos, pero ya hemos hecho las paces.', 'Gestern haben wir gestritten, aber wir haben uns schon versöhnt.'],
            ['Se enamoró de él a primera vista.', 'Sie verliebte sich auf den ersten Blick in ihn.'],
            ['Confío en ti.', 'Ich vertraue dir.'],
            ['¿Por qué cortaste con ella?', 'Warum hast du mit ihr Schluss gemacht?'],
          ],
          tip: '„Llevar + Zeit + Gerundium“ ist eine sehr natürliche Art, eine Dauer auszudrücken: Llevo dos años estudiando español = Ich lerne seit zwei Jahren Spanisch.',
        },
        {
          id: 'b1-trabajo',
          title: 'Buscar trabajo',
          goal: 'Bewerbung, Vorstellungsgespräch und Arbeitswelt',
          emoji: '📄',
          words: [
            ['el currículum', 'der Lebenslauf'],
            ['la entrevista de trabajo', 'das Vorstellungsgespräch'],
            ['la oferta de empleo', 'das Stellenangebot'],
            ['el puesto', 'die Stelle'],
            ['el sueldo', 'das Gehalt'],
            ['la experiencia', 'die Erfahrung'],
            ['el contrato indefinido', 'unbefristeter Vertrag'],
            ['la jornada completa', 'Vollzeit'],
            ['media jornada', 'Teilzeit'],
            ['el compañero de trabajo', 'der Kollege'],
            ['la reunión', 'das Meeting'],
            ['el plazo', 'die Frist'],
            ['contratar', 'einstellen'],
            ['despedir', 'kündigen / entlassen'],
            ['el punto fuerte', 'die Stärke'],
            ['el punto débil', 'die Schwäche'],
            ['trabajar en equipo', 'im Team arbeiten'],
          ],
          phrases: [
            ['Le escribo en relación con la oferta de empleo.', 'Ich schreibe Ihnen bezüglich des Stellenangebots.'],
            ['Tengo tres años de experiencia en marketing.', 'Ich habe drei Jahre Erfahrung im Marketing.'],
            ['Mi punto fuerte es que me gusta trabajar en equipo.', 'Meine Stärke ist, dass ich gerne im Team arbeite.'],
            ['¿Cuál es el sueldo?', 'Wie hoch ist das Gehalt?'],
            ['Tengo una reunión a las diez, hablamos luego.', 'Ich habe um zehn ein Meeting, wir sprechen später.'],
            ['Me han contratado, ¡empiezo el lunes!', 'Sie haben mich eingestellt, ich fange Montag an!'],
          ],
          tip: 'In Bewerbungen und mit Vorgesetzten benutzt man anfangs „usted“. In vielen spanischen Firmen duzt man sich aber schnell.',
        },
        {
          id: 'b1-quejas',
          title: 'Problemas y quejas',
          goal: 'Sich beschweren und Probleme lösen',
          emoji: '😤',
          words: [
            ['la queja', 'die Beschwerde'],
            ['quejarse', 'sich beschweren'],
            ['la hoja de reclamaciones', 'das Beschwerdeformular'],
            ['devolver', 'zurückgeben'],
            ['el reembolso', 'die Rückerstattung'],
            ['estar roto', 'kaputt sein'],
            ['estropearse', 'kaputtgehen'],
            ['la garantía', 'die Garantie'],
            ['el ticket', 'der Kassenbon'],
            ['es inaceptable', 'das ist inakzeptabel'],
            ['el error', 'der Fehler'],
            ['solucionar', 'lösen'],
            ['el encargado', 'der Verantwortliche / Filialleiter'],
            ['¿me puede atender?', 'können Sie mir helfen?'],
            ['cambiar', 'umtauschen'],
          ],
          phrases: [
            ['Quería devolver estos zapatos, están rotos.', 'Ich möchte diese Schuhe zurückgeben, sie sind kaputt.'],
            ['¿Puedo hablar con el encargado?', 'Kann ich mit dem Filialleiter sprechen?'],
            ['Creo que hay un error en la cuenta.', 'Ich glaube, in der Rechnung ist ein Fehler.'],
            ['Llevo una hora esperando, es inaceptable.', 'Ich warte seit einer Stunde, das ist inakzeptabel.'],
            ['¿Me lo pueden cambiar o devolverme el dinero?', 'Können Sie es umtauschen oder mir das Geld zurückgeben?'],
            ['Se me ha estropeado la lavadora.', 'Meine Waschmaschine ist kaputtgegangen.'],
          ],
          tip: 'In Spanien muss jedes Geschäft eine „hoja de reclamaciones“ haben. Schon die Frage danach wirkt oft Wunder.',
        },
      ],
    },
    {
      id: 'b1-u3',
      title: 'Gesellschaft & Leben',
      lessons: [
        {
          id: 'b1-salud',
          title: 'Vida sana',
          goal: 'Über Gesundheit, Ernährung und Lebensstil sprechen',
          emoji: '🥗',
          words: [
            ['la salud', 'die Gesundheit'],
            ['sano', 'gesund'],
            ['la dieta equilibrada', 'ausgewogene Ernährung'],
            ['hacer ejercicio', 'Sport treiben'],
            ['ponerse en forma', 'fit werden'],
            ['adelgazar', 'abnehmen'],
            ['engordar', 'zunehmen'],
            ['el estrés', 'der Stress'],
            ['dejar de fumar', 'mit dem Rauchen aufhören'],
            ['dormir bien', 'gut schlafen'],
            ['el hábito', 'die Gewohnheit'],
            ['la comida basura', 'das Junkfood', 'LatAm: la comida chatarra'],
            ['evitar', 'vermeiden'],
            ['relajarse', 'sich entspannen'],
            ['la meditación', 'die Meditation'],
          ],
          phrases: [
            ['Intento comer sano, pero me encanta el chocolate.', 'Ich versuche gesund zu essen, aber ich liebe Schokolade.'],
            ['He dejado de fumar hace un año.', 'Ich habe vor einem Jahr mit dem Rauchen aufgehört.'],
            ['Es importante que duermas al menos siete horas.', 'Es ist wichtig, dass du mindestens sieben Stunden schläfst.'],
            ['Quiero ponerme en forma para el verano.', 'Ich will bis zum Sommer fit werden.'],
            ['El estrés me está matando.', 'Der Stress bringt mich um.'],
          ],
          tip: '„Dejar de + Infinitiv“ = mit etwas aufhören. „Volver a + Infinitiv“ = etwas wieder tun: He vuelto a fumar.',
        },
        {
          id: 'b1-medios',
          title: 'Noticias y medios',
          goal: 'Nachrichten verstehen und darüber sprechen',
          emoji: '📰',
          words: [
            ['las noticias', 'die Nachrichten'],
            ['el periódico', 'die Zeitung'],
            ['el titular', 'die Schlagzeile'],
            ['el artículo', 'der Artikel'],
            ['el periodista', 'der Journalist'],
            ['la entrevista', 'das Interview'],
            ['según', 'laut / gemäß'],
            ['informar', 'berichten'],
            ['ocurrir', 'geschehen'],
            ['la encuesta', 'die Umfrage'],
            ['el bulo', 'die Falschmeldung', 'LatAm: la noticia falsa / fake news'],
            ['hacerse viral', 'viral gehen'],
            ['el pódcast', 'der Podcast'],
            ['la tele', 'der Fernseher / das Fernsehen'],
            ['¿te has enterado de…?', 'hast du mitbekommen …?'],
          ],
          phrases: [
            ['¿Te has enterado de lo que ha pasado?', 'Hast du mitbekommen, was passiert ist?'],
            ['Según el periódico, mañana hay huelga.', 'Laut Zeitung gibt es morgen einen Streik.'],
            ['Ese vídeo se ha hecho viral.', 'Das Video ist viral gegangen.'],
            ['No te creas todo lo que lees en internet.', 'Glaub nicht alles, was du im Internet liest.'],
            ['Escucho un pódcast en español cada mañana.', 'Ich höre jeden Morgen einen spanischen Podcast.'],
          ],
          tip: 'Tipp zum Lernen: Spanische Nachrichten in einfacher Sprache findest du z. B. bei RTVE oder in Podcasts für Lernende. „Enterarse“ = etwas mitbekommen/erfahren – ein Alltagswort!',
        },
        {
          id: 'b1-cocina',
          title: 'En la cocina',
          goal: 'Rezepte verstehen und Anweisungen geben',
          emoji: '👩‍🍳',
          words: [
            ['la receta', 'das Rezept'],
            ['los ingredientes', 'die Zutaten'],
            ['cortar', 'schneiden'],
            ['pelar', 'schälen'],
            ['freír', 'frittieren / braten'],
            ['hervir', 'kochen (Wasser)'],
            ['mezclar', 'mischen'],
            ['añadir', 'hinzufügen'],
            ['echar', 'hineingeben'],
            ['el horno', 'der Ofen'],
            ['la sartén', 'die Pfanne'],
            ['la olla', 'der Topf'],
            ['una pizca de sal', 'eine Prise Salz'],
            ['a fuego lento', 'bei schwacher Hitze'],
            ['la cebolla', 'die Zwiebel'],
            ['el ajo', 'der Knoblauch'],
          ],
          phrases: [
            ['Primero, pela las patatas y córtalas en rodajas.', 'Zuerst die Kartoffeln schälen und in Scheiben schneiden.'],
            ['Fríe la cebolla a fuego lento.', 'Brate die Zwiebel bei schwacher Hitze.'],
            ['Añade una pizca de sal y mézclalo todo.', 'Gib eine Prise Salz dazu und misch alles.'],
            ['Mete la tortilla en el horno diez minutos.', 'Schieb die Tortilla zehn Minuten in den Ofen.'],
            ['¿Me pasas la receta?', 'Gibst du mir das Rezept?'],
          ],
          grammar: 'imperativo',
          tip: 'Rezepte und Anleitungen stehen oft im Imperativ (pela, corta, añade). Pronomen werden angehängt: córtalas, mézclalo.',
        },
        {
          id: 'b1-coloquial',
          title: 'Español coloquial',
          goal: 'Typische Umgangssprache verstehen und benutzen',
          emoji: '😎',
          words: [
            ['guay', 'cool', 'LatAm: chévere (Karibik, CO) / padre (MX) / copado (AR)'],
            ['mola', 'ist cool / gefällt mir'],
            ['tío / tía', 'Alter / Mann (Anrede)', 'LatAm: güey (MX) / che (AR) / parce (CO)'],
            ['flipar', 'ausflippen / krass finden'],
            ['currar', 'arbeiten (locker)', 'LatAm: chambear (MX, PE)'],
            ['el curro', 'der Job (locker)', 'LatAm: la chamba'],
            ['la pasta', 'die Kohle (Geld)', 'LatAm: la lana (MX) / la plata'],
            ['¡qué morro!', 'wie dreist!'],
            ['estar flipado', 'total baff sein'],
            ['ser un rollo', 'nervig/langweilig sein'],
            ['¡venga!', 'komm schon! / los!'],
            ['¡anda ya!', 'ach komm! / nie im Leben!'],
            ['¡ostras!', 'oh Mann! / Mist!'],
            ['¡qué va!', 'ach was!'],
            ['en plan', 'so wie / quasi'],
            ['vale la pena', 'es lohnt sich'],
          ],
          phrases: [
            ['¡Qué guay tu chaqueta, tía!', 'Deine Jacke ist ja cool!'],
            ['Me mola mucho este barrio.', 'Mir gefällt dieses Viertel echt gut.'],
            ['Estoy flipando con el precio.', 'Ich fasse es nicht bei dem Preis.'],
            ['Mañana curro a las siete, ¡qué rollo!', 'Morgen arbeite ich um sieben, wie nervig!'],
            ['¡Venga, vamos, que llegamos tarde!', 'Komm schon, los, wir kommen zu spät!'],
            ['Era en plan… súper raro.', 'Es war so… total komisch.'],
          ],
          tip: 'Umgangssprache ist stark regional! „Guay“ und „tío“ sind typisch spanisch. In Mexiko hörst du „qué padre“ und „güey“, in Argentinien „copado“ und „che“, in Kolumbien „chévere“ und „parce“.',
        },
      ],
    },
  ],
};
