import type { LevelSource } from '../types';

export const B2: LevelSource = {
  id: 'B2',
  title: 'Con soltura',
  subtitle: 'Argumentieren, Nuancen, Redewendungen – wie ein Muttersprachler',
  units: [
    {
      id: 'b2-u1',
      title: 'Argumentieren',
      lessons: [
        {
          id: 'b2-hipotesis',
          title: 'Si yo fuera…',
          goal: 'Hypothesen und irreale Bedingungen ausdrücken',
          emoji: '🤷',
          words: [
            ['si fuera', 'wenn ich wäre'],
            ['si tuviera', 'wenn ich hätte'],
            ['si pudiera', 'wenn ich könnte'],
            ['si supiera', 'wenn ich wüsste'],
            ['haría', 'ich würde machen'],
            ['iría', 'ich würde gehen'],
            ['diría', 'ich würde sagen'],
            ['en caso de que', 'falls'],
            ['a no ser que', 'es sei denn'],
            ['siempre que', 'vorausgesetzt, dass'],
            ['con tal de que', 'solange / sofern'],
            ['de haberlo sabido', 'hätte ich es gewusst'],
            ['como si', 'als ob'],
            ['suponer', 'annehmen'],
            ['imaginarse', 'sich vorstellen'],
          ],
          phrases: [
            ['Si tuviera más tiempo, aprendería a tocar el piano.', 'Wenn ich mehr Zeit hätte, würde ich Klavier spielen lernen.'],
            ['Si fuera tú, no le diría nada.', 'Wenn ich du wäre, würde ich ihm nichts sagen.'],
            ['Te ayudo, siempre que me invites a un café.', 'Ich helfe dir, vorausgesetzt du lädst mich auf einen Kaffee ein.'],
            ['Habla como si lo supiera todo.', 'Er redet, als ob er alles wüsste.'],
            ['Iremos a la playa, a no ser que llueva.', 'Wir gehen an den Strand, es sei denn, es regnet.'],
            ['¿Qué harías si te tocara la lotería?', 'Was würdest du tun, wenn du im Lotto gewinnen würdest?'],
          ],
          dialogue: [
            ['Andrés', '¿Qué harías si te tocara la lotería?', 'Was würdest du machen, wenn du im Lotto gewinnst?'],
            ['Tú', 'Primero dejaría el curro, eso seguro.', 'Zuerst würde ich den Job kündigen, ganz sicher.'],
            ['Andrés', '¿Y luego?', 'Und dann?'],
            ['Tú', 'Me compraría una casa en Canarias y viajaría por todo el mundo.', 'Ich würde mir ein Haus auf den Kanaren kaufen und um die ganze Welt reisen.'],
            ['Andrés', 'Pues si te toca, ¡acuérdate de mí!', 'Na, wenn du gewinnst, denk an mich!'],
          ],
          grammar: 'si-condicional',
          tip: 'Irreale Bedingung: si + Subjuntivo imperfecto (tuviera), Hauptsatz im Konditional (haría). Nie „si + Konditional“!',
        },
        {
          id: 'b2-debate',
          title: 'Debatir',
          goal: 'Argumente strukturieren und überzeugen',
          emoji: '🎙️',
          words: [
            ['en primer lugar', 'erstens'],
            ['además', 'außerdem'],
            ['por lo tanto', 'deshalb / folglich'],
            ['no obstante', 'nichtsdestotrotz'],
            ['aunque', 'obwohl / auch wenn'],
            ['a pesar de', 'trotz'],
            ['en cambio', 'hingegen'],
            ['es decir', 'das heißt'],
            ['en definitiva', 'letztendlich'],
            ['hay que tener en cuenta', 'man muss berücksichtigen'],
            ['desde mi punto de vista', 'aus meiner Sicht'],
            ['es evidente que', 'es ist offensichtlich, dass'],
            ['no cabe duda de que', 'es besteht kein Zweifel, dass'],
            ['estar a favor de', 'dafür sein'],
            ['estar en contra de', 'dagegen sein'],
            ['el argumento', 'das Argument'],
            ['convencer', 'überzeugen'],
          ],
          phrases: [
            ['Desde mi punto de vista, es una medida necesaria.', 'Aus meiner Sicht ist das eine notwendige Maßnahme.'],
            ['Aunque sea caro, merece la pena.', 'Auch wenn es teuer ist, lohnt es sich.'],
            ['Estoy en contra de prohibirlo, ya que no soluciona nada.', 'Ich bin dagegen, es zu verbieten, da es nichts löst.'],
            ['No cabe duda de que el clima está cambiando.', 'Es besteht kein Zweifel, dass sich das Klima verändert.'],
            ['En definitiva, hay que buscar un equilibrio.', 'Letztendlich muss man ein Gleichgewicht finden.'],
            ['Entiendo tu postura; no obstante, no la comparto.', 'Ich verstehe deine Position; dennoch teile ich sie nicht.'],
          ],
          grammar: 'conectores',
          tip: '„Aunque“ + Indikativ = obwohl (Tatsache). „Aunque“ + Subjuntivo = auch wenn (egal ob). Aunque llueve, salgo / Aunque llueva, saldré.',
        },
        {
          id: 'b2-sociedad',
          title: 'Sociedad y política',
          goal: 'Über gesellschaftliche Themen diskutieren',
          emoji: '🏛️',
          words: [
            ['la sociedad', 'die Gesellschaft'],
            ['el gobierno', 'die Regierung'],
            ['las elecciones', 'die Wahlen'],
            ['votar', 'wählen'],
            ['el derecho', 'das Recht'],
            ['la igualdad', 'die Gleichheit'],
            ['la desigualdad', 'die Ungleichheit'],
            ['la vivienda', 'der Wohnraum'],
            ['el desempleo', 'die Arbeitslosigkeit'],
            ['la inmigración', 'die Einwanderung'],
            ['la manifestación', 'die Demonstration'],
            ['la huelga', 'der Streik'],
            ['la ley', 'das Gesetz'],
            ['el ciudadano', 'der Bürger'],
            ['el cambio climático', 'der Klimawandel'],
            ['la sostenibilidad', 'die Nachhaltigkeit'],
            ['reciclar', 'recyceln'],
          ],
          phrases: [
            ['El acceso a la vivienda es uno de los mayores problemas de los jóvenes.', 'Der Zugang zu Wohnraum ist eines der größten Probleme junger Leute.'],
            ['Mucha gente salió a la calle para protestar.', 'Viele Menschen gingen auf die Straße, um zu protestieren.'],
            ['Es fundamental que todos los ciudadanos voten.', 'Es ist grundlegend, dass alle Bürger wählen.'],
            ['Hay que tomar medidas contra el cambio climático.', 'Man muss Maßnahmen gegen den Klimawandel ergreifen.'],
            ['La desigualdad ha aumentado en los últimos años.', 'Die Ungleichheit hat in den letzten Jahren zugenommen.'],
          ],
          tip: 'Nach unpersönlichen Ausdrücken wie „es importante / fundamental / necesario que“ steht immer der Subjuntivo.',
        },
        {
          id: 'b2-dinero',
          title: 'Economía y dinero',
          goal: 'Über Geld, Banken und Wirtschaft sprechen',
          emoji: '💶',
          words: [
            ['ahorrar', 'sparen'],
            ['gastar', 'ausgeben'],
            ['el préstamo', 'der Kredit'],
            ['la hipoteca', 'die Hypothek'],
            ['la cuenta bancaria', 'das Bankkonto'],
            ['la transferencia', 'die Überweisung'],
            ['los impuestos', 'die Steuern'],
            ['la factura', 'die Rechnung'],
            ['el presupuesto', 'das Budget / der Kostenvoranschlag'],
            ['la inflación', 'die Inflation'],
            ['subir los precios', 'die Preise erhöhen'],
            ['llegar a fin de mes', 'über die Runden kommen'],
            ['invertir', 'investieren'],
            ['la deuda', 'die Schuld(en)'],
            ['estar sin blanca', 'pleite sein', 'LatAm: estar sin un peso / estar quebrado'],
            ['costar un ojo de la cara', 'ein Vermögen kosten'],
          ],
          phrases: [
            ['Cada vez cuesta más llegar a fin de mes.', 'Es wird immer schwieriger, über die Runden zu kommen.'],
            ['Te hago una transferencia esta tarde.', 'Ich überweise dir das heute Nachmittag.'],
            ['Este mes estoy sin blanca.', 'Diesen Monat bin ich pleite.'],
            ['El piso nos costó un ojo de la cara.', 'Die Wohnung hat uns ein Vermögen gekostet.'],
            ['Intento ahorrar un diez por ciento de mi sueldo.', 'Ich versuche, zehn Prozent meines Gehalts zu sparen.'],
          ],
          tip: 'Spanisch ist voller bildhafter Ausdrücke rund ums Geld: „costar un ojo de la cara“ (ein Auge aus dem Gesicht kosten) = sündhaft teuer.',
        },
      ],
    },
    {
      id: 'b2-u2',
      title: 'Wie Muttersprachler',
      lessons: [
        {
          id: 'b2-expresiones',
          title: 'Expresiones idiomáticas',
          goal: 'Die beliebtesten Redewendungen verstehen und benutzen',
          emoji: '🦜',
          words: [
            ['estar en las nubes', 'mit den Gedanken woanders sein'],
            ['tomar el pelo', 'jemanden auf den Arm nehmen'],
            ['meter la pata', 'ins Fettnäpfchen treten'],
            ['ponerse las pilas', 'sich ranhalten / Gas geben'],
            ['no tener pelos en la lengua', 'kein Blatt vor den Mund nehmen'],
            ['ser pan comido', 'ein Kinderspiel sein'],
            ['estar hecho polvo', 'fix und fertig sein'],
            ['dar la lata', 'nerven'],
            ['echar una mano', 'helfen / mit anpacken'],
            ['costar un ojo de la cara', 'sündhaft teuer sein'],
            ['estar como una cabra', 'total verrückt sein'],
            ['tirar la toalla', 'das Handtuch werfen'],
            ['ir al grano', 'zur Sache kommen'],
            ['quedarse de piedra', 'wie versteinert sein'],
            ['ser la leche', 'der Hammer sein'],
            ['no pegar ojo', 'kein Auge zutun'],
          ],
          phrases: [
            ['Perdona, estaba en las nubes. ¿Qué decías?', 'Sorry, ich war in Gedanken. Was hast du gesagt?'],
            ['¿Me estás tomando el pelo?', 'Willst du mich auf den Arm nehmen?'],
            ['¡Qué metedura de pata! Le pregunté por su ex.', 'Was für ein Fettnäpfchen! Ich habe ihn nach seiner Ex gefragt.'],
            ['Tengo que ponerme las pilas con el español.', 'Ich muss mich beim Spanisch ranhalten.'],
            ['El examen fue pan comido.', 'Die Prüfung war ein Kinderspiel.'],
            ['¿Me echas una mano con la mudanza?', 'Hilfst du mir beim Umzug?'],
            ['Anoche no pegué ojo.', 'Letzte Nacht habe ich kein Auge zugetan.'],
          ],
          tip: 'Redewendungen machen dein Spanisch lebendig. Fang mit 3–4 an, die du wirklich benutzt – z. B. „echar una mano“ und „ponerse las pilas“ hört man überall.',
        },
        {
          id: 'b2-matices',
          title: 'Matices y suavizar',
          goal: 'Höflich, diplomatisch und nuanciert formulieren',
          emoji: '🪶',
          words: [
            ['quizá', 'vielleicht'],
            ['a lo mejor', 'vielleicht (locker)'],
            ['puede que', 'es kann sein, dass'],
            ['igual', 'vielleicht (umgangssprachlich)'],
            ['más bien', 'eher'],
            ['un poco', 'ein bisschen'],
            ['¿te importaría…?', 'würde es dir etwas ausmachen …?'],
            ['¿sería posible…?', 'wäre es möglich …?'],
            ['no es por nada, pero', 'nichts für ungut, aber'],
            ['la verdad es que', 'ehrlich gesagt'],
            ['digamos que', 'sagen wir mal'],
            ['o sea', 'also / das heißt'],
            ['bueno', 'na ja / also'],
            ['pues', 'also / na ja'],
            ['vamos', 'sprich / ich meine'],
          ],
          phrases: [
            ['¿Te importaría bajar un poco la música?', 'Würde es dir etwas ausmachen, die Musik etwas leiser zu machen?'],
            ['Puede que tengas razón.', 'Es kann sein, dass du recht hast.'],
            ['A lo mejor vamos al concierto, no sé.', 'Vielleicht gehen wir zum Konzert, mal sehen.'],
            ['No es por nada, pero ese color no te queda bien.', 'Nichts für ungut, aber die Farbe steht dir nicht.'],
            ['Digamos que no es mi plato favorito.', 'Sagen wir mal, es ist nicht mein Lieblingsgericht.'],
            ['Bueno, pues… o sea, que no vienes, ¿no?', 'Na ja, also… du kommst also nicht, oder?'],
          ],
          tip: 'Füllwörter wie „pues“, „bueno“, „o sea“ und „vamos“ geben dir Zeit zum Nachdenken und klingen sehr natürlich. „Puede que“ verlangt den Subjuntivo, „a lo mejor“ den Indikativ.',
        },
        {
          id: 'b2-narrar',
          title: 'Contar una anécdota',
          goal: 'Lebendig erzählen – Spannung aufbauen und Geschichten verbinden',
          emoji: '📖',
          words: [
            ['resulta que', 'es stellte sich heraus, dass / also'],
            ['de repente', 'plötzlich'],
            ['en ese momento', 'in dem Moment'],
            ['mientras', 'während'],
            ['al cabo de un rato', 'nach einer Weile'],
            ['total, que', 'kurz und gut'],
            ['había quedado', 'ich hatte mich verabredet'],
            ['se me olvidó', 'ich habe vergessen'],
            ['no te lo vas a creer', 'du wirst es nicht glauben'],
            ['¿y qué pasó?', 'und was ist passiert?'],
            ['¡no me digas!', 'echt jetzt?! / sag bloß!'],
            ['al final', 'am Ende'],
            ['menos mal que', 'zum Glück'],
            ['la casualidad', 'der Zufall'],
            ['darse cuenta de', 'merken / bemerken'],
          ],
          phrases: [
            ['No te lo vas a creer: resulta que mi vecino es primo de mi jefe.', 'Du wirst es nicht glauben: Es stellt sich heraus, dass mein Nachbar der Cousin meines Chefs ist.'],
            ['Estaba esperando el bus cuando de repente empezó a llover.', 'Ich wartete auf den Bus, als es plötzlich zu regnen begann.'],
            ['Cuando llegué, ya se había ido.', 'Als ich ankam, war er schon gegangen.'],
            ['Total, que perdimos el tren.', 'Kurz und gut, wir haben den Zug verpasst.'],
            ['Menos mal que llevaba paraguas.', 'Zum Glück hatte ich einen Schirm dabei.'],
            ['Al salir me di cuenta de que no tenía las llaves.', 'Beim Rausgehen merkte ich, dass ich die Schlüssel nicht hatte.'],
          ],
          grammar: 'pasados',
          tip: 'Gute Geschichten mischen die Zeiten: Imperfecto für den Hintergrund (estaba esperando), Indefinido für die Handlung (empezó), Pluscuamperfecto für das, was davor geschah (se había ido).',
        },
        {
          id: 'b2-cultura',
          title: 'Cultura y arte',
          goal: 'Über Filme, Bücher, Musik und Kunst diskutieren',
          emoji: '🎭',
          words: [
            ['la obra', 'das Werk'],
            ['el cuadro', 'das Gemälde'],
            ['la exposición', 'die Ausstellung'],
            ['la novela', 'der Roman'],
            ['el escritor', 'der Schriftsteller'],
            ['el director', 'der Regisseur'],
            ['la trama', 'die Handlung'],
            ['el personaje', 'die Figur'],
            ['el final', 'das Ende'],
            ['emocionante', 'spannend / bewegend'],
            ['impresionante', 'beeindruckend'],
            ['un rollo', 'langweilig'],
            ['recomendar', 'empfehlen'],
            ['estrenar', 'erstmals aufführen / herausbringen'],
            ['el estreno', 'die Premiere'],
            ['los subtítulos', 'die Untertitel'],
            ['en versión original', 'im Original'],
          ],
          phrases: [
            ['¿Has visto la última película de Almodóvar?', 'Hast du den neuesten Film von Almodóvar gesehen?'],
            ['La trama engancha desde el principio.', 'Die Handlung fesselt von Anfang an.'],
            ['El final me dejó con la boca abierta.', 'Das Ende hat mich sprachlos gemacht.'],
            ['Prefiero ver las series en versión original con subtítulos.', 'Ich schaue Serien lieber im Original mit Untertiteln.'],
            ['Te la recomiendo, es una obra maestra.', 'Ich empfehle sie dir, sie ist ein Meisterwerk.'],
          ],
          tip: 'Lerntipp: Schau spanische Serien (z. B. „La casa de papel“, „Élite“, „Narcos“ für Kolumbien/Mexiko) mit spanischen Untertiteln – das trainiert Hören und Lesen gleichzeitig.',
        },
        {
          id: 'b2-negociar',
          title: 'Negociar y convencer',
          goal: 'Verhandeln, Kompromisse finden und Einwände entkräften',
          emoji: '🤝',
          words: [
            ['negociar', 'verhandeln'],
            ['la propuesta', 'der Vorschlag'],
            ['proponer', 'vorschlagen'],
            ['llegar a un acuerdo', 'sich einigen'],
            ['ceder', 'nachgeben'],
            ['el compromiso', 'der Kompromiss'],
            ['la condición', 'die Bedingung'],
            ['el descuento', 'der Rabatt'],
            ['rebajar', 'reduzieren'],
            ['¿qué tal si…?', 'wie wäre es, wenn …?'],
            ['lo máximo que puedo ofrecer', 'das Maximum, das ich anbieten kann'],
            ['me lo pensaré', 'ich werde darüber nachdenken'],
            ['trato hecho', 'abgemacht'],
            ['partir la diferencia', 'sich in der Mitte treffen'],
            ['regatear', 'feilschen'],
          ],
          phrases: [
            ['¿Qué tal si lo dejamos en cincuenta euros?', 'Wie wäre es, wenn wir uns auf fünfzig Euro einigen?'],
            ['Es lo máximo que puedo ofrecerle.', 'Das ist das Maximum, das ich Ihnen anbieten kann.'],
            ['Si me hace un descuento, me llevo dos.', 'Wenn Sie mir einen Rabatt geben, nehme ich zwei.'],
            ['Me parece justo. ¡Trato hecho!', 'Klingt fair. Abgemacht!'],
            ['Déjeme pensarlo y le digo algo mañana.', 'Lassen Sie mich darüber nachdenken, ich melde mich morgen.'],
          ],
          tip: 'Auf Märkten in Lateinamerika ist Feilschen (regatear) oft üblich, in spanischen Geschäften dagegen kaum.',
        },
        {
          id: 'b2-ciencia',
          title: 'Ciencia y futuro',
          goal: 'Über Technologie, Wissenschaft und Zukunft diskutieren',
          emoji: '🚀',
          words: [
            ['la inteligencia artificial', 'die künstliche Intelligenz'],
            ['el avance', 'der Fortschritt'],
            ['la investigación', 'die Forschung'],
            ['el descubrimiento', 'die Entdeckung'],
            ['el riesgo', 'das Risiko'],
            ['la ventaja', 'der Vorteil'],
            ['el inconveniente', 'der Nachteil'],
            ['sustituir', 'ersetzen'],
            ['la energía renovable', 'erneuerbare Energie'],
            ['los datos', 'die Daten'],
            ['la privacidad', 'die Privatsphäre'],
            ['a largo plazo', 'langfristig'],
            ['a corto plazo', 'kurzfristig'],
            ['plantear', 'aufwerfen / stellen (Frage)'],
            ['el reto', 'die Herausforderung'],
          ],
          phrases: [
            ['La inteligencia artificial plantea muchos retos éticos.', 'Künstliche Intelligenz wirft viele ethische Herausforderungen auf.'],
            ['¿Crees que las máquinas sustituirán a los humanos?', 'Glaubst du, dass Maschinen die Menschen ersetzen werden?'],
            ['A largo plazo, las energías renovables son más baratas.', 'Langfristig sind erneuerbare Energien günstiger.'],
            ['Tiene sus ventajas y sus inconvenientes.', 'Es hat seine Vor- und Nachteile.'],
            ['Me preocupa la privacidad de mis datos.', 'Ich mache mir Sorgen um den Schutz meiner Daten.'],
          ],
          tip: 'Viele Wörter auf -ción, -dad und -ismo sind fast international: la investigación, la sostenibilidad, el turismo. Sie sind alle weiblich (außer -ismo: männlich).',
        },
      ],
    },
  ],
};
